### ISSUE TITLE
markSeen: true not working

### ISSUE THREAD

**Issue by nhagen** [mscdex/node-imap#157]
When markSeen: true, emails are not marked read when I finish fetching all unseen mail using the master branch.

 19     ImapConnection  = require('./node-imap/lib/imap').ImapConnection,
 20     //ImapConnection  = require('imap'),

However, using the npm imap module, it works as expected, so this was broken very recently (if at all).

This works:
 19     //ImapConnection  = require('./node-imap/lib/imap').ImapConnection,
 20     ImapConnection  = require('imap'),

**Comment by anks333** [comment]
`imap.openBox("INBOX", false, function(err, mailBox) {
        if (err) {
            console.error(err);
            return;
        }
        imap.search(["UNSEEN"], function(err, results) {

            imap.setFlags(results, ['\\Seen'], function(err) {
                if (!err) {
                    console.log("marked as read");
                } else {
                    console.log(JSON.stringify(err, null, 2));
                }
            });

            var f = imap.seq.fetch(results, { bodies: "" });
            f.on("message", processMessage);
            f.once("error", function(err) {
                return Promise.reject(err);
            });
            f.once("end", function() {
                console.log("Done fetching all unseen messages.");
                imap.end();
            });
        });
    });`

processMessage

`function processMessage(msg seqno){
         //use mailparser
}`


I don't know why my code is not getting properly formatted here,
so basically results contains the uuid

we need to call imap.setFlags([uuids], ['\\Seen'], cb) function to make it mark as read
