### ISSUE TITLE
Can't Delete Gmail Message

### ISSUE THREAD

**Issue by zishon89us** [mscdex/node-imap#224]
imap.addFlags(results, 'DELETED', function(err) {
                                if(err)
                                    console.log('Email Not Deleted');
                                else
                                    console.log('Email Deleted');
                            });

passed results as a range, tried with single id but nothing worked; any suggestion @mscdex thnx

**Comment by nikolina93** [comment]
Can you please help me. this code works for me but I need to remove/move the message from Inbox to Trash is it possible?
