### ISSUE TITLE
Issues with XOAUTH2

### ISSUE THREAD

**Issue by thinkkevin** [mscdex/node-imap#233]
I am trying to use XOAUTH2 to connect to google IMAP, I updated the Connections constructor method by allowing set config.xoauth2.

Could you help check why this happened, and how to fix it?

```
<= '* OK Gimap ready for requests from 50.156.50.203 qk7if1705226pac.117'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH AUTH=XOAUTH2'
<= 'A0 OK Thats all she wrote! qk7if1705226pac.117'
=> 'A1 AUTHENTICATE XOAUTH2 xxxx'
<= '+ eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ=='
<= 'A1 NO Invalid SASL argument. qk7if1705226pac.117'
{ [Error: {"status":"400","schemes":"Bearer","scope":"https://mail.google.com/"}] textCode: undefined, source: 'authentication' }
```

My imap options:

```
{ host: 'imap.gmail.com',
  port: 993,
  tls: true,
  user: 'xxxxxxxxxxx@gmail.com',
  password: '',
  xoauth2: 'xxxx',
  tlsOptions: { rejectUnauthorized: false },
  debug: console.log
}
```

**Comment by scopsy** [comment]
I'm using xoauth2 module and having the same issue 
'A1 BAD Invalid SASL argument

**Comment by viktorjansson** [comment]
Make sure your xoauth2 string is formatted like this 

`new Imap({xoauth2:btoa("user="+USER+"\x01auth=Bearer "+TOKEN+"\x01\x01"), ... })`

**Comment by iggyZiggy** [comment]
got this issue when I generated xoauth2 with wrong username/email address, i misspelled field name so i guess I was passing undefined instead of real username

**Comment by fhackenb** [comment]
Anything obviously wrong with what I'm doing here below? I'm getting an error: "Invalid credentials (failure)" error and trying to format it the same way as @viktorjansson and the google oauth2 docs suggest. To generate the xoauth2 params, I'm using the refresh token that was returned from oauth2

const xoauthParams = {
       user: authorizedEmail.email,
       clientId: client_id,
       clientSecret: client_secret,
       refreshToken: authorizedEmail.refreshToken
};
          console.log("xoauth params:", xoauthParams);
          const xoauth2gen = xoauth2.createXOAuth2Generator(xoauthParams);

xoauth2gen.getToken(function(err, accessToken){
              if(err){
                  return console.log(err);
              }
              console.log("AUTH XOAUTH2 " + accessToken);
              
              const preBase64String = "user="+email+"\x01auth=Bearer "+accessToken+"\x01\x01"; 
              const base64Token = Encode.encode(preBase64String, 'base64');
              
              const imap = new Imap({
                xoauth2: base64Token,
                host: 'imap.gmail.com',
                port: 993,
                tls: true
              });
              imap.once('error', error => {
                console.log('Imap error!');
                console.log(error);
              });
              imap.once('end', () => {
                console.log('imap is done...');
              });              
              imap.connect();
              
              
          });

**Comment by mscdex** [comment]
@fhackenb There is a separate example in `xoauth2`'s readme for google accounts. It appears you are not supplying the expected object to `createXOAuth2Generator`.

**Comment by fhackenb** [comment]
Thanks for the prompt reply! I figured out that the issue was with my scopes when authorizing with OAuth2. I needed to add "https://mail.google.com/" to my list of scopes
