### ISSUE TITLE
"Error: connect ECONNREFUSED" when connecting through a proxy server

### ISSUE THREAD

**Issue by danielnode** [mscdex/node-imap#342]
I'm using a proxy server and getting following error:

 { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  source: 'socket' }

How can I fix this problem?

**Comment by merajseraji** [comment]
I have the same problem and I can't get mails with imap behind a proxy. Is this issue completed?
If Imap use Socket connection, then how can I use it with proxy?

**Comment by ravitejara-kore** [comment]
Does anyone have a solution for this. 

@merajseraji have you achieved a solution for your use-case?
