### ISSUE TITLE
Connection.js:722  / throw new Error('Nothing to fetch');

### ISSUE THREAD

**Issue by eldiablolives** [mscdex/node-imap#350]
I am retrieving the messages from server and storing them into local DB

then on the second run I determine what's my last message (date) then run:

[ 'ALL', ['SINCE',''+ latestDate] ]

this causes the above error since there are no new messages since that date. I could work around it BUT the resolution of latestDate is in DAYS rather than seconds (or less) so as to not get the same error I would have to fetch ALL SINCE -1 DAY and then de-dupe in DB which may amount to quite a few emails for one day resolution

**Comment by SnowdenWintermute** [comment]
After struggling with this and trying to catch the error in several ways, I ended up just checking if results was empty or nonexistent and returning null if it was.
`
                if (!results || !results.length) return null;
                const f = imap.fetch(results, { bodies: "" });
`
