### ISSUE TITLE
Gmail: getting Error: read ETIMEDOUT after a few minutes

### ISSUE THREAD

**Issue by fabdrol** [mscdex/node-imap#366]
After a few minutes I'm getting a ETIMEDOUT error while using gmail. I can't catch the error, and the error causes the process to crash... Any ideas?

```
[2014-03-20 09:59:44][Adapter: stdio] Received message from ***@starting-point.nl
[2014-03-20 10:10:23][Adapter: stdio] error { [Error: read ETIMEDOUT]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'read',
  source: 'socket' }

Error: read ETIMEDOUT
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

As you can see, the process crashes after `00:10:39`. It's not always exactly that, but it's usually around the 10 minutes mark when it times out...

**Comment by jdtzmn** [comment]
Just thought I should mention that this has started happening to me now also in case it affects anything. @mscdex @fabdrol

**Comment by mscdex** [comment]
@tvvignesh If you're not getting an `ETIMEDOUT` error, then it's a different issue. If you want to try, you can force NOOP-based keepalive by setting `keepalive: { forceNoop: true }` in the connection config.
