### ISSUE TITLE
How to get other folder mail( such as sent mail , Drafts) through single connection

### ISSUE THREAD

**Issue by alagukaja** [mscdex/node-imap#374]
i need to get all box mail.. see my code in below 

imap.once('ready', function ()
{
    imap.getBoxes(function more(err, boxes, path)
    {
        if (err)
            throw err;
        if (!path)
            path = '';
        for (var key in boxes)
        {
            if (boxes[key].children)
                more(undefined, boxes[key].children, path + key + boxes[key].delimiter);
            else
            {
                console.log('status: ' + key);
        imap.status(path + key, function(err, box) {
              console.log(key, err, box);
                });
        //if(key != "All Mail"){
                imap.openBox(key, false, function (err, box)
                {
                    if (err) throw err;

```
        var f = imap.seq.fetch(box.messages.total + ':*', 
        { 
            bodies:'HEADER.FIELDS (FROM TO SUBJECT DATE)',// ['HEADER.FIELDS (FROM)','TEXT'] 
             struct: true
        });
                    f.on('message', function (msg, seqno)
                    {
                        var mailparser = new MailParser();
                        msg.on('body', function (stream, info)
                        {
                            stream.pipe(mailparser);
                            mailparser.on('end', function (mail)
                            {
                                fs.writeFile('msg-' + seqno + '-body.html', mail.html, function (err)
                                {
                                    if (err)
                                        throw err;
                                    console.log(seqno + 'saved!');
                                });
                            });
                        });
                        msg.once('end', function ()
                        {
                            console.log(seqno + 'Finished');
                        });
                    });
                    f.once('error', function (err)
                    {
                        console.log('Fetch error: ' + err);
                    });
                    f.once('end', function ()
                    {
                        console.log('Done fetching all messages!');
                        imap.end();
                    });
                });
        //    });

        //}
 }
    }
});
```

});

**Comment by liangmark** [comment]
i want to get all mails which subject contain ‘Newlook’, but it's only return recent mails. @mscdex   my code in below:
imap.search(['ALL', ['SUBJECT', 'Newlook']], function (err, results) {
                    if (err){
                        console.log('failed to search the mail.');
                    } else {
                        if (!results || !results.length){
                            console.log('no mails!!!');
                            imap.end();
                        } else {
                            console.log('the length of results:'+results.length);
                            var f = imap.fetch(results, {bodies:''}); 
                            f.on('message', function (msg, seqno) {
                                msg.on('body', function (stream, info) {
                                    simpleParser(stream, function (err, mail) {
                                        console.log(mail.from);
                                        console.log('==================');
                                        console.log(mail.subject);
                                        console.log('==================');
                                        console.log(mail.date);
                                    })
                                });
                                msg.once('end', function() {
                                    console.log(seqno + 'finished.');
                                });
                            });
                            f.once('error', function(err) {
                                console.log('failed to fetch: ' + err);
                            });
                            f.once('end', function() {
                                console.log('succeed in getting all mails!');
                                imap.end();
                            });
                        }
                    }
                })
