### ISSUE TITLE
imap.end() causes [Error: read ECONNRESET]

### ISSUE THREAD

**Issue by coyle** [mscdex/node-imap#395]
I have the following function :

```javascript
ImapService.prototype.disconnect = function(callback) {
  callback = callback || function(){}
  this.imap.end();
  this.imap.once('end', function(){
    
    callback();
  });
}

```

When this is called, 9/10 times it throws the error:

{ [Error: read ECONNRESET]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  source: 'socket' }

I have an active connection and have been able to successfully pull messages from the IMAP server.

I understand I can capture error events and handle them. This should not be a solution though. I need to understand why this error is getting thrown and prevent it. I have read through the code and can not find any reasonable explanation.

Any insight into this issue?

**Comment by sergenikitin** [comment]
I have the same error: 
```
{ [Error: read ECONNRESET]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  source: 'socket' }
```
And with this error I do not know how to close connection and finish imap request.

**Comment by mscdex** [comment]
@sergenikitin The connection is closed if you are getting that message.

**Comment by mscdex** [comment]
As far as I know there isn't much this module can do about this since we are gracefully terminating the connection with the server by sending the `LOGOUT` and the server responds appropriately. If anything this would be a node bug.

**Comment by mpiivonen** [comment]
Hi,

I had similar issue and someone else had similar issue, which was caused by tls settings.
Try to change tls true to following

	this.imap = new Imap({
		user: username,
		password: password,
		host: host,
		port: port || 993,
		tls: {
        secureProtocol: "TLSv1_method"
    }

source: http://stackoverflow.com/a/17583844

**Comment by nmalzieu** [comment]
@mscdex @sergenikitin I had the same issue with Gmail IMAP, and @mpiivonen 's answer worked for me.

**Comment by Salketer** [comment]
I've had the same problem... I ended up doing this:

    // Silence all errors.
    this.imap.removeAllListeners("error");
    this.imap.on("error",()=>{});
    this.imap.end();

**Comment by satbirkira** [comment]
> 

genius
