### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by atorgfr** [mscdex/node-imap#417]
Hi,

I always got this error when i try to connect to my gmail account :

{ [Error: Invalid credentials lu2mb33951954wic] textCode: undefined, source: 'authentication' }

This account is in only on one step login.
And i can configure it with my Mail app  (Max OSX).

Is it because i'm using 10.22 of Node ?

Thx

**Comment by aravael** [comment]
answer from 2019 :-) @mscdex , was right. The problem is with `less secure access` option.
