### ISSUE TITLE
Connection fails against Gmail (and others?) with certain antivirus software (Windows 7)

### ISSUE THREAD

**Issue by sp00x** [mscdex/node-imap#420]
Windows 7: Trying the test script against Gmail while having Eset nod32 Antivirus 5 active makes the connection fail ('error' event is raised):

{ [Error: Timed out while connecting to server] source: 'timeout' }

Works FINE when I disable IMAP scanning under nod32's options.

I suspect it's doing some kind of MITM approach to scan email, but this works fine with Thunderbird, so I'm not sure what it is that node-imap is doing that makes this fail.

I'm not sure if this is something you want to address or investigate, but I'm leaving this issue here in case someone else runs into this and wastes time trying to understand why it's not working.

**Comment by mscdex** [comment]
When "security software" does things like this, there isn't anything this module can do about it unfortunately. Even if there was something that could be done, it would probably be vendor-specific which would be ugly/hacky.
