### ISSUE TITLE
Request for code review of a common use case

### ISSUE THREAD

**Issue by mercmobily** [mscdex/node-imap#422]
Hi,

First of all, thank you so much for mentoring me through my little journey towards nodejs' streams.
My use case is a common one, where I want to download a message's body (both HTML and TEXT) and have a list of attachments for later downloading.
I have to (humbly) admin that I am not a great fan of this code: https://github.com/mscdex/node-imap/issues/398#issuecomment-47406538 It's meant to be a "starting point", but I feel that it tries to do too much in one function, behaving very differently whether partID is set or not.

I would like to provide an alternative approach, and possibly give that out as examples. I am obviously offering this in the most humble way, and I only expect you to _consider_ it.

Here we go: here is a function that downloads a specific part of a message:

    function fetchMessagePart( imap, uid, partID, done ){

      if( ! partID ) return done( null, null );

      var hadErrInFetch, hadErrInMessage, hadErrInBody;
      var fullPart = { body: '', attributes: null, info: null }
      var f = imap.fetch(uid, { bodies: [ partID ] } );

      // QUESTION #1: Since I am only fetching one part, I assume I will
      // either get the signals (in order) 'message,end' or 'error,end', and never
      // 'message,error,end'. Am I right in my assumption?
      // If that is the case, I can get rid of `hadErrInFetch` since the 'message'
      // event will never actually get called if there was an error  

      // If there is an error fetching, note that it happened and
      // simply call the callback
      f.on('error', function( err) {
        hadErrInFetch = err;
        done( err );
      });

      f.on('message', function( m ) {
     
        if( hadErrInFetch) return;

        // If there is an error, note that it happened and
        // simply call the callback
        m.on( 'error', function( err ){
          hadErrInMessage = err;
          done( err );
        });

        // Get the attributes
        m.on( 'attributes', function( attributes ) {

          if( hadErrInMessage) return;

          fullPart.attributes = attributes;
        });
        

        // Get the body
        m.on('body', function( stream, info) {

          if( hadErrInMessage) return;

          // Assign the part info
          fullPart.info = info;

          stream.on('data', function( d ) {
            fullPart.body += d;
          });
          stream.on('end', function() {
            // QUESTION: Is not having anything here OK? Rationale:
            // No need to have anything here since the fetch's 'end' event
            // will be called after this one, and that's when we return the
            // body as string
          });

          // If there is an error, note that it happened and
          // simply call the callback
          stream.on( 'error', function( err ){
            hadErrInBody = err;
            done( err );
          })

        });
      });

      f.on('end', function() {
        // If hadErrIn**** is set, then the callback has already been called.
        if( hadErrInFetch || hadErrInBody || hadErrInMessage ){
          return;
        }

        done( null, fullPart );        

      });

    }

Please see the comments marked as "QUESTION" within the code!
The great thing about this code is that it's dead easy to understand, it follows simple patterns to check if previous errors happened, and it can be used "as is".

Here is the other function, that does exactly what I stated at the beginning: fetches a message with TEXT and HTML body as well as headers, AND a list of attachments which haven't been downloaded (yet):

    // This function will take `struct` as a parameter, and will
    // return an object where `text` and/or `html` are possibly
    // set based on its contents.
    function findText( struct, result ) {

      var result = result || { text: null, html: null };

      for( var i = 0, len = struct.length; i < len; i++ ) {

        // If it's an array, scan that recursively. Pass `result` to it,
        // so that it keeps on enriching the same object
        if( Array.isArray( struct[i] ) ) {
          findText( struct[i], result );

        // If it's a normal element, use it to try and enrich
        // result with `plain` or `html` (if available)
        } else {

          var s = struct[ i ];
          if( s.type.toLowerCase() === 'text' ){
            if( ! result.text && s.subtype.toLowerCase() === 'plain' ){
              result.text = s;
            }
           if( ! result.html && s.subtype.toLowerCase() === 'html' ){
              result.html = s;
            }         
          }
        }

        // Exit early if not all elements have been scanned yet, but result
        // is already complete.
        if( result.text && result.html ) return result;
      }

      return result;
    }

    function fetchMessageWithTextParts( imap, uid, fetchOptions, done ){

      // Unfinished, initial fullMessage object
      var fullMessage = { uid: null, text: '', html: '', headers: null, attachmentParts: [] };
      var hadErrInFetch, hadErrInBody, hadErrInMessage;
      var attributes, messageBody = '';

      // Just in case. Without this, this function cannot work.
      fetchOptions.struct = true;

      // Run the imap
      var f = imap.fetch(uid, fetchOptions );

      // If there was an error, note it and call the callback with err
      f.once('error', function( err) {
        hadErrInFetch = err;
        done( err );
      });

      // Not really using this for anything since the function will only ever
      // download one message
      f.once( 'end', function(){
      });

      f.once('message', function( msg, seqno) {

        // QUESTION: 
        // This should be useless, as node-imap's fetch() should never emit
        // 'error' and them 'message'. Right?
        if( hadErrInFetch ) return;

        var prefix = '(#' + seqno + ') ';

        // Set hadErrorInMessage in case of errors
        msg.once('error', function( err) {

          hadErrInMessage = true;
          done( err );
        });

        // Assign 'attributes'
        msg.once('attributes', function( _attributes ) {
          if( hadErrInMessage ) return;

          attributes = _attributes;
        });
        
        // Assign 'messageBody'
        msg.on( 'body', function(stream, info) {
          if( hadErrInMessage ) return;

          stream.on( 'error', function( err ){
            hadErrInBody = err;
            cb( err );
          });
          stream.on( 'data', function( d ){
            if( hadErrInBody ) return;
            messageBody += d;
          });

          stream.on( 'end', function(){
            if( hadErrInBody ) return;

            // Not doing anything with this it, using the 'end' signal of the message
            // to continue the flow
          });
        });
        
        msg.once('end', function() {
          if( hadErrInMessage || hadErrInBody ) return;

          // Setting fullMessage
          fullMessage.headers = Imap.parseHeader( messageBody );
          fullMessage.attachmentParts = findAttachments( attributes.struct );
          fullMessage.uid = attributes.uid;

          var textParts = findText( attributes.struct );

          // At this point, we are missing "text" and "html" in fullMessage.
          // It should be easy to get it

          var partIDs = [];
          if( textParts.html ) partIDs.push( { type: 'html', partID: textParts.html.partID } );
          if( textParts.text ) partIDs.push( { type: 'text', partID: textParts.text.partID } );

          async.eachSeries(
            partIDs,
            function( partID, cb ){

              fetchMessagePart( imap, fullMessage.uid, partID.partID, function( err, part ){
                if( err ) return cb( err );

                fullMessage[ partID.type ] = part.body;
                cb( null );
              })
            },
            function( err ){
              if( err ) return done( err );

              done( null, fullMessage );
            }
          );

        })
      })  
    }

Please note that I want to fix some naming, especially around "text", "body" etc.
Anyhow, this way the function is dead easy to use. Note that I always fetch one message at a time, using async to go through them. This makes the app's flow a lot easier to manage.

          var imap = new Imap({
            user: config.imapLogin,
            password: config.imapPassword,
            host: config.imapServer,
            port: config.imapPort,
            tls: true
          });

          imap.once('error', function( err ) {
            console.log("LOG THE PROBLEM", err, config );
          });

          imap.once('end', function() {
            console.log('Connection ended');
          });

          imap.once('ready', function() {

            // Open INBOX in the imap server
            imap.openBox('INBOX', true, function( err, mailbox ){

              if (err){

                logLine( stores, config, null, 1, "Could not open inbox: " + config.imapHost + ":" + config.imapPort );
                // EMIT error with config
                return;    
              } 

              imap.search([ 'UNSEEN' ], function(err, uids) {
                if( err ){
                  logLine( stores, config, null, 1, "Could not open inbox: " + config.imapHost + ":" + config.imapPort )
                  return;
                }

                async.eachSeries(
                  uids,
                  function( uid, cb ){

                    fetchMessageWithTextParts( imap, uid, { bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE )', struct: true }, function( err, fullMessage){

                      if( err ){
                        console.log("fetchMessageWithTextParts returned with error: ", err );
                        // LOG THE ERROR
                      }
                      console.log("FULL MESSAGE IN THE END: ", fullMessage );
                      cb( null );

                    });

                  },
                  function( err ){

                    // Err cannot be set here as the iterating function will never call it
                    // If a message fails, the loop should continue
                    console.log("END OF PROCESSING MESSAGES!" );
                    imap.end();

                    // 

                  }
                );

              });
            });
          });
          imap.connect();

**Comment by mscdex** [comment]
The problem with blindly fetching multiple messages with specific body part numbers is that not all messages are necessarily structured the same. If you'd want to fetch multiple messages with specific body parts, you'd need to fetch the metadata first to find out their structures and if they support those body parts then fetch them.

**Comment by mercmobily** [comment]
OK. Now, "question 4" aside, I think the use case "Fetching all parts of a specific message except the attachment" is quite common.  My question then is: do you want me to improve the code further (that is, getting rid of `logLine` for example and replacing it with `console.log`, generally making sure that it works "out of the box", improve comments, etc) and use it as a possible use-case as an example? If not, all good. I just think that with a little bit of work (which I am willing go do) this code would be very useful to a lot of people.

**Comment by mscdex** [comment]
I think this is going to be a fairly large chunk of code, so maybe we can start an `examples/` subdirectory to contain larger examples?

**Comment by mercmobily** [comment]
I think that would be an _excellent_ idea. If you agree, I will be totally 100% happy to improve my code (see improvements above) so that we can add it to the examples (specifically, mine could be "Fetch a message leaving attachments on the server"). If you are even "very likely" to accept it, I will submit the improved code very soon. I think giving "live examples" is a great idea, as it took me a while to get my head around how node-imap actually works.

**Comment by mscdex** [comment]
Go ahead and submit a PR for it when you get a chance :-)
