### ISSUE TITLE
No timeout for openBox

### ISSUE THREAD

**Issue by jamestooks** [mscdex/node-imap#425]
We were having an issue where occasionally opening a box would cause the system to hang.  We fixed this by implementing a timeout around this code that forces it to close the current opened box and then try again.

Might be useful to implement a timeout in node-imap that works in the same sort of way as connection timeouts.

**Comment by mscdex** [comment]
As previously mentioned, a pull request to add a timeout like this in a sane way for all requests would be welcome.
