### ISSUE TITLE
Timed out while authenticating with server

### ISSUE THREAD

**Issue by celalo** [mscdex/node-imap#432]
Hello,

Very Rarely, I come across the error "Timed out while authenticating with server". Is there a way to handle this error gracefully? Connection event `imap.once('error', function(err) {})` does not help. I am on node 0.8.27 with node-imap 0.8.14. Error details are below.

```
Error: Timed out while authenticating with server
 at Object._onTimeout (/app/node_modules/imap/lib/Connection.js:137:17)
 at Timer.list.ontimeout (timers.js:101:19)
```

**Comment by GeorgS** [comment]
I am getting the same uncaught exception.

**Comment by mscdex** [comment]
@GeorgS Do you have an `error` event handler set up on the imap connection instance?

**Comment by GeorgS** [comment]
I sometimes get `Uncaught Exception: Imap not authenticated`.
When I reconnect with 
```javascript
client.on('ready', function() {
        if (_this.client.state != 'authenticated') {
            _this.client.connect();
        }
});
``` 
I get `...imap/lib/Connection.js:1484 Uncaught TypeError: Cannot read property 'bodyEmitter' of undefined`.

@mscdex Yes, I handle errors with 
```javascript
client.on('error', function(err) {
        console.error(err);
});
```

**Comment by celalo** [comment]
Changing `imap.once('error', ...)` to `imap.on('error', ...)` solves the `uncaughtException`, that was my bad. Now the error is handled gracefully.

Though, `Timed out while authenticating with server` error still persists. I see much more often recently. increasing `authTimeout` (even up to 30s) does not help.

```
[connection] Connected to host
<= '* OK Gimap ready for requests from <redacted this part> n18mb3700662qhc'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN'
<= 'A0 OK Thats all she wrote! n18mb3700662qhc'
=> 'A1 AUTHENTICATE XOAUTH2 <redacted this part>'
```
Then authentication attempts stalls at this point. Starting all over again with a fresh connection does not help.

**Comment by mscdex** [comment]
@celalo Do you see more output after the `AUTHENTICATE XOAUTH2` if you apply [this patch](https://github.com/mscdex/node-imap/pull/454.patch)?

**Comment by celalo** [comment]
@mscdex no, it is the same.

**Comment by mscdex** [comment]
If that's the case, it seems like there is some problem with Google's server or the connection between. After sending that command, it's waiting for a response of some kind, successful or not. I'm not sure what else this module can do about that.

**Comment by celalo** [comment]
That's what I suspected. The error occurs somewhat intermittently. In the same instance, few accounts end up with this authentication error although large majority works alright. Changing the instance, using a different IP address to connect does not help. Oddly, the issue does not persist. After a while, it starts working again for that particular accounts. Nevertheless, it is very likely the problem recurs again after an uncertain period of time.

**Comment by onelesd** [comment]
I am occasionally getting the same uncaughtException as @GeorgS when connecting to a yahoo.com account.

`...imap/lib/Connection.js:1484 Uncaught TypeError: Cannot read property 'bodyEmitter' of undefined`.

**Comment by kaldimar** [comment]
I've been using the library for some days, and until today we got this error, but we're getting it repeatedly:

```
/mnt/task/node_modules/imap/lib/Connection.js:1484
  if (req.bodyEmitter) {
         ^
TypeError: Cannot read property 'bodyEmitter' of undefined
    at Connection._resTagged (/mnt/task/node_modules/imap/lib/Connection.js:1484:10)
    at Parser.<anonymous> (/mnt/task/node_modules/imap/lib/Connection.js:177:10)
    at Parser.emit (events.js:95:17)
    at Parser._resTagged (/mnt/task/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/mnt/task/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/mnt/task/node_modules/imap/lib/Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (/mnt/task/node_modules/imap/lib/Parser.js:53:12)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at _stream_readable.js:403:7
```

I feel like hijacking this issue thread, which was opened for timeout issues, however a web search brought me here because @GeorgS and @onelesd quoted the same error than the one I'm having. @mscdex if this should have its own thread feel free to move our messages or let us know to open a new one.

**Comment by mscdex** [comment]
@kaldimar Can you set `debug: console.log` or similar and post the output leading up to that error (including the initial FETCH sent to the server)?

**Comment by kaldimar** [comment]
I haven't had the issue again in the last ~24 hours however if it happens again I will post back with the debug info. Thanks.

**Comment by Yubin** [comment]
hi @mscdex 

Any update on this, i ran into this several times, especially there is a error when connect. 
Here is the debug output:

[connection] Connected to host
<= '* OK [CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE ID UIDPLUS AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE AUTH=LOGIN NAMESPACE CHILDREN ID UIDPLUS'
<= 'A0 OK CAPABILITY Completed'
=> 'A1 LOGIN "369163493@qq.com" "xxxxx"'
<= 'A1 NO [ALERT] Login failure. Incrrect passowd or your account is not enabled for IMAP. [��¼ʧ��, ������������IMAP����δ��ͨ]'
<= 'A1 NO ��¼ʧ��[������������IMAP����δ��ͨ]'
./node_modules/imap/lib/Connection.js:1502
  if (req.bodyEmitter) {
         ^
TypeError: Cannot read property 'bodyEmitter' of undefined
    at Connection._resTagged (./node_modules/imap/lib/Connection.js:1502:10)
    at Parser.<anonymous> (./node_modules/imap/lib/Connection.js:193:10)
    at Parser.emit (events.js:107:17)
    at Parser._resTagged (./node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (./node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (./node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (./node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)

**Comment by mscdex** [comment]
@Yubin Should be fixed with 808565e97913.

**Comment by Yubin** [comment]
@mscdex  awesome, it works for me now! Thanks

**Comment by Maples7** [comment]
I got these 3 errors at the same time in most cases:
```
Timed out while authenticating with server          
This socket is closed        
write EPIPE    
```
I think maybe that's a bug of node, see [EPIPE errors thrown when piping to a closed stream #947](https://github.com/nodejs/node/issues/947)

**Comment by chandnisoni** [comment]
I am getting same error: 
`Error: Timed out while authenticating with server`
 `at Object._onTimeout (/app/node_modules/imap/lib/Connection.js:137:17)`
` at Timer.list.ontimeout (timers.js:101:19)`

**Comment by mscdex** [comment]
@nareshgithub123 I'm not sure what you mean. You can configure the connection and authentication timeouts in the connection config.

**Comment by gsaravanakumar932** [comment]
imap version: imap@0.8.19

@mscdex,  I am getting the below issue, 
It is working fine with **LocalHost**, but it is not working in server. My config as below,
What should i do, to make it work ?

```
{
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  source: 'socket',
  level: 'error'
}
{ source: 'timeout', level: 'error' }
{ source: 'timeout', level: 'error' }
{
  message: 'Error: Timed out while connecting to server\n' +
    '    at Timeout._onTimeout (/apps/smartexpense/mailread/node_modules/imap/lib/Connection.js:280:15)\n' +
    '    at listOnTimeout (internal/timers.js:551:17)\n' +
    '    at processTimers (internal/timers.js:494:7)',
  level: 'error'
}

{ message: 'Process will exit with code: 0', level: 'error' }
{ source: 'timeout', level: 'error' }

```
**my config:** 
export const imapConfig = {
  imap: {
        user: 'my@email',
        password: 'password',
        host: 'outlook.office365.com',
        port: 993,
        tls: true,
        authTimeout: 10000,
        connTimeout: 30000,
        keepalive: true,
        tlsOptions: {
          rejectUnauthorized: false
        }
};
