### ISSUE TITLE
cyrillic encoding

### ISSUE THREAD

**Issue by VladislavAnkudinov** [mscdex/node-imap#434]
I have troubles with cyrillic encoding KOI8-r used in widely spread Yandex mail. 

this is a snippet of email that I got on my server (right from the file in postfix directories where emails stored)

/**********************************************
Message-Id: 3490181413973957@web20o.yandex.ru
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Wed, 22 Oct 2014 14:32:37 +0400
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=koi8-r

Привет, Долли!
Отлично выглядишь
**********************************************/

And this is what i've got with node-imap

/**********************************************
Message-Id: 3490181413973957@web20o.yandex.ru
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Wed, 22 Oct 2014 14:32:37 +0400
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=koi8-r

������, �����!
������� ���������
**********************************************/

I tryed to play with this unrecognised charachters with s.charCodeAt but it returns indistinguishable values, such as 65533.

Is there any workaround here?
can I get somehow that Buffer from which node-imap makes the string?
Thanks alot

**Comment by XIIIcool** [comment]
help, I have the same problem, how else to solve?
