### ISSUE TITLE
Stopping long running fetchs

### ISSUE THREAD

**Issue by khalilTN** [mscdex/node-imap#447]
Is there a way to stop long running fetchs ? i'm implementing a solution to handle mails, and i have to stop long running fetches when an error handling the mail occures (Logic error, not a node-imap error). A fetch returning ~7000 mails costs me ~82 seconds of lost time if an error occures when handling my first mail.

**Comment by mscdex** [comment]
No, there is no way to stop long running fetches because there is no 'abort request' mechanism in IMAP. About the only way to do what you want is to just abruptly close the whole socket, which you should be able to do with `imap.destroy();`.

**Comment by khalilTN** [comment]
Thank you !
