### ISSUE TITLE
Moving thread out of inbox

### ISSUE THREAD

**Issue by ewein** [mscdex/node-imap#449]
I am trying to move a thread out of the inbox and into a different folder. When I do this the new label is applied to the thread and the thread shows up in the folder but it also stays in the inbox. 

```
imap.move(msgID, 'folder name', function (err) {
    if (err) {
        imap.addBox('folder name', function (err) {
           if (err) return callback(err);

           imap.move(msgID, 'folder name', function (err) {
                if (err) return callback(err);

                imap.end();
                callback();
            });
        });
    } else {
        imap.end();
        callback();
    }
});
```

**Comment by mscdex** [comment]
[According to google](https://support.google.com/mail/answer/78755), deleting the message in the inbox will archive it. Deleting a message in `[Gmail]/Spam` or `[Gmail]/Trash` is the only way to permanently delete a message with gmail.
