### ISSUE TITLE
unable to do this

### ISSUE THREAD

**Issue by techsin** [mscdex/node-imap#451]
I wanted to read emails from my gmail. From recent to backward. And then using cmd i wanted to do this node app.js > file.html. 

However, some messages don't get retrieved, giving range in minus is not possible (how else do i tell it to start from recent), and everything is coming randomly.

**Comment by mscdex** [comment]
gmail's imap server does not support the SORT extension, so you basically would have to download all emails first and *then* sort them manually (by date or however).
