### ISSUE TITLE
Example Code fails to execute:

### ISSUE THREAD

**Issue by steowens** [mscdex/node-imap#453]
The error returned is { [Error: SELF_SIGNED_CERT_IN_CHAIN] source: 'socket' }

What do we need to do to fix this?

**Comment by mscdex** [comment]
You can pass a `tlsOptions` object that contains any options you want to pass on to [`tls.connect()`](http://nodejs.org/api/tls.html#tls_tls_connect_port_host_options_callback). So you will probably want to set `ca` to your self-signed cert's CA. Or if you want to just blindly ignore the error, you can set the `rejectUnauthorized: false` to your `tlsOptions`.

**Comment by steowens** [comment]
Great, I was sure that there was some simple fix and the rejectUnauthorized seems like the approach I want to use, for development that is.

**Comment by viyancs** [comment]
hi how to fix this ? what should code i add in the example code for fix this ?
