### ISSUE TITLE
suggestion: pass error to the callback instead of throw

### ISSUE THREAD

**Issue by okv** [mscdex/node-imap#455]
It would be great if imap will pass error as first argument to the callback (like other libraries do) instead of throw it.

**Comment by mscdex** [comment]
Errors are supposed to be passed to callbacks (where possible). Can you show the code you're using and where/when the error is "thrown?" What error are you seeing exactly?

**Comment by okv** [comment]
```
Error: connect ETIMEDOUT
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete] (net.js:761:19)
```

periodically kills my nodejs process

also sometimes 

```
Error: Timed out while connecting to server
    at Object._onTimeout (node_modules/imap/lib/Connection.js:243:15)
    at Timer.list.ontimeout (timers.js:101:19)
```

occurs

**Comment by okv** [comment]
I can only handle this error within process `uncaughtException` handler but this is too bad because i don't know what action leads to this error

**Comment by okv** [comment]
i'm using imap 0.8.10

**Comment by okv** [comment]
i've just tried wrong mail parameters with imap 0.8.14 and i've got

```
Error: connect ECONNREFUSED
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete] (net.js:761:19)
```

also catched at process `uncaughtException`

**Comment by okv** [comment]
It behaves like that if you don't have any `error` handler on `imap`.
Now it's ok. It was my misunderstanding of library interface (which combines events and callbacks), sorry for that. Closing the issue ...
