### ISSUE TITLE
How to check a opened connection?

### ISSUE THREAD

**Issue by sergenikitin** [mscdex/node-imap#457]
Hello,

I use node-imap with a `imap.on('mail')` event, open one connection when app is loaded and wait new messages.

But I'm not sure for stable connection. Is there any way to check the opened connection for a live status?

I tried check `imap.state` when I disconnected my machine from internet, but it allways returned `authenticated`.

I'm looking for a way to catch any network problems and reconnect node-imap.

Thanks!

**Comment by icemilo** [comment]
I too have a same question.. Thanks for opening an issue.

**Comment by polomoshnov** [comment]
Same here. Seems to be similar to https://github.com/mscdex/node-imap/issues/228

**Comment by mscdex** [comment]
Keepalive is enabled by default, however you may try either adjusting the `idleInterval` for the keepalive option or force using NOOPs for keepalive via `keepalive: { forceNoop: true }`. Either way, the dead connection should be detected at some point, it just may be longer than expected depending on your `keepalive` setting (or its defaults).
