### ISSUE TITLE
Problem with email date search

### ISSUE THREAD

**Issue by nicu** [mscdex/node-imap#459]
I'll start by saying that I'm almost sure I'm not using the API properly.

In one of my GMail accounts, I have an unread email from `March 22, 2015`.
I'm trying to read its contents, but with no luck. The code is:

```js
var lastDate = new Date(2015, 2, 20); // 2 days before the email's date
imap.search([  ['SINCE', lastDate] ], function(err, results) {
	if (err) throw err;

	var f = imap.seq.fetch(results, {
		bodies: 'TEXT'
	});

	f.on('message', function(msg, seqno) {
		// this never fires
	});
	[...]
});
```
I also tried with string representation of the date, with identical results.
If I set the date long enough in the past, I can see this email in the list of few emails that belong to the time interval.

Any ideas?

In the debug log, I don't see any request like the one below, which is extracted from a date filter from January until March.
```
'* 555 FETCH (X-GM-THRID XXXXXXXXXXXXXXXXX X-GM-MSGID XXXXXXXXXXXXXXXXX X-GM-LABELS ("\\\\Important" "\\\\Sent") UID 562 MODSEQ (XXXXX) INTERNALDATE "31-Jan-2015 20:00:22 +0000" FLAGS (\\Seen) BODY[TEXT] {14}'
```

Debug info:
```
[connection] Connected to host
<= '* OK Gimap ready for requests from <IP> <HASH>'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN'
<= 'A0 OK Thats all she wrote! <HASH>'
=> 'A1 LOGIN "my_user@gmail.com" "password"'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT'
<= 'A1 OK my_user@gmail.com authenticated (Success)'
=> 'A2 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A2 OK Success'
=> 'A3 LIST "" ""'
<= '* LIST (\\Noselect) "/" "/"'
<= 'A3 OK Success'
=> 'A4 EXAMINE "<NAME_OF_INBOX>" (CONDSTORE)'
<= '* FLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $Phishing $NotJunk NotJunk $NotPhishing)'
<= '* OK [PERMANENTFLAGS ()] Flags permitted.'
<= '* OK [UIDVALIDITY 12] UIDs valid.'
<= '* 636 EXISTS'
<= '* 0 RECENT'
<= '* OK [UIDNEXT 660] Predicted next UID.'
<= '* OK [HIGHESTMODSEQ 111910]'
<= 'A4 OK [READ-ONLY] <NAME_OF_INBOX> selected. (Success)'
=> 'A5 UID SEARCH SINCE 20-Mar-2015'
<= '* SEARCH 659'
<= 'A5 OK SEARCH completed (Success)'
=> 'A6 FETCH 659 (X-GM-THRID X-GM-MSGID X-GM-LABELS MODSEQ UID FLAGS INTERNALDATE BODY.PEEK[TEXT])'
<= 'A6 OK Success'
=> 'IDLE IDLE'
<= '+ idling'
=> DONE
<= 'IDLE OK IDLE terminated (Success)'
=> 'A7 LOGOUT'
<= '* BYE LOGOUT Requested'
<= 'A7 OK 73 good day (Success)'
[connection] Ended
[connection] Closed
```

Thank you

**Comment by mscdex** [comment]
I'm a little confused here. What are the dates of the messages you're expecting to see? What are the actual `SINCE` dates that you're using where it works *and* where it doesn't work for those messages? Are the messages you're having trouble seeing actually in the Inbox or are they archived under a different label for example?

**Comment by nicu** [comment]
Sorry if I wasn't clear and thank you for the reply.

The date of the message is: `Date: Sun, 22 Mar 2015 13:29:07 +0200`.
The `SINCE` values are a bit confusing to me too. The 9th of March works, and from 10th on, I get no results, even though the date is 22nd of March.

This works
```js
var lastDate = new Date(2015, 2, 9);
```

but this doesn't
```js
var lastDate = new Date(2015, 2, 10);
```
The messages are **not** in the Inbox, but under a different label.
I open it using:
```js
imap.openBox('Changes', true, cb);
```

A sample of the message I get when it works, with some stuff replaced:
```
Return-Path: <my_email@gmail.com>
Received: from XXXXX ([XXX.XXX.XXX.XXX])
        by mx.google.com with ESMTPSA id SOME.LETTERS.AND.NUMBERS
        for <my_email@gmail.com>
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Sun, 22 Mar 2015 04:29:10 -0700 (PDT)
Message-ID: <MESSAGE.ID@mx.google.com>
From: my_email@gmail.com
X-Google-Original-From: original@from
Received: by SENDER (sSMTP sendmail emulation); Sun, 22 Mar 2015 13:29:07 +0200
Date: Sun, 22 Mar 2015 13:29:07 +0200
Subject: Changes
To: <my_email@gmail.com>
X-Mailer: mail (GNU Mailutils 2.99.97)

BODY OF EMAIL
```

**Comment by mscdex** [comment]
In the previous debug output you posted:

```
=> 'A5 UID SEARCH SINCE 20-Mar-2015'
<= '* SEARCH 659'
<= 'A5 OK SEARCH completed (Success)'
```

That shows you used a date of March 20, and it found 1 message with a UID of 659. However you then try to fetch a message with a *sequence number* of 659 instead of the message with a *UID* of 659. Since you searched for UIDs, you need to use `imap.fetch(uid, ...);` instead of `imap.seq.fetch(uid, ...)`

**Comment by nicu** [comment]
That was the problem. How embarrassing.

Thank you for the help.

**Comment by mscdex** [comment]
No problem
