### ISSUE TITLE
outlook calendar request attachments files(invite.ics) file not downloading 

### ISSUE THREAD

**Issue by mohit125** [mscdex/node-imap#460]
i tried using your module for reading mails and downloading attachments , worked great , just has this one issue where calendar request (invite.ics) file from microsoft outlook does'nt get downloaded , it works for all other mail clients like thunderbird ...etc , while other attachments from outlook like media files etc gets downloaded fine , can't really get why this is happening any idea 
also i did got little info the invite.ics file from outlook has transfer encoding 7 bit while that of thunderbird is 8 bit and normal google request is base64  has this anything to with this download issue

**Comment by mscdex** [comment]
To start, I need to see code and output after setting `debug: console.log` in your connection config.

**Comment by mohit125** [comment]
@mscdex  well i got it , actully , there was is property called content-disposition in mail that should contain attachment as a value ,if there is a attachment  with the mail , in this case when you send a calendar request from outlook then , outlook just send a body text/plain to receiver , but mail client i.e gmail just interpret the calendar request as a attachment file ,you will get all this information in show original option of mail
