### ISSUE TITLE
MailParser + node-imap

### ISSUE THREAD

**Issue by George02** [mscdex/node-imap#461]
I'm trying to parse email stream with MailParser. Why this would not work ? If I fetch only FROM TO SUBJECT and DATE it's working but if I want the TEXT to be fetched too the headers are set bad.

    var f = imap.seq.fetch('4:4', {
			bodies: ['HEADER.FIELDS (FROM TO SUBJECT DATE)','TEXT'],
			struct: true
    });
    f.on('message', function(msg, seqno) {
			msg.on('body', function(stream, info) {
				var msgText = '';
				var msgHeaders = '';
				stream.on('data', function(chunk) {
					if(info.which === 'TEXT'){
						msgText += chunk.toString('utf8');
					}else if(info.which === 'HEADER.FIELDS (FROM TO SUBJECT DATE)'){
						msgHeaders += chunk.toString('utf8');
					}
				});
				stream.once('end', function() {
					if(info.which === 'TEXT'){
						mailparser.write(msgText);
					}else{
						mailparser.write(msgHeaders);
					}
				});
			});
			msg.once('attributes', function(attrs) {
				mailparser.write(attrs);
			});
			msg.once('end', function() {
				console.log('Message Finished');
				mailparser.end();
			});
		});

**Comment by mscdex** [comment]
What do you mean "are set bad?" If you're wanting to parse the whole message with MailParser, then just do something like this:

```javascript
var f = imap.seq.fetch('4:4', {
  bodies: [''],
  struct: true
});
f.on('message', function(msg, seqno) {
  msg.on('body', function(stream, info) {
    var mp = new MailParser();
    mailparser.on('end', function(obj) {
      console.log('Message fully parsed!');
      console.log('Subject:', obj.subject);
    });
    stream.pipe(mp);
  }).once('attributes', function(attrs) {
    // attrs here is an *object* containing email metadata
  });
}).on('end', function() {
  console.log('Done fetching all messages');
});
```

**Comment by George02** [comment]
Oh, thank you ! I was thinking that I have to parse headers and text at a time.
