### ISSUE TITLE
keepAlive not working as expected ?

### ISSUE THREAD

**Issue by George02** [mscdex/node-imap#462]
My understanding is that email providers has something called IDLE when dealing with imap. And to be able to use this feature I need to set keepAlive to true. My code looks something like this and my expectation is that after 3600 seconds = 1 minute the mails to be fetched again. This doesn't work. I run nodejs, I send a mail to `myemail@gmail.com` wait 60 seconds and nothing happen. What I'm doing wrong ?

    var Imap = require('imap');
    var MailParser = require("mailparser").MailParser;

    var DatabaseClient = require('../../controllers/DatabaseClient');

    var imap = new Imap({
            user: 'myemail@gmail.com',
            password: 'mypassword',
            host: 'imap.gmail.com',
            port: 993,
            tls: true,
            keepalive: {
                interval: 3600,
                idleInterval: 3600,
                forceNoop: true
            }
    });

    registerEvents(imap);

    imap.connect();

    function registerEvents(imap){
        imap.once('ready', function() {

        console.log("MAIL SERVICE LISTENING");

        imap.openBox('INBOX', false, function(err, box) {
            if (err){
                serviceState.setStatusCode(404);
                serviceState.setStatusMessage("Error oppening inbox");
                console.log(err);
            }else{
                fetchMessages(imap);
            }
        });
    });

    imap.once('error', function(err) { //handle it });
    imap.once('end', function() { //handle it });
    }

    function fetchMessages(imap){
        var query = imap.search(["UNSEEN"], function(error, results){
            if(error) { console.log("ERROR imap.search"); throw err;}

            var fetchQuery = imap.seq.fetch(results, { bodies: [''], markSeen: true, struct: true });

            fetchQuery.on('message', function(msg, seqno) {
                parseMessage(msg, seqno);
                console.log('New mail received.');
            });

            fetchQuery.once('error', function(err) {
                console.log('Fetch error: ' + err);
            });

            fetchQuery.on('end', function() {
                console.log('Done fetching all messages');
            });

    });
    }

    function parseMessage(msg, seqno){
        //parseMessage with MailParser
    }

**Comment by George02** [comment]
Another problem with my code is that there are no new message when I run nodejs I get this error: `etc/node_modules/imap/lib/Connection.js:760
    throw new Error('Nothing to fetch');
` and application terminates

**Comment by mscdex** [comment]
Since you're using `imap.search()` you should use `imap.fetch()`. The `seq` namespace is for dealing with sequence numbers instead of UIDs. Also you can check `results.length > 0` before executing `fetch()` if you want to avoid the "Nothing to fetch" error.

For detecting new mail, you should listen for the `mail` event. Your current code is not listening for this or otherwise calling `fetchMessages()` after you open the inbox.

**Comment by mscdex** [comment]
Additionally, the `keepalive` `interval` and `idleInterval` are in **milliseconds** *not* seconds.

**Comment by George02** [comment]
I'm calling `fetchMessages()` after I open the inbox, aren't I ?

**Comment by mscdex** [comment]
What I meant is that it's only called *once*.

**Comment by George02** [comment]
Thanks ! I solved it.

    imap.on('mail', function(numNewMsgs){
        console.log(numNewMsgs + " messages has arrived");
        fetchMessages(imap);
    });
