### ISSUE TITLE
imap.search  'ALL' not work

### ISSUE THREAD

**Issue by Alexnder** [mscdex/node-imap#465]
Example is wrong to use with 'ALL' param:
`imap.search(['ALL'], function(err, results) {`
Need to use:
`imap.seq.search(['ALL'], function(err, results) {`

**Comment by mscdex** [comment]
Can you explain why you think it is wrong? It works fine for me.

**Comment by Alexnder** [comment]
`imap.search(['ALL'], ...` return only the last message
`imap.seq.search(['ALL'], ...` return really all messages

**Comment by mscdex** [comment]
I'm not seeing that behavior at least on gmail. Both methods return the same number of messages for the inbox or other labels/mailboxes.

Are you using a different provider?

**Comment by Alexnder** [comment]
Yandex. Try this:
```
var imap = new Imap({
  user: "asdfasdfa.asdfas@yandex.ru",
  password: "asdfasdfaasdfasdfa",
  host: "imap.yandex.ru",
  port: 993,
  tls: true
});
```

**Comment by mscdex** [comment]
It works fine for me there too. Both methods return 3 messages.

**Comment by Alexnder** [comment]
Oh. It not worked... But we delete some email with personal information to prepare it for you. And at now it works fine. Ok. Another time. Thanx for attention.
