### ISSUE TITLE
imap.seq.fetch on('message') event is not triggered

### ISSUE THREAD

**Issue by George02** [mscdex/node-imap#468]
It is strange that the callback from fetch.on('end') is triggered but the callback from on('message') is not. I inspected my app with node-inspector and the message event is never triggered. In console I can see "Done fetching message" but no "New mail received". What I'm doing wrong ?

    function fetchMessages() {
        var query = imap.search(["UNSEEN"], function(error, results) {
            if (error) {
                console.log("ERROR imap.search");
                throw err;
            }

            lastFetchDate = new Date();

        if (results.length === 0) {
            console.log("No new messages");
            return;
        }
        var fetchQuery = imap.seq.fetch(results, {
            bodies: [''],
            markSeen: true,
            struct: true
        });

        fetchQuery.on('message', function(msg, seqno) {
            console.log('New mail received.');
            parseMessage(msg, seqno);
        });

        fetchQuery.once('error', function(err) {
            console.log('Fetch error: ' + err);
        });

        fetchQuery.on('end', function() {
            console.log('Done fetching message');
        });
    });
}

**Comment by mscdex** [comment]
Change `imap.seq.fetch` to `imap.fetch`.

**Comment by George02** [comment]
That was the problem. Can you explain what is the difference between those two ? `imap.seq.fetch` and `imap.fetch`
