### ISSUE TITLE
Delete email messages

### ISSUE THREAD

**Issue by AndreLigeiro** [mscdex/node-imap#47]
Hi,

How can I delete an email?
What I'm doing wrong?
Thks.

fetch = imap.fetch(req.params.id, {request: {headers:true, body:false } });

```
            fetch.on('message', function(msg)
            {
                msg.on('end', function() {
                    console.log("Flags: " + msg.flags);
                    msg.flags.push("\\Deleted");
                    console.log("Flags: " + msg.flags);
                });         
            });

            fetch.on('end', function()
            {
                imap.logout(cb);
                imap.closeBox(function(err) {
                if (err)
                    console.log(err);});
```

}

**Comment by aaronbriel** [comment]
@AndreLigeiro  Would it be possible to show how you initialized 'req' here?  I'm trying to achieve something similar but I'm unsure of what object would have the params.id.  I do a call like 'f.on('message', function(msg, seqno) {' but msg doesn't seem to have it.  I'm trying to build off of the example listed in https://github.com/mscdex/node-imap

Thanks!!
