### ISSUE TITLE
How to create a message in a folder

### ISSUE THREAD

**Issue by dgil** [mscdex/node-imap#474]
Hi,

I would like to create a message in one folder, e.g. in the `Sent Mail` in Gmail, but without actually sending the email through SMTP, rather adding the message created from scratch. Is that possible? Can anybody help me?

Many thanks

**Comment by mscdex** [comment]
You can use the `append()` method, but it requires that you already have a (properly formatted) string version of the entire email (headers and body).

**Comment by dgil** [comment]
Hi @mscdex, thanks for your quick response. 

Is there any way to create the string formatted version by appending it to the IMAP folder using your library? I've searched in the documentation and the closed issues, but unfortunately I haven't found anything.

Thank you again.

**Comment by mscdex** [comment]
No, the ability to create such strings isn't something provided by this library.

There are modules on npm however that do generate raw email messages for you, such as [`mailcomposer`](https://github.com/andris9/mailcomposer). For `mailcomposer` in particular, after you have finished creating your message, you will want to use its [`buildMessage()`](https://github.com/andris9/mailcomposer#compile-the-message-in-one-go) method to output a string version of the message. That string is what you'd pass to `append()`.

**Comment by dgil** [comment]
I've followed your instructions and it has been very easy to do.

Many thanks @mscdex!

**Comment by puppeteer512** [comment]
@mscdex
I have the same problem and still don't resolve, please help!
Here is my code:
`var msgData = mailcomposer({
  "from": from,
  "to": to,
  "cc": cc,
  "bcc": bcc,
  "replyTo": replyTo,
  "subject": subject,
  "text": text,
  "html": html,
  "attachments": attachments
});
var string = "";
msgData.build(function(err, message) {
  string = message;
});`
