### ISSUE TITLE
Message body stream freezes mid-way for some emails

### ISSUE THREAD

**Issue by zenflow** [mscdex/node-imap#476]
```js
message.on('body', function(body_stream, body_info) {
    process.stdout.write("message body:\n");
    body_stream.pipe(process.stdout);
    body_stream.once('end', function(){
        process.stdout.write("\nDone!\n")
    });
}
```
yeilds
```
message body:
This will not compl
```

I'm not sure how I could give you what you would need to reproduce this. I could post the whole test script including email credentials, and then just change my password after. Before I do, (a) is there anything you can think of off the bat that might be causing this? (b) would you use this to investigate and possibly fix the bug?

**Comment by mscdex** [comment]
Do you get the full message if you do:

```javascript
message.on('body', function(body_stream, body_info) {
    process.stdout.write("message body:\n");
    body_stream.on('data', function(data) {
      process.stdout.write(data);
    });
    body_stream.once('end', function(){
        process.stdout.write("\nDone!\n")
    });
}
```
?

If you still don't get the full message, how large is the email body? Is it possible you could send the entire raw email as an attachment (privately or otherwise)?

**Comment by zenflow** [comment]
OK. My bad. I created an infinite loop in the code consuming the stream (its been a while!), so at some point i would stop getting feedback in the console. I incorrectly concluded that the stream was the problem. Sorry about that. Thanks!
