### ISSUE TITLE
move not return new uids

### ISSUE THREAD

**Issue by ehsanagh** [mscdex/node-imap#484]
hello,
i'm using node-imap for creating my imap client section on my web application,
i have an issue with move function.
when i use this function it moves email on the remote server (now is yahoo) but its not returning anything as callback,

according to this (https://github.com/mscdex/node-imap/issues/309) it must return err,code and then we have to be able to extract the moved emails new uid but its not happening.

my code is : 

Connection[account].move(uid, remoteFolder, function (err, code) {
	// As of node-imap 11b37fcd, you can get the UID of the
	// moved message in the destination mailbox from `code`:
	//   if (code.key === 'COPYUID' && code.val[2])
	//     var newUID = code.val[2];
	if (err) {
		framework.logger.warn('IMAP-MOVE-EMAIL: ' + username + ' - ' + account);
		return {err: err};
	}
	console.log('ENDDDDD', code);
	return {};
	// TODO : -> @Matt return new uid
});

but the result undefined; check  the screenshot
![aliiiiiii](https://cloud.githubusercontent.com/assets/6294823/8649551/9d727562-2980-11e5-84d8-02b915f64193.jpg)

**Comment by mscdex** [comment]
Can you try the master branch now and let me know if that fixes things for you?

**Comment by ehsanagh** [comment]
hi, sorry for the gap in replying, i just updated master branch and the bug get fixed.
thank you.
i created some function and i'd like to publish them as utils for node-imap, i'll inform you when i did,
i'll be happy if you check the codes and help me to make it as a module for nodejs.
Regards
