### ISSUE TITLE
Getting email address on connection

### ISSUE THREAD

**Issue by yuklai** [mscdex/node-imap#489]
Hi there,
When someone logins with a user name (not full email) to gmail, the response contains the full gmail. Is that currently captured anywhere or returned through any events? E.g.

```
1 login **foo.bar** MyP@ssW0rd
* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS
1 OK **foo.bar@gmail.com** authenticated (Success)
```

**Comment by mscdex** [comment]
No, freeform response text like that is not captured/interpreted.

**Comment by yuklai** [comment]
Ah, thanks! That makes sense.
I love the **versatility** of imap. ;)

**Comment by mscdex** [comment]
FWIW isn't the default domain always `gmail.com`? So if there is no `@` in the username then you can assume it's `@gmail.com`?

**Comment by yuklai** [comment]
The user can sign up for @mycompany.com with gmail. I don't think they limit the username input to just be gmail.com. I could be wrong.

**Comment by mscdex** [comment]
For Google Apps domains you always need to put the domain though, don't you? At least for IMAP since Google Apps and normal Gmail all use the same IMAP server?

**Comment by yuklai** [comment]
Yea, you could be right, since they are using the same server.

**Comment by ultimate-tester** [comment]
Correct. If you login with just a username, Google will authenticate at the gmail.com domain. If you wish to authenticate at another domain, you need to supply that domain name after the username.
