### ISSUE TITLE
UTF8 decoding

### ISSUE THREAD

**Issue by mkenran** [mscdex/node-imap#495]
Hi,
My raw header subject is "Confirmation de votre adresse Ã©lectronique"
using chunk.toString('utf8') or a StringDecoder change nothing in my browser output.

i added <meta charset="UTF-8"> to my header without success.
I also tried escape, decodeURI, encode URI, unescape.

Thanks for your help

**Comment by mscdex** [comment]
Can you show the complete code you are using?

**Comment by mkenran** [comment]
I'm using the first example in the readme and store the return in a database :

var im = new imap({
				user: decodeURIComponent(docs[0].user),
				password: decodeURIComponent(docs[0].password),
				host: docs[0].in_server,
				port: docs[0].in_port,
				tls: docs[0].in_tls
			});
			
			
			im.once('ready', function() {
				im.openBox('INBOX', true, function(err, box) {
					if (err) throw err;
					// fetch last 10
					var f = im.seq.fetch('1:10', {
					  bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
					  struct: true
					});
					f.on('message', function(msg, seqno) {
						
						//console.log('Message #%d', seqno);
						var prefix = '(#' + seqno + ') ';
						
						// save message to db
						var mess = { login: login, box : 'INBOX', account: docs[0].name};
						//var decoder = new StringDecoder('utf8');
						
						msg.on('body', function(stream, info) {
							var buffer = '';
							stream.on('data', function(chunk) {
								buffer += chunk.toString('utf8'); //decoder.write(chunk); //
							});
							stream.once('end', function() {
								var parsh = imap.parseHeader(buffer);
								mess.sender = parsh.from[0];
								mess.to = parsh.to;
								mess.date = parsh.date[0];
								mess.subject = parsh.subject[0];
								//console.log(prefix + 'Parsed header: %s', inspect(parsh));
							});
						});
						
						msg.once('attributes', function(attrs) {
							mess.uid = attrs.uid;
							mess.flags = attrs.flags;
							//console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
						});
						
						msg.once('end', function() {
							
							yc.tables.messages.insert(mess);							
							//console.log(prefix + 'Finished');

							
						});
					});
					f.once('error', function(err) {
						console.log('Fetch error: ' + err);
					});
					f.once('end', function() {
						console.log('Done fetching all messages!');
						im.end();
						clbk();
					});
				});
			});

			im.once('error', function(err) {
				console.log(err);
			});

			im.once('end', function() {
				console.log('Connection ended');
			});

			im.connect();

The data (using nedb) is stored in plain json text : 

{"login":"admin","box":"INBOX","account":"gmx","sender":"registration <services_internet@grx34.fr>","to":["Mr johndoe <johndoe@gmx.fr>"],"date":"Sun, 4 Jan 2015 08:52:50 +0100","subject":"Confirmation de votre adresse Ã©lectronique","uid":8,"flags":["\\Seen"],"_id":"BvTOzh6PT8cFkuSA"}

then in my ejs template :

<html>
<head>
<meta charset="UTF-8">
<title>my title</title></head>
<script src="/socket.io/socket.io.js"></script>
<script src="/assets/ycfw.js"></script>
<style>

<% for (mes in messages) { %>
   <span class="msg_subject"><%= messages[mes].subject %></span>
<% } %>

**Comment by mkenran** [comment]
oops wrong button...

**Comment by alarangeiras** [comment]
Hi, i'm with same issue.

**Comment by mscdex** [comment]
@alarangeiras Assuming the charset for your text is utf8, does setting `stream.setEncoding('utf8');` fix things?

**Comment by mscdex** [comment]
If setting `stream.setEncoding()` immediately inside the `'body'` event does not work, then most likely the original email already contains invalid characters or the string is not UTF-8, but some other encoding instead.
