### ISSUE TITLE
While fetching Email list in parse header I date is different-2 Time Zone

### ISSUE THREAD

**Issue by Gajendracis** [mscdex/node-imap#500]
Hi,

When I am fetching a list of email then In parse header I am getting a date object, in this date object I am getting different different Time Zone(GMT) for each mail I fetched. (Like [ 'Fri, 2 Oct 2015 19:04:30 +0300' ], [ 'Fri, 2 Oct 2015 10:40:49 -0700' ], [ 'Sat, 03 Oct 2015 00:24:40 +0000' ])

How can I solve this issue to get a one standard time zone only.

**Comment by mscdex** [comment]
You'll have to show code because by default, headers are not parsed into objects like that.
