### ISSUE TITLE
Uncaught TypeError: Socket is not a function

### ISSUE THREAD

**Issue by nickzuber** [mscdex/node-imap#501]
Whenever I call ```imap.connect();``` in my app, I receive this error message in my client window that breaks my entire app, and this is where the error is coming from:
```
Connection.prototype.connect = function() {
  var config = this._config,
      self = this,
      socket,
      parser,
      tlsOptions;

  socket = config.socket || new Socket();
  //                        ^
  // Uncaught TypeError: Socket is not a function
  socket.setKeepAlive(true);
  this._sock = undefined;
  this._tagcount = 0;
  this._tmrConn = undefined;
  this._tmrKeepalive = undefined;
  this._tmrAuth = undefined;
  this._queue = [];
  this._box = undefined;
  this._idle = { started: undefined, enabled: false };
  this._parser = undefined;
  this._curReq = undefined;
  this.delimiter = undefined;
  this.namespaces = undefined;
  this.state = 'disconnected';
```
Does anyone have any ideas on how to fix/what is going on?

**Comment by nickzuber** [comment]
I'm running node v4.1.2, and node-imap v0.8.15

**Comment by mscdex** [comment]
Well, `Socket` comes from `require('net').Socket`, which is still exported in node v4 (and *is* a function), so I'm not sure why that error would occur. Are you using any other third-party modules that might interfere with core modules?

**Comment by nickzuber** [comment]
@mscdex I'm using react and node-jsx, and I'm using reactify and browserify to transform the react jsx etc. Do you suspect these might be causing an issue? I think you might be on to something, because only when the code is concatenated into a single file and transformed into the browser does the Socket appear to be undefined..

**Comment by mscdex** [comment]
Well, browser-side javascript does not have TCP sockets available to them, so you won't be able to use this module. The exception being if you pass in your own Duplex stream as the `socket` config option that acts as the TCP connection to the IMAP server. This stream would need to somehow be connected to a backend server somewhere that proxies TCP traffic.

So for example you might create a Duplex stream that is connected to a WebSocket, where the server performs the actual TCP connection on behalf of the browser and then sends and receives socket data over the WebSocket instead. There may be such proxies already available, but they would need to provide a node stream though.
