### ISSUE TITLE
No way to set flags without leading backslash

### ISSUE THREAD

**Issue by evarsanyi** [mscdex/node-imap#502]
An imap server from 1and1 supports a number of flags that do not have a leading '\' in them:

```
<= '* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=LOGIN AUTH=PLAIN] IMAP server ready H mieueus006 106587 IMAP-0MdsaD-1ZwqHy0Pvh-00Pfts'
...
<= '* FLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft $Forwarded $Junk $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $NotJunk JunkRecorded NotJunk)'
<= '* OK [PERMANENTFLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $Forwarded $Junk $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $NotJunk JunkRecorded NotJunk \\*)] Unlimited'
```

If I try to write any of these non backslashed flags node-imap helpfully adds backslashes which the server then rejects.

Here's what I got from the server on a particular message (from the debug output of fetch):
`FLAGS (\\Answered \\Flagged \\Seen $MailFlagBit0 $MailFlagBit2 $NotJunk JunkRecorded NotJunk)`

Here's what I tried to write back and the servers rejection:

```
SETTING FLAGS= [ '\\Answered', '\\Seen', '$NotJunk', '\\Flagged' ]
<= '+ idling'
=> DONE
<= 'IDLE OK IDLE completed'
=> 'A8 UID STORE 2 FLAGS.SILENT (\\Answered \\Seen \\$NotJunk \\Flagged)'
<= 'A8 BAD unknown systemflag'
=> 'IDLE IDLE'
```

I commented out the helpful addition of \'s in _store() and everything works fine.

```
    if (isFlags) {
      // if (items[i][0] !== '\\')
      //  items[i] = '\\' + items[i];
    } else {
```

**Comment by surajwy** [comment]
Refer: https://tools.ietf.org/html/rfc3501#section-2.3.2
There is two type of Flags:
- **System flags:** The one which starts with **\** like \Answered, \Flagged, \Deleted, \Seen etc.
- **Keywords:** A keyword is defined by the server implementation and does not contain **\** at the beginning. Mostly you will see things like $Junk, $NotJunk etc. here.

So, to add keywords like $Junk, use this code:
```
imap.addKeywords(uid, "$Junk", function(){})
```
