### ISSUE TITLE
Imap not fetching nested e-mails.

### ISSUE THREAD

**Issue by Cherviakov** [mscdex/node-imap#504]
Hello I'm working on system, part of which listens to e-mails via imap and should read all coming messages and process them. My client sending me e-mails and some of them are nested in previous ones. Imap successfully detect, them bur command imap.seq.fetch make no effect. Using imap 0.8.15.

If e-mail is first level, or make whole sequence unread so app detect it again processing goes alright, bunt inside of sequence nothing happens. So far have to stick to not nested emails only, but is there a way to fix this?

**Comment by Cherviakov** [comment]
Resolved. Problem appeared in using imap.seq.fetch according to frist two examples, instead of imap.fetch. 

I don't know what for creators actually need that imap.seq but really better not use it at all, because it has many bugs on it (or not working intentionally).

**Comment by mscdex** [comment]
The `imap.seq` namespace is for dealing with sequence numbers. The other methods are for dealing with UIDs. Both types can be useful. Sequence numbers always range from 1 to the number of messages in the mailbox. UIDs are message numbers that uniquely identify that message in that mailbox (until the UID validity value for that mailbox changes, at which time UIDs for messages are changed).

**Comment by Cherviakov** [comment]
Thank you for response. That explains odd behavior of seq.fetch method.
