### ISSUE TITLE
event 'mail' is slow or not working

### ISSUE THREAD

**Issue by samiralajmovic** [mscdex/node-imap#505]
I'm using these settings:

var imap = new Imap({
  user: "mailplaceholder@outlook.com",
  password: "passplaceholder",
  host: "imap-mail.outlook.com",
  port: 993,
  tls: true
});

and when debug is turned on:

[connection] Connected to host
<= '* OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (XXXXXXXX)'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT AUTH=PLAIN AUT
H=XOAUTH2 SASL-IR'
<= 'A0 OK CAPABILITY completed'
=> 'A1 LOGIN "xxx@outlook.com" "xxx)"'
<= '* CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT'
<= 'A1 OK xxx@outlook.com authenticated successfully'
=> 'A2 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A2 OK NAMESPACE completed'
=> 'A3 LIST "" ""'
<= '* LIST (\\Noselect) "/" ""'
<= 'A3 OK LIST completed'
=> 'A4 EXAMINE "INBOX"'
<= '* FLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft)'
<= '* 51 EXISTS'
<= '* 0 RECENT'
<= '* OK [UNSEEN 41] Message 41 is first unseen'
<= '* OK [UIDVALIDITY 89646122] UIDs valid'
<= '* OK [UIDNEXT 100089] Predicted next UID'
<= '* OK [PERMANENTFLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft)] Limite
d'
<= 'A4 OK [READ-ONLY] EXAMINE completed.'
{ name: 'INBOX',
  flags: [ '\\Answered', '\\Flagged', '\\Deleted', '\\Seen', '\\Draft' ],
  readOnly: true,
  uidvalidity: 89646122,
  uidnext: 100089,
  permFlags: [ '\\Answered', '\\Flagged', '\\Deleted', '\\Seen', '\\Draft' ],
  keywords: [],
  newKeywords: false,
  persistentUIDs: true,
  nomodseq: false,
  messages: { total: 51, new: 0 } }
=> 'NOOP NOOP'
<= 'NOOP OK NOOP completed'
=> 'NOOP NOOP'
<= 'NOOP OK NOOP completed'
=> 'NOOP NOOP'
<= 'NOOP OK NOOP completed'
=> 'NOOP NOOP'
<= 'NOOP OK NOOP completed'

Sometimes the mail event works, other times nothing happens. As you can see, opening the mailbox works just fine, and I suppose I could do some polling on my side, but it feels dirty.

**Comment by mscdex** [comment]
Mail notifications (if available) should be sent by the server when responding to NOOP requests, which you can see are being sent. If the server isn't sending those notifications, there's not much that can be done client-side about it.

**Comment by samiralajmovic** [comment]
Yes, seems to be wrong on their end, and opening the mailbox is the way to go then.

**Comment by mscdex** [comment]
Just to add here, instead of polling by re-opening the mailbox, you could also just do an `imap.search()` for unread messages, which *may* be more efficient (depending on the server's IMAP implementation).
