### ISSUE TITLE
Search for MESSAGE-ID not allways returning a value

### ISSUE THREAD

**Issue by Alyndre** [mscdex/node-imap#511]
Hello, i'm working on a personal app with this module, but when I'm trying to search by MESSAGE-ID, sometimes doesn't return any value when I'm expecting one.

Example:
_imap.search([ [ 'HEADER',  'MESSAGE-ID',  'EBCA9A8F-3856-4430-953E-BDBB36FADB66@gmail.com ' ] ], function (err, results){...});_
This is not returning any value, when that message-id is certified that exist on that mailbox.

But, for example, this:
_imap.search([ [ 'HEADER',  'MESSAGE-ID',  '5664ac7dca243_48ac3f8507e036681656690574@ns5001546.ip-192-95-32.net.mail' ] ], function (err, results){...});_
That example is returning a value, like expected.

I don't know if i'm doing something wrong or the functionality isn't working right.

Thank you

**Comment by realyze** [comment]
I'm having exactly the same issue. I ended up searching using email subject to limit the number of hits and then searching within that set programatically using message-id. Not particularly clever but works.

**Comment by mscdex** [comment]
If the server doesn't return any results, then there's not much that can be done by this module unfortunately. Some servers may deviate from the IMAP spec and make searches case sensitive, exact matches vs substring matches, etc.
