### ISSUE TITLE
Can I get notification when new email arrived.

### ISSUE THREAD

**Issue by ZuzooVn** [mscdex/node-imap#515]
Did the imap have the same function as below library?
https://github.com/circuithub/mail-listener
https://github.com/chirag04/mail-listener2

Thank you

**Comment by mscdex** [comment]
I don't understand the question. Those two libraries build on the functionality provided this library.

**Comment by ZuzooVn** [comment]
That mean with mail-listener/mail-listener2, I can get the notification when I have a new email.
I just want to know that: Can I do this with only your node-imap? 
All of your sample code can get the email whenever I run the code. But I want the code will run in the background and notify me when I have new email.

**Comment by mscdex** [comment]
Seeing as how those modules use this library, then the answer to your question is yes.
