### ISSUE TITLE
Using xoauth2 authentication failed

### ISSUE THREAD

**Issue by ShaharLahav** [mscdex/node-imap#522]
Hi, I am using xoauth2 to connect to imap and I'm getting this error:
```
`[09:50:28.806] [LOG] [connection] Connected to host
[09:50:28.873] [LOG] <= '* OK Gimap ready for requests from 31.154.25.42 q4mb701
07656lfe'
[09:50:28.881] [LOG] => 'A0 CAPABILITY'
[09:50:29.067] [LOG] <= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID
 XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIE
NTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH'
[09:50:29.069] [LOG] <= 'A0 OK Thats all she wrote! q4mb70107656lfe'
[09:50:29.073] [LOG] => 'A1 AUTHENTICATE XOAUTH2 ******************************************
****************************************************************************************************************************
********************************************************************************='
[09:50:29.374] [LOG] <= '+ eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2Nvc
GUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ=='
[09:50:29.377] [LOG] => '\r\n'
[09:50:29.534] [LOG] <= 'A1 NO [AUTHENTICATIONFAILED] Invalid credentials (Failu
re)'
[09:50:29.537] [ERROR] ERROR Imap:Error: Invalid credentials (Failure)
[09:50:29.755] [LOG] [connection] Ended
[09:50:29.756] [LOG] Imap: Connection ended
[09:50:29.758] [LOG] [connection] Closed`
```

here is my connection code : 

```
`this.setImap = function(connParams) {
    //----------------------------------------------
    console.log(connParams);
    xoauth2gen = xoauth2.createXOAuth2Generator({
      user: connParams.user",
      clientId: configAuth.googleAuth.clientID,
      clientSecret: configAuth.googleAuth.clientSecret,
      refreshToken: connParams.refresh_token,
      accessToken: connParams.access_token,
       customPayload: {
      "access_type": "offline"
    }
    });


    xoauth2gen.getToken(function(err, token) {
      if (err) {
        return console.log(err);
      }
      console.log("AUTH XOAUTH2 " + token);
      connParams.xoauth2 = token;
    });

    connParams = {
      id: 13,
      user: connParams.user,
      xoauth2: connParams.xoauth2,
      host: 'imap.gmail.com',
      port: 993,
      tls: 1,
      debug: console.log
    }
    //------------------------------------------- 
    connParams.tlsOptions = {
      rejectUnauthorized: false
    };

    console.log(connParams);



    self.imap = new Imap(connParams);

    this.imap.once('ready', function() {
      console.log('Imap: ready');
      self.openInbox();
    });

    this.imap.once('error', function(err) {
      console.error("ERROR Imap:" + err);
    });

    this.imap.once('end', function() {
      console.log('Imap: Connection ended');
    });
  };
```
Checked a million time the details :(

here is the scope I'm using : 
```
scope: ['profile', "https://mail.google.com/" ]
```
I would appreciate any help, Thanks!!

**Comment by mscdex** [comment]
It's hard to tell if your code really is exactly as you show it, but `xoauth2gen.getToken()` is asynchronous, so it returns immediately and then you try to use the value of `connParams.xoauth2` before it has been set (when `getToken()`'s callback is finally called). You need to wait for `getToken()` to complete first before connecting to the imap server.

**Comment by ShaharLahav** [comment]
Hi, thanks for your quick comment,
iv'e checked and i get the xoauth2 token ... it's not undefined....
So I think this is not the problem here.

**Comment by mscdex** [comment]
Unfortunately I can't help you much then as I'm not very familiar with oauth stuff

**Comment by ShaharLahav** [comment]
Thanks anyway

**Comment by ShaharLahav** [comment]
Hi , solved it by adding a space in the user field in the xoauth generation plus deleting the username and the password in the imap connection....
Now, i have another problem... box.messages.total doesn't return the number of the last message, it returns the number of a message from January 14th... 
any idea ?

**Comment by mscdex** [comment]
Thanks for the update.

`box.messages.total` should just be a count of the total number of messages in that mailbox, not a specific sequence number or UID. Although technically I suppose `total - 1` would be the last sequence number in the mailbox. Does the `total` not match the actual number of messages in that mailbox?

**Comment by ShaharLahav** [comment]
`box.messages.total` Does not match the actual number of messages in the mailbox...

**Comment by ShaharLahav** [comment]
` var f = self.imap.fetch((box.messages.total - 5) + ':*', {
          struct: true,
          markSeen: conf.imap.markSeen,
          bodies: ''
        });`
I have used it that way and it tries to fetch hundreds of messages

**Comment by ShaharLahav** [comment]
(self=this)

**Comment by ShaharLahav** [comment]
??

**Comment by spyeadon** [comment]
@ShaharLahav I'm currently getting the **same exact** sequence of debug statements and the error that you had at the beginning of this thread. I'm using the xoauth2 generator library as you are with getToken... and creating an imap instance as you are too. Could you describe in a little more detail what you did to get that connection working for me? Maybe post the xoauth2generator/token retrieval and imap configuration code that worked for you?

**Comment by fhackenb** [comment]
@spyeadon you figure this out either?
