### ISSUE TITLE
box.messages.total doesn't returns the actual number of emails in the box

### ISSUE THREAD

**Issue by ShaharLahav** [mscdex/node-imap#524]
box.messages.total Does not match the actual number of messages in the mailbox...
I am trying to fetch emails from gmail.
Here is the code: 

  ```
this.openInbox = function() {
    this.imap.openBox('INBOX', true, function(err, box) {
      if (err) {
        console.error('ERROR Imap box: ' + JSON.stringify(err));
        throw err;
      } else {
        var f = self.imap.fetch((box.messages.total - 5) + ':*', {
          struct: true,
          markSeen: conf.imap.markSeen,
          bodies: ''
        });
        f.on('message', self.readMsg);

        f.once('error', function(err) {
          console.error('ERROR Imap: Fetch error: ' + err);
        });
        f.once('end', function() {
          console.log('Imap: Done fetching all messages!');
          self.imap.end();
        });
      }
    });
  };
```

I have used it that way and it tries to fetch hundreds of messages since january.

**Comment by shnode** [comment]
you misunderstand the `box.messages.total` and the `uid` for single mail.

mails' ids keeps growth even you delete some of them
but `box.messages.total` only return the current emails number.

which means `total` may give you a 351, but a email id may already  be 405.

so it's not accuracy to count id by `box.messages.total - 5`

**Comment by mscdex** [comment]
@shnode is correct. If you want to fetch the last 5 email messages in the mailbox, you should instead use the `seq` namespace (which deals with sequence numbers instead of message UIDs) like so:

```javascript
var f = self.imap.seq.fetch((box.messages.total - 5) + ':*', {
  struct: true,
  markSeen: conf.imap.markSeen,
  bodies: ''
});
```
