### ISSUE TITLE
How to open multiple box folder and sub-folder in INBOX

### ISSUE THREAD

**Issue by johnzhou2011** [mscdex/node-imap#527]
hello,

There are some rules in mailbox then email will move to target folder when email arrive.
How to open all boxes in one email account?

**Comment by mscdex** [comment]
If you need to monitor multiple mailboxes simultaneously, you will need to create a new connection for each mailbox, as IMAP does not support more than one open mailbox at a time.

**Comment by johnzhou2011** [comment]
I mean in one mailbox but lots of sub-folders in INBOX folder. It's that possible to get all mails in INBOX and sub-folders?

**Comment by mscdex** [comment]
There is no way to listen for mail notifications for multiple folders (subfolders or otherwise) either. *Supposedly* the NOTIFY extension does allow you to do this, but that's not exactly clear from the relevant RFC. Also, not all servers support NOTIFY.

**Comment by silentroach** [comment]
but what is `subscribe` command for?
