### ISSUE TITLE
 I want to use copy(), move(), but always failed , how to properly use them

### ISSUE THREAD

**Issue by dogsmall** [mscdex/node-imap#529]
hello:
     I want to copy a message from one mailbox to another, how do I

**Comment by mscdex** [comment]
Can you expand a bit on that? What does "failed" mean? What error messages do you get? What code have you tried?

**Comment by dogsmall** [comment]
`function copyMessages(filter) {
    srcServer.search(filter, function(err, results) {
        if (err) throw err;
        var count = results.length;
        srcServer.fetch(results,
            { headers: { parse: false },
                body: true,
                cb: function(fetch) {
                    fetch.on('message', function(msg) {
                        var buffer = [], bufLen = 0;
                        console.log('Got a message with seq no: ' + msg.seqno);
                        msg.on('data', function(chunk) {
                            buffer.push(chunk);
                            bufLen += chunk.length;
                        });
                        msg.on('end', function() {
                            console.log('Finished message no. ' + msg.seqno);
                            buffer = Buffer.concat(buffer, bufLen);
                            destServer.append(buffer, {
                                date: new Date(msg.date),
                                flags: ['Seen']
                            }, function(err) {
                                if (err) throw err;
                                if (--count === 0) {
                                    console.log('Done copying!');
                                    srcServer.logout();
                                    destServer.logout();
                                }
                            });
                        });
                    });
                }
            }, function(err) {
                // all fetches complete here, but appending to other server may not
                // necessarily be finished yet
                if (err) throw err;
            }
        );
    });
}
`
code is no work,   Can you tell me a correct use of copy () and move () ?

**Comment by dogsmall** [comment]
I want to Copy or Move mail from one inbox to another on (2 or 1) different servers.

**Comment by mscdex** [comment]
That's not how `fetch()` currently works. It looks like you may be basing the code off an older version of `imap` (see the API change list [here](https://github.com/mscdex/node-imap/wiki/API-changes-between-v0.7-and-v0.8) if you have additional code that needs updating). Also, `copy()` and `move()` are for copying/moving between mailboxes of the same account (on the same server).

You might try something like this:

```javascript
function copyMessages(filter) {
  srcServer.search(filter, function(err, results) {
    if (err) throw err;
    var toAppend = results.length;
    var fetch = srcServer.fetch(results, { bodies: '' });
    fetch.on('message', function(msg, seqno) {
      var buffer = [];
      var bufLen = 0;
      var msgDate;
      msg.on('body', function(stream, info) {
        stream.on('data', function(data) {
          buffer.push(data);
          bufLen += data.length;
        });
      });
      msg.on('attributes', function(attrs) {
        msgDate = attrs.date;
      });
      msg.on('end', function() {
        buffer = Buffer.concat(buffer, bufLen);
        destServer.append(buffer, {
          date: msgDate,
          flags: ['Seen']
        }, function(err) {
          if (err) throw err;
          if (--toAppend === 0) {
            srcServer.end();
            destServer.end();
          }
        });
      });
    });
    fetch.on('end', function() {
      console.log('Done fetching all messages!');
      imap.end();
    });
  });
}
```

**Comment by dogsmall** [comment]
thanks ,this code is from https://github.com/mscdex/node-imap/issues/175  

If I want to achieve  Copy or Move mail from one inbox to another on (2 or 1) different servers.
What should i do ？

**Comment by mscdex** [comment]
Use the code that I just posted along with the latest version of this module.

**Comment by dogsmall** [comment]
Let me try，thanks again

**Comment by dogsmall** [comment]
var Imap = require('imap');

var srcServer = new Imap({
    user: 'xxxxxxx@qq.com',
    password: 'xxxxxxx',
    host: 'imap.qq.com',
    port: 993,
    tls: true
});
var destServer = new Imap({
    user: 'xxxxxxx@163.com',
    password: 'xxxxxxxxxx',
    host: 'imap.163.com',
    port: 993,
    tls: true
});

function openInbox(conn, cb) {
    conn.once('ready', function () {
        conn.openBox('INBOX', (conn === srcServer ? true : false), cb);
    })
}


function copyMessages(filter) {
    console.log("....")
    srcServer.search(filter, function (err, results) {
        if (err) throw err;
        var toAppend = results.length;
        var fetch = srcServer.fetch(results, {bodies: ''});
        fetch.on('message', function (msg, seqno) {
            var buffer = [];
            var bufLen = 0;
            var msgDate;
            msg.on('body', function (stream, info) {
                stream.on('data', function (data) {
                    buffer.push(data);
                    bufLen += data.length;
                });
            });
            msg.on('attributes', function (attrs) {
                msgDate = attrs.date;
            });
            msg.on('end', function () {
                buffer = Buffer.concat(buffer, bufLen);
                destServer.append(buffer, {
                    date: msgDate,
                    flags: ['Seen']
                }, function (err) {
                    if (err) throw err;
                    if (--toAppend === 0) {
                        console.log('Done copying!');
                        srcServer.end();
                        destServer.end();
                    } else
                        console.log(toAppend + ' message(s) to go ...');
                });
            });
        });
    });
}

openInbox(srcServer, function (err) {
    if (err) throw err;
    openInbox(destServer, function (err) {
        if (err) throw err;
        copyMessages(['ALL']); // copies ALL messages
    });
});




I modified some places.  Something wrong?   no work also no err

**Comment by mscdex** [comment]
At first glance it looks alright. Try adding more debugging statements to see where things stop. You can also set `debug: console.log` in the connection config objects to get debug output, although you may want to use a custom function for each connection so you can differentiate output for each connection (e.g. `debug: function(s) { console.log('srcServer: ' + s); }` for the `srcServer` connection config).

**Comment by dogsmall** [comment]
It 's stop before  
conn.once('ready', function () {
        conn.openBox('INBOX', (conn === srcServer ? true : false), cb);
    })

Maybe conn.once is wrong

**Comment by mscdex** [comment]
Did you make sure you have the latest version of `imap`? What does `npm ls` show for `imap`?

**Comment by dogsmall** [comment]
imap@0.8.16

**Comment by dogsmall** [comment]
have a new error 
c:\Users\Administrator\WebstormProjects\copyAndmove\node_modules\imap\lib\Connection.js:400
    throw new Error('Not authenticated');
    ^

Error: Not authenticated
    at Connection.openBox (c:\Users\Administrator\WebstormProjects\copyAndmove\node_modules\imap\lib\Connection.js:400:11)
    at openInbox (c:\Users\Administrator\WebstormProjects\copyAndmove\move.js:23:10)
    at Object.<anonymous> (c:\Users\Administrator\WebstormProjects\copyAndmove\move.js:67:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by mscdex** [comment]
I think you're missing the `srcServer.connect();` and `destServer.connect();`.

**Comment by dogsmall** [comment]
function openInbox(conn, cb) {
    debug(44444) ;
    conn.connect(function (err) {
        if (err) throw err;
        conn.once('ready', function () {
            conn.openBox('INBOX', (conn === srcServer ? true : false), cb);
        })
    });

    debug(3333);
}

is this ?

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while authenticating with server
    at null._onTimeout (c:\Users\Administrator\WebstormProjects\copyAndmove\node_modules\imap\lib\Connection.js:138:17)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by mscdex** [comment]
Well, it'd be more like this:

```javascript
function openInbox(conn, cb) {
    conn.once('ready', function () {
        conn.openBox('INBOX', (conn === srcServer ? true : false), cb);
    });
    conn.connect();
}
```

If you're still getting the timeout error, then try adding the `debug: ....` config option like I previously mentioned to see what is being sent/received at the protocol level.

**Comment by dogsmall** [comment]
thanks, you are right ,when I modify the code,it's work  but now have a error

**Comment by mscdex** [comment]
Try enabling debug output and see what is being sent and what the server is replying with when the error occurs.

**Comment by dogsmall** [comment]
everything is ok . thanks

**Comment by TejasBIngle1** [comment]
@mscdex can u please advice
