### ISSUE TITLE
How to stop connection immediately when fetching multiple emails

### ISSUE THREAD

**Issue by shnode** [mscdex/node-imap#531]

**Comment by mscdex** [comment]
You can try `imap.destroy();`

**Comment by shnode** [comment]
having tried it, but a strange error appeared.

it seems that `destroy()` method is not stable for successive messages response:

        var msg = self._curReq.fetchCache[info.seqno], toget;
                          ^
    
    TypeError: Cannot read property 'fetchCache' of undefined
