### ISSUE TITLE
Can we increase a chunk size since fetching large email is too slow.

### ISSUE THREAD

**Issue by vikaskanani** [mscdex/node-imap#541]
I found that we can increase the chuck size from the default 16384. see [here ](http://stackoverflow.com/a/24006680/415865) and [here](https://nodejs.org/api/stream.html#stream_new_stream_writable_options)

When I checked your code, it looks like stream is create with socket. I found another [thread](http://stackoverflow.com/questions/14537183/nodejs-set-highwatermark-of-socket-object) that with TCP its not possible. I am not familiar with TCP and UDP, but is there any way we can increase the speed.

FYI, I am testing an attachment with around 19 mb

**Comment by mscdex** [comment]
Are you sure that it's the `highWaterMark` that is causing your speed problems? What are you comparing the speed with? What speeds do you get?

**Comment by vikaskanani** [comment]
I have 100 Mbps lease line connection, but it takes more than 10 mins to
load 19 mb email. Task manager shows 0.1 Mbps download speed with node
process, while outlook can give 3.1+ Mbps speed.

**Comment by mscdex** [comment]
Out of curiosity, can you post the code you're using?

**Comment by vikaskanani** [comment]
We'll I realize. Its the rackspace.com (email service provider) which is slow. When I tested my code with gmail, it works as expected. I was getting decent 10 Mbps+ speed.

However, if you wish to look at my code, [here](https://gist.github.com/vikaskanani/09320969e12476d657d1) it is.

**Comment by mscdex** [comment]
The code looks mostly alright to me, nothing that should cause latency. I will say though that I think you can get away without explicitly buffering the message bodies. Just create the MailParser instance earlier in the parent scope and do `stream.pipe(mp);` inside the `body` event handler.

**Comment by mscdex** [comment]
Closing this for now, if you encounter a discrepancy in the future feel free to open a new issue.
