### ISSUE TITLE
seq.fetch returns a different UID or Invalid messageset

### ISSUE THREAD

**Issue by spoi** [mscdex/node-imap#542]
Hello mscdex and everyone else.

We are having some trouble getting node-imap and Dovecot to play together well.

We suspect that it it might be a Dovecot problem, but it seems odd that it would be a problem for years and was hoping someone might shed some light on this situation.

After getting the mailbox contents and securing the UID of each message, trying to fetch those UIDs sometimes returns a "Error in IMAP command FETCH: Invalid messageset".  We suspected we got this error on newer messages that may have been read/touched by an email client (Apple Mail, iOS, Thunderbird, etc.).

So we gave up on trying to fetch by UID, thinking that maybe Dovecot is twitchy and changing UIDs in the time between getting a list and asking for the message, so we started searching by the header 'message-id' (that long stringy thing generated by most modern mail relays, eg: '<blahblahblah@mail.gmail.com>').

This is where things get weird.

Sending imap.search the 'message-id' will return the same/expected message UID in 'results', so we know that we are getting the expected message.  But when we imap.seq.fetch with the 'results' from the search (that contains the correct UID), and we look at the 'attributes' of the returned imap.seq.fetch message, the UID, 'message-id', and message are for a completely different message (or a "Error in IMAP command FETCH: Invalid messageset").

Now the "Error in IMAP command FETCH: Invalid messageset" error messages starts making sense.  node-imap imap.seq.fetch is asking for one UID and getting returned something that doesnt exist because there is a disconnect between the node-imap imap.seq.fetch and Dovecot return.  Searching by 'HEADER' and UID return the same results.

After entertaining the idea that it could be email clients causing the problem, Dovecot was updated to a current/daily/dev release (2.2.devel (11120ac)) rather than use the several years old stable version in Debian 8 Jessie.

Doing a 'find /dovecot/mail/userid -name "dovecot*" -exec rm {} \;' fixes the problem temporarily, but thats a no-no, and it causes all normal clients to have to re-download all messages after the command is run.  Doing that once to fix the problem would be acceptable, but doing it minutely/hourly/daily/monthly would not be acceptable.

Its been tried with node v4.4.0 LTS and v5.8.0 Stable.

Thoughts, suggestions, tips?

Uninteresting code:

	var imap = new Imap({blah});
	imap.once('ready', function() {

		// currentbox is a valid mailbox name

		imap.openBox(currentbox, true, function(err, box) {
			imap.search([["HEADER","message-id","<blahblahblah@mail.gmail.com>"]], function(err, results) {

				// results.uid is 449

				var f = imap.seq.fetch(results, {
					f.on('message', function(msg, seqno) {
						msg.once('attributes', function(attrs) {

							// attrs.uid is 465

						});
					});
				});
			});
		});
	});

**Comment by mscdex** [comment]
The `seq` namespace is for working with _sequence numbers_, not UIDs. In your example code you are passing UIDs to the sequence number-based `fetch()`. It just so happens there is a sequence number that matches that UID and it's fetching that, and so it will obviously have a different "UID."

**Comment by spoi** [comment]
Understood.  We were grasping at straws for troubleshooting patterns!

But the problem exists (even when the UID/sequence id guess is ignored): imap.seq.fetch results is returning/can return either:

1. something that wasnt asked for
2. an "Invalid messageset" error from IMAP

**Comment by mscdex** [comment]
You tried using either `imap.search()` with `imap.fetch()` or `imap.seq.search()` with `imap.seq.fetch()`?

**Comment by spoi** [comment]
Ouch.  That fixed it.

One must use `imap.search()` with `imap.fetch()`    **-OR-**      `imap.seq.search()` with `imap.seq.fetch()`.

They cant be mixed.  A **massive** thank you for the help.
