### ISSUE TITLE
How do I get the uid of the returned message?

### ISSUE THREAD

**Issue by BlaM** [mscdex/node-imap#545]
This code is taken from the example in your repository:

    imap.search([ 'UNSEEN', ['SINCE', 'May 20, 2010'] ], function(err, results) {
        if (err) throw err;
        var f = imap.fetch(results, { bodies: '' });
        f.on('message', function(msg, seqno) {
            ...

I just needed several hours to notice that f.on('message', function(msg, **seqno**)...) actually seems to return the seqno, even if I don't use the seq namespace. I falsely assumed that in *"uid mode"* parameter 2 would be the uid - but it is not.

I do need the uid of the message to do a followup request later on. How do I get the uid of the message I'm just recieving?

**Comment by mscdex** [comment]
It's on the object passed to the `attributes` event handler.

**Comment by BlaM** [comment]
I was blind... Thank you, you just saved my sanity. :bow:
