### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error code return on connect

### ISSUE THREAD

**Issue by JoshuaBWT** [mscdex/node-imap#551]
Hi,

I'm trying to use node-imap to read an inbox through imap and I have been able to do so using C# or directly from outlook but everytime I'm trying to connect to the imap server I get the following error : 
`{ [Error: self signed certificate in certificate chain] code: 'SELF_SIGNED_CERT_IN_CHAIN', source: 'socket' }`

I have tried googling this issue and found only results about npm. 

Here is the sample i'm using : 
```
var Imap = require('imap'),
    inspect = require('util').inspect;

var imap = new Imap({
  host: 'imap.server.name',
  port: 993,
  tls: true,
  user: 'username',
  password: "password",
});

imap.once('error', function(err) {
  console.log(err);
});

imap.once('end', function() {
  console.log('Connection ended');
});

imap.connect();
```

**Comment by JoshuaBWT** [comment]
Hi,

I found out the solution for myself by adding rejectUnauthorized: false in the tlsOptions
```
tlsOptions: {
    rejectUnauthorized: false
  }
```

**Comment by mscdex** [comment]
Setting `rejectUnauthorized: false` isn't ideal as it can potentially expose you to MITM attacks. Is the server using a self-signed certificate? Either way, you can set the `ca` in `tlsOptions` to the CA used by the server so that the server certificate can be successfully verified.
