### ISSUE TITLE
How to open box when mailboxName with "/"

### ISSUE THREAD

**Issue by johnzhou2011** [mscdex/node-imap#553]
How to open box when mailboxName with "/"?

**Comment by mscdex** [comment]
Are you actually trying to open a child folder or ?

**Comment by johnzhou2011** [comment]
yes, open a child folder. But the folder's name is something like "Z/B".

**Comment by mscdex** [comment]
You tried `imap.openBox('Z/B', ...)`? Otherwise you may need to double-check the server's hierarchy delimiter by checking the value of `imap.delimiter` and/or `imap.namespaces.personal[0]`.

**Comment by johnzhou2011** [comment]
---INBOX
--------Z/B
`imap.delimiter` is "/".
I tried to `imap.openBox('INBOX/Z/B', ...)`. of course I cannot open it by this way , but there is any other  
way to open this folder? 
And `getBoxes` also cannot get the path of this kind folder.

**Comment by mscdex** [comment]
What *does* `getBoxes()` show? I've never seen a mailbox as a child of the inbox (the "inbox" mailbox is treated special in IMAP).

**Comment by johnzhou2011** [comment]
![2016-05-13 17_22_01-z_b - microsoft outlook](https://cloud.githubusercontent.com/assets/6656559/15243668/963ec88c-192f-11e6-943e-3cde1ab884dd.png)
The sub-folder under inbox, when I use `getBoxes([],...)` the return data have no any info about "Z/B" folder.
If the folder named with `imap.delimiter`, how to open it?

**Comment by mscdex** [comment]
Did you call `getBoxes()` with just a callback (no array for the first parameter)?:

```js
imap.getBoxes(function(err, boxes) {
  if (err) throw err;
  console.dir(boxes);
});
```

**Comment by johnzhou2011** [comment]
![2016-05-16 09_41_00-](https://cloud.githubusercontent.com/assets/6656559/15278398/c0d8942a-1b4a-11e6-9110-16b3f08abe24.png)
![2016-05-13 17_22_01-z_b - microsoft outlook](https://cloud.githubusercontent.com/assets/6656559/15278399/c106973a-1b4a-11e6-89d0-120df53cbfc1.png)
When call `getBoxes()` there is no err and cannot get the sub-folder "Z/B".

Anyway, Name a folder with "\" it's not a good way , but there is no block in exchange server when create folder.

There is any other way to get  the folder "Z/B"? thank a lot! :)

**Comment by mscdex** [comment]
Can you set `debug: console.log` in your connection config object and post the resulting output (censoring username/password)? The parser doesn't seem to see the mailbox at all, so it will be interesting to see what the server is sending in the `LIST` response.

**Comment by johnzhou2011** [comment]
![2016-05-16 10_19_57-inbox - microsoft outlook](https://cloud.githubusercontent.com/assets/6656559/15278781/c8735e9a-1b4f-11e6-98ae-7e1dec996534.png)
![2016-05-16 10_19_41-](https://cloud.githubusercontent.com/assets/6656559/15278782/c87489be-1b4f-11e6-8b4c-b7afb8027b94.png)
I add a "test1" folder in inbox, the result show it out, seems just ignore "Z/B".

**Comment by johnzhou2011** [comment]
> <= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN STARTTLS IDLE NAMESPACE LITERAL+'
<= 'A2 OK CAPABILITY completed.'
=> 'A3 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A3 OK NAMESPACE completed.'
=> 'A4 LIST "" ""'
[connection] Connected to host
<= '* OK The Microsoft Exchange IMAP4 service is ready.'
=> 'A0 CAPABILITY'
<= '* LIST (\\Noselect \\HasChildren) "/" ""'
<= 'A4 OK LIST completed.'
=> 'A5 SELECT "INBOX"'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN STARTTLS IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
=> 'A1 LOGIN "" ""'
<= 'A1 OK LOGIN completed.'
=> 'A2 CAPABILITY'
<= '* 8 EXISTS'
<= '* 0 RECENT'
<= '* FLAGS (\\Seen \\Answered \\Flagged \\Deleted \\Draft $MDNSent)'
<= '* OK [PERMANENTFLAGS (\\Seen \\Answered \\Flagged \\Deleted \\Draft $MDNSent)] Permanent flags'
<= '* OK [UIDVALIDITY 110028] UIDVALIDITY value'
<= '* OK [UIDNEXT 212] The next unique identifier value'
<= 'A5 OK [READ-WRITE] SELECT completed.'
=> 'A6 UID SEARCH UNSEEN'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN STARTTLS IDLE NAMESPACE LITERAL+'
<= 'A2 OK CAPABILITY completed.'
=> 'A3 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A3 OK NAMESPACE completed.'
=> 'A4 LIST "" ""'
<= '* LIST (\\Noselect \\HasChildren) "/" ""'
<= 'A4 OK LIST completed.'
=> 'A5 LIST "" "*"'
<= '* SEARCH'
<= 'A6 OK SEARCH completed.'
=> 'IDLE IDLE'
<= '+ IDLE accepted, awaiting DONE command.'
<= '* LIST (\\HasNoChildren) "/" Calendar'
<= '* LIST (\\HasNoChildren) "/" Contacts'
<= '* LIST (\\HasNoChildren) "/" "Conversation History"'
<= '* LIST (\\HasNoChildren) "/" CQ'
<= '* LIST (\\HasChildren) "/" "Deleted Items"'
<= '* LIST (\\HasNoChildren) "/" "Deleted Items/"123123""'
<= '* LIST (\\HasNoChildren) "/" Drafts'
<= '* LIST (\\HasChildren) "/" GQA'
<= '* LIST (\\HasNoChildren) "/" GQA/ELLA'
<= '* LIST (\\HasNoChildren) "/" GQA/JACKY'
<= '* LIST (\\HasNoChildren) "/" GQA/JOJO'
<= '* LIST (\\HasChildren) "/" HR'
<= '* LIST (\\HasNoChildren) "/" HR/Felix'
<= '* LIST (\\HasNoChildren) "/" HR/HILFY'
<= '* LIST (\\HasNoChildren) "/" HR/MICHELLE'
<= '* LIST (\\Marked \\HasChildren) "/" INBOX'
<= '* LIST (\\HasNoChildren) "/" INBOX/test1'
<= '* LIST (\\HasNoChildren) "/" Journal'
<= '* LIST (\\HasNoChildren) "/" "Junk E-mail"'
<= '* LIST (\\HasNoChildren) "/" Notes'
<= '* LIST (\\HasNoChildren) "/" Outbox'
<= '* LIST (\\HasChildren) "/" "RSS Feeds"'
<= '* LIST (\\HasNoChildren) "/" "RSS Feeds/Microsoft at Home"'
<= '* LIST (\\HasNoChildren) "/" "RSS Feeds/Microsoft at Work"'
<= '* LIST (\\HasNoChildren) "/" "RSS Feeds/MSNBC News"'
<= '* LIST (\\HasNoChildren) "/" "Sent Items"'
<= '* LIST (\\HasChildren) "/" "Sync Issues"'
<= '* LIST (\\HasNoChildren) "/" "Sync Issues/Conflicts"'
<= '* LIST (\\HasNoChildren) "/" "Sync Issues/Local Failures"'
<= '* LIST (\\HasNoChildren) "/" "Sync Issues/Server Failures"'
<= '* LIST (\\HasNoChildren) "/" Tasks'
<= 'A5 OK LIST completed.'

**Comment by mscdex** [comment]
Ok, so the parser isn't missing anything here. As you can see there is no folder named "Z/B" stored *on the server*. Are you sure this isn't a local folder or something?

**Comment by johnzhou2011** [comment]
I'm sure that is a local folder, I can found it by using web site entrance.
![2016-05-16 11_29_18-z_b - outlook web access](https://cloud.githubusercontent.com/assets/6656559/15279663/7f8d6734-1b59-11e6-8db2-7b317f60dce1.png)

It's that possible that "Microsoft Exchange server" has some error when find the folder(delimiter in name)?

**Comment by mscdex** [comment]
After some brief googling, [it appears](https://support.office.com/en-gb/article/Tips-for-optimizing-IMAP-migrations-e6e4b0d0-4c3d-4826-a818-8aeab06b9b76) (see the last sub-bullet point of the last bullet point) that Exchange doesn't allow access to folders with forward slashes in the name via their IMAP interface (understandably so).

So there's nothing that can be done here I'm afraid, short of what the linked document suggests: renaming the folder.

**Comment by johnzhou2011** [comment]
@mscdex Thanks for your effort.
:)
