### ISSUE TITLE
Is ImapFetch.`end` event guaranteed to be emitted after all ImapFetch.`message` and ImapMessage.`end` events?

### ISSUE THREAD

**Issue by jstejada** [mscdex/node-imap#557]
Is the `ImapFetch.end` event guaranteed to be emitted after all `ImapFetch.message` and corresponding subsequent `ImapMessage.end` events have been emitted? (assuming there are no errors)

For example:

```javascript
      const f = imap.fetch(range, {
        bodies: ['HEADER', 'TEXT'],
      });
      f.on('message', (imapMessage) => {
        console.log('----> on msg')
       
        imapMessage.on('attributes', (attrs) => {
          // ...
        });
        imapMessage.on('body', (stream, info) => {
          // ...
        });
        imapMessage.once('end', () => {
          console.log('----> on msg end')
        });
      })
      f.once('error', (error) => console.log(error))
      f.once('end', () => {
        // Is this guaranteed to be executed ONLY after all `message` 
        // events have fired and ended?
      })
```

**Comment by mscdex** [comment]
It should be.

**Comment by jstejada** [comment]
@mscdex, thanks. I thought this wasn't the case for a moment, but it looks that what is actually going on is that when attempting to fetch a message by UID, the fetch request sometimes immediately ends without emitting the message, and sometimes correctly emits the message and ends afterwards. I am always fetching the same message in the same box. 
The debug output when the fetch request ends is the following:

```
<= 'A5 OK [READ-ONLY] Completed'
----> fetching:  [ '2' ]
=> 'A6 UID FETCH 2 (MODSEQ UID FLAGS INTERNALDATE BODY.PEEK[HEADER] BODY.PEEK[TEXT])'
<= 'A6 OK Completed (0.000 sec)'
=> 'IDLE IDLE'
---> ending fetch
---> msg undefined
<= '+ idling'
=> DONE
<= 'IDLE OK Completed'
```

The fetch seems to complete in 0s with an empty message, and without errors. However, as I mentioned, the request sometimes completes successfully with the requested message. Do you have any ideas as to what might be causing this?

**Comment by mscdex** [comment]
I don't know, this is a server issue probably as long as 2 *is* a UID that refers to a message that exists in the current mailbox. As you can see the server does not respond with any `* FETCH` responses, so there's nothing wrong client side. It's just not sending the requested message.

**Comment by jstejada** [comment]
@mscdex, thanks! The problem was an error in my logic where I was opening the incorrect mailbox sometimes and didn't realize it, causing the fetch to return empty. Thanks!

**Comment by chzhm159** [comment]
When the network stream ends, imapFetch responds to the close event, but also resides in the memory waiting for the imapMessage to finish processing. So only dealing with imapFetch's end event will lose some messages
