### ISSUE TITLE
Node-Imap only works with gmail?

### ISSUE THREAD

**Issue by MarcelCremer** [mscdex/node-imap#559]
Hello Everyone,

I have a problem connecting to servers. With my gmail account, node-imap works just fine. With all others, I get attempts like

```
<= '* OK [CAPABILITY IMAP4REV1 NAMESPACE ID AUTH=PLAIN AUTH=LOGIN UIDPLUS STARTTLS ACL METADATA] h*****.stratoserver.net IMAP4rev1 Citadel 8.24 ready'
=> 'A0 CAPABILITY'
{ Error: Timed out while authenticating with server
    at Timeout._onTimeout (..\node_modules\imap\lib\Connection.js:138:17)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) source: 'timeout-auth' }
[connection] Closed

```
It looks like the 'A0 CAPABILITY' command is not ended with an \r\n - at least I have the same behaviour with manual connecting to the servers via telnet and don't press enter afterwards. If I do, both servers answer just fine:

![image](https://cloud.githubusercontent.com/assets/6123724/16867825/6639bad6-4a74-11e6-97d7-b1f22963f576.png)

I can reproduce the same behaviour also with Exchange ('A0 CAPABILITY' is sent - now answer from server until the timeout occurs). I've already extended the authTimeout to 60 seconds which didn't help too. I've tried SSL, StartTLS and tls deactivated. All Options had the same effect.

My Node Version is 6.2.1.

Any help would be appreciated.

Best Regards
Marcel

**Comment by mscdex** [comment]
It should work with any IMAP server. I and many others have tested `imap` with non-gmail servers. You will not see the CRLF because they are stripped in the debug output.

I have never heard of Citadel before.

**Comment by MarcelCremer** [comment]
Hey @mscdex, thank you for your answer. I uninstalled the whole citadel system and used a postfix instead. it seems to work with postfix. Most Likely Citadel doesn't implement the IMAP standard or some other issue occured.

Thank you for your time, I will close the ticket for now. Feel free to test citadel anyway, because it's an easy to use/install open source groupware.

BR
Marcel
