### ISSUE TITLE
Does node-imap run in browser?

### ISSUE THREAD

**Issue by guettli** [mscdex/node-imap#563]
Is it possible to get node-imap running in the browser or in an android app?

It would be great if the client could talk to the imap-server, since this way I can
avoid a server which acts like a proxy (receiving the http-requests from the client,
and forwarding them to the imap server).

**Comment by mscdex** [comment]
Unfortunately it will not work in the browser because of the lack of access to plain TCP sockets among other things. You would have better chances in an Android app because that at least gives you access to the necessary resources, however I am not up to date on running node on Android.

**Comment by guettli** [comment]
Thank you very much for this answer. I close it.
