### ISSUE TITLE
More than two OR search criteria

### ISSUE THREAD

**Issue by wayofthefuture** [mscdex/node-imap#571]
Is there a way to have more than 2 OR search criterias? We are looking to search for approximately 100 possible email addresses in the FROM field. 

Also, is it possible to nest an OR inside of an OR?
Thanks

**Comment by mscdex** [comment]
Yes, they can be nested, although 100 could be viewed as a bit excessive. I would suggest only doing it this way if you cannot filter/search in some other, more efficient way.

**Comment by wayofthefuture** [comment]
Can their be more than two OR's? Like 100, NOT nested?

What would be a more efficient way, download the whole message and parse manually? Thanks

**Comment by mscdex** [comment]
In your case you probably would have to nest them because all criteria at the same "level" are ANDed together.

What I meant is by using other (shorter) criteria to find the messages instead. For example, if all of the addresses had a common keyword (e.g. same unique domain name or user name), you could just use that keyword(s) in the FROM field criteria since IMAP servers would search FROM fields containing that keyword anywhere in the field value.

Or if you know all of the found messages are a part of the same "conversation" and you're using gmail, you might be able to just search by conversation thread ID.

Or if you can narrow the results down by date/time to a very small duration.

.. etc., anything to avoid using an excessively long search query. Most IMAP servers may not have a problem, but others may. YMMV.

**Comment by wayofthefuture** [comment]
Man.... this is hard. We need to search for hundreds of email addresses within the inbox. Basically we have hundreds of emails in an array, and we need all messages that have a "from" field of an email in the array. I don't think imap servers would want that long query, so long query probably not possible?

I was thinking that the only other option is just to fetch all "unseen" messages, and parse them myself using the server. Do you think that would be a huge mistake or is that the only way? Thanks.

**Comment by mscdex** [comment]
One possible solution is to split up the searches in whatever sized batches you feel is appropriate. For example, maybe you only search for 25 email addresses at a time?

**Comment by wayofthefuture** [comment]
Yeah that would be really hard. I think the solution is just to do a search for all unseen, and pull the specific "from" header, then evaluate on the server.

**Comment by wayofthefuture** [comment]
Do you think 100-500 nested ORs would even work with servers? I'm wondering where the code is executed for the actual filter. Is the actual search/filtering occurring on the imap server itself? If so, then who is to say that each imap server would properly parse 100-500 nested ORs? Or would this be the same across all imap servers... Thanks.

**Comment by mscdex** [comment]
Request length is implementation-dependent. All filtering happens on the server. Other users have reported issues with long requests to specific IMAP server implementations (I want to say I distinctly recall Microsoft's implementation being one, but I am not 100% sure and even that could change depending on the server's own version). This is why I suggested to split the searches up into what should be reasonable chunks to avoid that kind of issue.

**Comment by popey456963** [comment]
If you already have access to every single mail message, have you considered letting the client handle it using something like Elasticsearch?  Likely not a problem anymore, but it is far more reliable than letting an unknown server handle it.

**Comment by mariusa** [comment]
How can one search for all messages from/to/cc a domain?
eg this doesn't work:
```
 imap.search(['ALL', ['FROM', 'test.com'], ['CC', 'test.com'], ['TO', 'test.com']], function (err, results) {
```

Thanks

**Comment by mscdex** [comment]
@mariusa You could try something like:

```js
imap.search([ ['HEADER', 'FROM', '@test.com'] ], (err, results) => {
  // ...
});
```

**Comment by mariusa** [comment]
Thanks!

**Comment by quangvinh1305** [comment]
Hi @mscdex,
How can i search like this

```
imap.search([ ['or', ['HEADER', 'FROM', 'a@test.com'],  ['HEADER', 'FROM', 'b@test.com']] ], (err, results) => {
  // ...
});
```
Thanks

**Comment by mscdex** [comment]
@quangvinh1305 That should work just fine.

**Comment by quangvinh1305** [comment]
@mscdex Thanks you Sir.

**Comment by quangvinh1305** [comment]
Hi @mscdex, 
I would like to build this query but OR query is just accept 2 arguments how can i do it.

```
imap.search([ [ 'or', [ 'Body', 'a' ], ['or', [ 'From', 'b' ] , ['From', 'c'], ['From', 'd']] ]], (err, uids) =>{
							console.log("uids, ", uids);
						});
```

Thanks

**Comment by mscdex** [comment]
@quangvinh1305 you would have to nest them, like:

```js
['or',
 'foo1',
  ['or',
   'foo2',
   ['or',
    'foo3',
     ...
   ]
  ]
]
```

**Comment by mscdex** [comment]
Closing this as the original question has already been answered.

**Comment by rptl** [comment]
@mscdex I am trying to perform nested OR. I tried as suggested above but still getting throw new Error('OR must have exactly two arguments') error.
Tried: 
`imap.search(['UNSEEN',['OR','SUBJECT','subject1',['OR','SUBJECT','subject2',['OR','SUBJECT','subject3:']]],['FROM','magic@sender.com']], ...`

`imap.search(['UNSEEN',['OR',['SUBJECT','subject1'],['OR',['SUBJECT','subject2'],['OR',['SUBJECT','subject3']]]],['FROM','magic@sender.com']], ... `

Any hint? Thanks for your help!

**Comment by mscdex** [comment]
@rptl The error is pretty clear, you're passing the wrong number of arguments. In the examples you've shown you're passing 3 in most cases.

To nest them, you need to do something like:

```js
[ 'OR',
  'foo',
  [ 'OR',
    'bar',
    [ 'OR',
      'baz',
      'quux' ]
  ]
]
```

**Comment by jeanbuzzello** [comment]
Just for show what's worked for me for combination between OR & AND, hope this help ...
imap.search(
        ['UNSEEN',
            ['SINCE', 'April 20, 2010'],
            ['OR',
                ['HEADER', 'SUBJECT', 'carga cartão'],
                ['HEADER', 'SUBJECT', 'CARGA CARTÕES']
            ]
        ])

**Comment by cantoute** [comment]
This kind of nested loops do my head in.

This seems to do the job:

```js
const filterFrom = ['@example.com', '@example2.com', '@example3.com'];
let result;

filterFrom.forEach((value, index) => {
  result = index
    ? ['OR', ['HEADER', 'FROM', value], result]
    : ['HEADER', 'FROM', value];
});

console.log('result', result);

/*
result [
  'OR',
  [ 'HEADER', 'FROM', '@example3.com' ],
  [
    'OR',
    [ 'HEADER', 'FROM', '@example2.com' ],
    [ 'HEADER', 'FROM', '@example.com' ]
  ]
]
*/
```

There is probably a more elegant way to do this and I'm more than happy to find out how :)

**Comment by fazrimo** [comment]
@mscdex  How to only search email if the TO is send to the filtered email address, not in the CC/BCC, example:
example1 -> to: mail1@mail.com & cc: mail2@mail.com (will not be processed)
example2 -> to: mail2@mail.com & cc: mail1@mail.com (will be processed)

Tried: 
`imap.search(
      ['UNSEEN', ['HEADER', 'TO', 'mail2@mail.com']],
      (err, results) => {
      // fetch email
 })`
 
 but the email on example1 still be processed
