### ISSUE TITLE
Don't throw error in async library functions

### ISSUE THREAD

**Issue by dbellavista** [mscdex/node-imap#572]
Hi!

I noticed that certain methods such as https://github.com/mscdex/node-imap/blob/3051724f85ac2efbf887d112c91f669919186897/lib/Connection.js#L560

throw an error using `throw new Error` if some preconditions are not met.
I suggest to invoke the callback (maybe using `process.nextTick`) with the error parameter set instead of forcing the user to try catch every single call.

Thanks!

**Comment by mscdex** [comment]
See: https://github.com/mscdex/node-imap/issues/479

**Comment by dbellavista** [comment]
Sorry, but I'm not convinced. Errors are thrown not only if parameter
validation fails but also depending on the context such as the current
connection or the server capabilities. While readFile always throws if the
encoding is wrong, the expunge function may throws if the server doesn't
support extend Uid or not. This is not acceptable when adopting the error
first callback convention.

**Comment by mscdex** [comment]
You can always check for server extension support ahead of time with `imap.serverSupports()`.
