### ISSUE TITLE
I cannot read emails from Outlook

### ISSUE THREAD

**Issue by alexandraperezbermejo** [mscdex/node-imap#582]
Hi!!
Since some months I'm trying to read emails from Outlook but I cannot, at first I could.

My imap configuration is:

var imap = new Imap({
        user: user,
        password: password,
        host: 'imap-mail.outlook.com',
        port: 993,
        tls: {
        secureProtocol: "TLSv1_method"
        },
        tlsOptions: {rejectUnauthorized: false}
    });

I don't know if it is something wrong there.

Thanks!!

**Comment by mscdex** [comment]
Two issues:

* `tls` should just be a boolean, so `true` in your case
* `tlsOptions` is where you place your `tls.connect()` options, so this is where your `secureProtocol: 'TLSv1_method'` should be if you absolutely need it.
* You should almost never use `rejectUnauthorized: false`, it ignores certificate check errors, which means you could be MITM'ed. Even for self-signed certificates you can add those via the `ca` option (although you can use LetsEncrypt certs for self-hosted IMAP servers, which would make things work out of the box).

**Comment by alexandraperezbermejo** [comment]
mscdex a lot of thanks!!! Now it works correctly :)
