### ISSUE TITLE
IDLE prevents closing connection

### ISSUE THREAD

**Issue by zyonnetworks** [mscdex/node-imap#583]
When I search using since... the connection never closes even when i call imap.close()
```
imap.search([ 'ALL', [ 'SINCE', 'December 5, 2016' ] ],
```
<= '+ idling'
 => DONE
<= 'IDLE OK Idle completed (0.001 + 0.095 + 0.094 secs).'

if i search using just ALL, it works fine
```
imap.search(['ALL'],
```

**Comment by mscdex** [comment]
Probably related: https://github.com/mscdex/node-imap/pull/573

**Comment by zyonnetworks** [comment]
Fixed! Tnx
