### ISSUE TITLE
Support for SEARCH/FETCH command (not UID)

### ISSUE THREAD

**Issue by dbellavista** [mscdex/node-imap#596]
Hi!
I'd like to propose support for plain `SEARCH` and `FETCH` command instead of the default `UID SEARCH` and `UID FETCH`. In some edge cases, the `UID` command is not feasible and the only way is to rely on sequence number.

Can it be done by using `_search` and `_fetch` methods?

**Comment by mscdex** [comment]
This is already possible using `imap.seq.search()` and `imap.seq.fetch()`.

**Comment by dbellavista** [comment]
Oh right thank you! Didn't notice it.
