### ISSUE TITLE
Parsing Emails In a Folder Other Than Inbox

### ISSUE THREAD

**Issue by rhsu0268** [mscdex/node-imap#600]
Hi, 

Is it possible to parse emails inside a certain folder that is different than the INBOX? I got two types of emails I want to parse and I want to send them to two different folders and parse with different functions since the structure is not the same?

**Comment by mscdex** [comment]
I'm not quite sure what you're asking. Are you talking about fetching emails and parsing the header and/or the content, or something else?

**Comment by rhsu0268** [comment]
I guess it'll work if I can set the search criteria. Is this the correct format?

    var searchCriteria = [
                'HEADER', 'SUBJECT', '<WHAT I WANT TO SEARCH FOR>'
            ];


It's not working for me...

**Comment by rhsu0268** [comment]
I left out the UNSEEN criteria. Got it working so I'm closing this. 

Thank you!
