### ISSUE TITLE
Non-plain text password schemes

### ISSUE THREAD

**Issue by jirevwe** [mscdex/node-imap#601]
Hi,

Is it possible to enable non-plain text authentication for this library.

From the source code :
```
/** Password for plain-text authentication. */
password: string;
```

I'm using STARTTLS already, but I'd like to use a more secure password scheme for authentication.

**Comment by mscdex** [comment]
There's already XOAUTH/XOAUTH2 support if the server supports it, but otherwise there is no other auth mechanism support currently.

**Comment by jirevwe** [comment]
Ouch...

I'm using self hosted mail server [iRedmail (Dovecot and PostFix)].
I don't think it does.

Sigh.

**Comment by mscdex** [comment]
FWIW Dovecot does support XOAUTH2, see the supported auth menchanism list here: http://wiki2.dovecot.org/Authentication/Mechanisms

If that's still not a viable option, then feel free to submit a PR to add support for one or more of the common auth methods. I think the hash-based ones would be candidates for this (with MD5-based mechanisms probably being the most prevalent, despite being weaker).

**Comment by jirevwe** [comment]
Thanks. I'll go through it.
