### ISSUE TITLE
Error with setKeywords method

### ISSUE THREAD

**Issue by Peuj** [mscdex/node-imap#602]
Hello,

I have an error with the setKeywords method using a simple command like this:

```
imap.setKeywords(uid, "test", (error) => {
	imap.end();

	if (error) {
		reject(error);
	}
	else {
		resolve();
	}
});
```
The mail with the specified uid exist and the keyword "test" exists has an Outlook category.
When I execute the command, I get the error "Command Argument Error. 11".

Here's the output log:
[connection] Connected to host
```
<= '* OK The Microsoft Exchange IMAP4 service is ready.'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
=> 'A1 LOGIN ******************************'
<= 'A1 OK LOGIN completed.'
=> 'A2 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT XPROXY3 CLIENTNETWORKPRESENCELOCATION CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A2 OK CAPABILITY completed.'
=> 'A3 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A3 OK NAMESPACE completed.'
=> 'A4 LIST "" ""'
<= '* LIST (\\Noselect \\HasChildren) "/" ""'
<= 'A4 OK LIST completed.'
=> 'A5 SELECT "INBOX"'
<= '* 2941 EXISTS'
<= '* 0 RECENT'
<= '* FLAGS (\\Seen \\Answered \\Flagged \\Deleted \\Draft $MDNSent)'
<= '* OK [PERMANENTFLAGS (\\Seen \\Answered \\Flagged \\Deleted \\Draft $MDNSent)] Permanent flags'
<= '* OK [UIDVALIDITY 14] UIDVALIDITY value'
<= '* OK [UIDNEXT 9740] The next unique identifier value'
<= 'A5 OK [READ-WRITE] SELECT completed.'

=> readOnly: false
=> newKeywords: false

.......
<= 'IDLE OK IDLE completed.'
=> 'A6 UID STORE 9682 FLAGS.SILENT (test)'
<= 'A6 BAD Command Argument Error. 11'
```

Is the problem related with some exchange server properties (like _newKeywords: false_) and so I don't have the rights to set a keyword?

Note: if I set manually the category "test" on my mail, I can see the information in the headers entries "keywords = test". This is why I suppose I need to use setKeywords to set a category.

Thanks

**Comment by mscdex** [comment]
> Is the problem related with some exchange server properties (like newKeywords: false) and so I don't have the rights to set a keyword?

Correct.

> Note: if I set manually the category "test" on my mail, I can see the information in the headers entries "keywords = test". This is why I suppose I need to use setKeywords to set a category.

I'm not sure what "manually setting the category" means here, but Exchange is only letting you set the explicit list of flags shown. Perhaps "category" means a separate mailbox, like how gmail uses a separate mailbox for each of their "labels?"

**Comment by Peuj** [comment]
Thanks for the supprt!
