### ISSUE TITLE
maximum number of connections from user+ip exceeded (mail_max_userip_connections=16)

### ISSUE THREAD

**Issue by sunil-daffodil** [mscdex/node-imap#606]
When imap is connecting  (maximum number of connections from user+ip exceeded (mail_max_userip_connections=16)) error is coming

connection] Connected to host
<= '* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=TOKEN] Server ready proxy6.mail.iad3a.rsapps.net'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=TOKEN'
<= 'A0 OK Pre-login capabilities listed, post-login capabilities have more.'
=> 'A1 LOGIN "xyz" "yyy"'
<= 'A1 NO [UNAVAILABLE] Maximum number of connections from user+IP exceeded (mail_max_userip_connections=16)'

**Comment by jirevwe** [comment]
What mail server are you running?

I had this problem a while ago when testing my client.
I think it happens when you try to access the same IMAP account with different clients. I was actually using three browsers to access one IMAP account.

```
If you use iRedMail you could  go into /etc/dovecot/dovecot.conf and find the section
# IMAP configuration
protocol imap {
    #mail_plugins = quota imap_quota zlib expire
    mail_plugins = quota imap_quota zlib

    # number of connections per-user per-IP
    #mail_max_userip_connections = 10
}
```
ad just increase the number of connections, but I don't think it's needed.

**Comment by sunil-daffodil** [comment]
mail server :- secure.emailsrvr.com  
and where to change the config of imap protocol of this server

**Comment by mscdex** [comment]
I don't think there is anything this module can do about this error other than report it back to the user.

**Comment by ftoledo** [comment]
can be specific the ip address ? to set the max connections for these ip only?

**Comment by working-name** [comment]
This is more about node-imap and less about the server. It doesn't close connections on errors (see #520 for example). For example if `.fetch(...)` doesn't return any results it will error out but not close the connection. You can also call `.end()` manually, it doesn't matter. Quite a peculiar choice to default to an error when .fetch doesn't find what you send it to. Anyway, this is so unmaintained it's scary.

**Comment by vasu-rangpariya-yudiz** [comment]
Still facing the same error any way to  prevent  this error?
