### ISSUE TITLE
Invalid Messageset

### ISSUE THREAD

**Issue by popey456963** [mscdex/node-imap#608]
Looked over the previous issue on this topic, #410, saw that it worked when they replaced "1:3" with "*", thought I'd try the same.  Still got the same issue.  When grabbing a few mailboxes, such as:

 - INBOX.Trash.Business
 - INBOX.Archive

I get the following error returned to me from IMAP:

    Error in IMAP command FETCH: Invalid messageset (0.000 + 0.000 secs).

The log can be found here - https://hastebin.com/afitagiyer.tex -  The fetch statement looks as follows, where in this case lowestSeq is undefined, leading to the statement being '*' (confirmed by the logs, `A12 FETCH * (MODSEQ UID...`):

    let f = client.seq.fetch(`${lowestSeq ? `${lowestSeq}:` : ``}*`, {
      bodies: 'HEADER.FIELDS (TO FROM SUBJECT)',
      struct: false,
      envelope: false
    })

**Comment by mscdex** [comment]
The reason for the error is that '*' does not work for empty mailboxes. [According to RFC 3501](https://tools.ietf.org/html/rfc3501#page-90):

<blockquote>
* represents the largest number in use.  In the case of message sequence numbers,
it is the number of messages in a non-empty mailbox. In the case of unique
identifiers, it is the unique identifier of the last message in the mailbox or,
if the mailbox is empty, the mailbox's current UIDNEXT value. The server should
respond with a tagged BAD response to a command that uses a message sequence
number greater than the number of messages in the selected mailbox.  This
includes "*" if the selected mailbox is empty.
</blockquote>

**Comment by popey456963** [comment]
Thanks for the prompt reply @mscdex, do you know of a way to query for an empty mailbox?  Or can we just assume that if this error occurs that the box is empty?

**Comment by mscdex** [comment]
Not offhand, no. It might be better to simply check the number of mailbox messages first? This count is available on the mailbox object passed to the `openBox()` callback.

**Comment by popey456963** [comment]
@mscdex Oh, excellent point!  We get the number of messages from there.  Thanks.
