### ISSUE TITLE
Connection is not ending in using imap.end() on lenode server

### ISSUE THREAD

**Issue by sunil-daffodil** [mscdex/node-imap#610]
On local connection of  email id of host secure.emailsrvr.com  is ending on imap.end() but on live lenode server connection is not ending for this email while connection of gmail id  is ending on imap.end

**Comment by mscdex** [comment]
Can you set `debug: console.log` in your connection config and post the resulting output (removing/censoring username and password in the output)?

**Comment by sunil-daffodil** [comment]
Issue has been resolved.node version on lenode was 0.10 and after changing to v6.9.5 it is working fine.
