### ISSUE TITLE
Can't connect with xoauth2 token

### ISSUE THREAD

**Issue by spyeadon** [mscdex/node-imap#614]
After authenticating a user using oAuth with the google strategy, I have an access token which im passing into my node imap instance like so: 

const imap = new Imap({
    **xoauth2: xoauth2,**
    host: 'imap.gmail.com',
    port: 993,
    tls: true
});

When imap.connect() is invoked (I have an event handler set for the imap.once('ready', callback) event), the following error is logged in my server console.

Error: Invalid SASL argument. o8nb531754059oih <-- (different alphanumeric sequence every time)

Do I need a refresh token instead of an access token? Is my access token formatted incorrectly? My authentication with google was a success, so it seems like it just has to do with the information im passing to the imap instance being wrong and/or formatted incorrectly.

**Comment by spyeadon** [comment]
To clarify, I am NOT using the xoauth2 generator module recommended, just the raw access token I receive from google. To use that module it requires a refresh token which I am not receiving in my oauth callback function which gives me access to the following parameters: 
(accessToken, refreshToken, profile, done) 

refreshToken is undefined, tho I have access to profile and accessToken.

**Comment by mscdex** [comment]
You need to pass the base64-encoded form as described in the [google documentation](https://developers.google.com/gmail/imap/xoauth2-protocol#the_sasl_xoauth2_mechanism).

**Comment by spyeadon** [comment]
I have now passed in the token generated by [xoauth2](https://github.com/andris9/xoauth2) library, which as I understand it **is** formatted for the SASL mechanism. I managed to get the required refresh token to pass into the xoauth generator. The value generated is assigned to 'token' in the example below. When imap.connect() is invoked, the console prints out: 

Error: Invalid credentials (Failure)

Is there something obvious that I am missing in my imap configuration options? I was hoping that with the xoauth2 token, I would not have to include my email or password, since those were included in generating the refresh token/SASL formatted token before this.

const imap = new Imap({
      xoauth2: token,
      host: 'imap.gmail.com',
      port: 993,
      tls: true
});

**Comment by mscdex** [comment]
To be honest, I don't really have a lot of experience with as I added the feature based on a request by someone else.

**Comment by spyeadon** [comment]
I was able to connect by changing some of the imap configuration options, namely switching 'tls: true' to 'ssl: true' after reading that gmail uses [SSL for Imap but TSL for SMTP](https://developers.google.com/gmail/imap/imap-smtp). After invoking imap.connect() with the below options the console prints out that I established a connection, however, judging by the lack of output, none of the on connect events are triggered. Then, after 10 seconds I'm prompted that my connection has ended. Can you point me in the direction of some solution or just an indication of what the problem could be?

    const imap = new Imap({
      xoauth2: b64Token,
      host: 'imap.gmail.com',
      port: 993,
      ssl: true,
      debug: console.log,
      authTimeout: 30000,
      connTimeout: 30000
    });

**Comment by mscdex** [comment]
There is no `ssl` option, it's only `tls`.

**Comment by spyeadon** [comment]
You're correct, thank you. After change ssl to tsl, I am still getting the same lack of output after establishing  a connection, as if my imap.once('ready', callback) event is not triggering.

**Comment by mscdex** [comment]
@spyeadon Did you find the cause of the problem you were having?

**Comment by spyeadon** [comment]
No :(

**Comment by zorow** [comment]
> I was able to connect by changing some of the imap configuration options, namely switching 'tls: true' to 'ssl: true' after reading that gmail uses [SSL for Imap but TSL for SMTP](https://developers.google.com/gmail/imap/imap-smtp). After invoking imap.connect() with the below options the console prints out that I established a connection, however, judging by the lack of output, none of the on connect events are triggered. Then, after 10 seconds I'm prompted that my connection has ended. Can you point me in the direction of some solution or just an indication of what the problem could be?
> 
> ```
> const imap = new Imap({
>   xoauth2: b64Token,
>   host: 'imap.gmail.com',
>   port: 993,
>   ssl: true,
>   debug: console.log,
>   authTimeout: 30000,
>   connTimeout: 30000
> });
> ```

This answer saved me thannks
