### ISSUE TITLE
Original Gmail message is encripted

### ISSUE THREAD

**Issue by hadeskun** [mscdex/node-imap#616]
Hi,

When I try to recover a Gmail message with the following structure:
 imap.search([ 'UNSEEN' ,['BODY', order_id  ]], function(err, results) 
Not result is returned and I imagine could be that the message is encrypted.
Any help, please?

**Comment by mk-pmb** [comment]
If the message were encrypted, you should at least see garbage data as the message content. If you don't get any `results`, it's probably either an error (check `err`) or a control flow issue.

**Comment by hadeskun** [comment]
I noticed that the problem is something with my gmail account sorry.
