### ISSUE TITLE
Node.js 7/8 Segfault when using TLS

### ISSUE THREAD

**Issue by mofux** [mscdex/node-imap#617]
I am getting segmentation faults every few minutes when using your library to connect to an imap server (dovecot). I've tried to isolate the problem using the segfault-handler module, it came up with this trace:

```
PID 9000 received SIGSEGV for address: 0x0
/apps/myapp/segfault-handler/build/Release/segfault-handler.node(+0x1b14)[0x7efc7049ab14]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7efc72a79330]
node(_ZN4node7TLSWrap6EncOutEv+0x2e5)[0x13587c5]
node(_ZN4node7TLSWrap10OnReadImplElPK8uv_buf_t14uv_handle_typePv+0xb6)[0x1359696]
node(_ZN4node8JSStream10ReadBufferERKN2v820FunctionCallbackInfoINS1_5ValueEEE+0x10d)[0x12c2c0d]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x141)[0xac6421
]
node[0xb4909c]
```

After disabling TLS for the imap connection it did no longer crash.
The app creates like 20 imap connections in sequence (open connection, scan box, close connection) within 2 or 3 seconds overall time, which probably results in a heavy load.

My code relies on async/await, so I couldn't test on node 6, but node 7 and 8 are both crashing with a segfault.

If you're willing to dig deeper, I can try to create a small example app that works against my server to reproduce the problem.

**Comment by mscdex** [comment]
This should be reported to node's issue tracker instead of here since the crash is occurring from within node's internals and this module does not use any native code.

**Comment by mofux** [comment]
Thanks, I think it might be related to https://github.com/nodejs/node/issues/8074
