### ISSUE TITLE
Date format for SINCE

### ISSUE THREAD

**Issue by mk-pmb** [mscdex/node-imap#620]
The readme gives an example for SINCE date as `April 20, 2010`. However, as I understand the [ABNF definition of "date" in rfc3501](https://tools.ietf.org/html/rfc3501#section-9), it should rather be `20-Apr-2010`, for which I even know an easy way to render it:

```javascript
(new Date(2014, 3, 20, 12)).toGMTString().split(/ /).slice(1, 4).join('-')
// 12 = noon: should accomodate most timezones
```

* Have I missed something in the RFC?
* Does the IMAP module convert the date format?
* Are IMAP servers required to accept the date format used in the Readme?

**Comment by mscdex** [comment]
`imap` converts the date for you if you don't pass a `Date` object for date-related search criteria.

**Comment by mk-pmb** [comment]
Thanks! :+1:
