### ISSUE TITLE
GMAIL Security: Less Secure

### ISSUE THREAD

**Issue by McJug** [mscdex/node-imap#623]
Hi,

I've set up a basic example and tried to connect it to my GMail but it gave me an error connecting. I could only get it to work by going into my Google account and enabling "Less Secure Apps". Am I using this wrong or does the library need updating? (Sorry I'm new to anything IMap it could be a stupid question). 

Thanks,

**Comment by surajwy** [comment]
Gmail does not promote accessing its IMAP services by using plain username and password. 
You should first get OAuth2.0 credentials ([here](https://developers.google.com/gmail/api/quickstart/nodejs)) and then should convert it to xoauth2 (using [this](https://github.com/andris9/xoauth2)).
Once you have that, then you can pass it as params to Imap constructor. Refer [this](https://github.com/mscdex/node-imap#connection-instance-methods).

Regards,
Suraj

**Comment by McJug** [comment]
Thanks Suraj,

Great explanation - thanks for taking the time!

Regards,

**Comment by bijoythomas** [comment]
@surajwy and @McJug I ran into the same issue and followed your instructions but I am always getting `A1 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)` error.

My code looks like
```
let {installed: {client_id, client_secret}} = require('./client_secret') // the client_secret.json file
let xoauth2gen = xoauth2.createXOAuth2Generator({
  user: '*******', // the email address
  clientId: client_id,
  clientSecret: client_secret,
  refreshToken: refresh_token
 })

xoauth2gen.getToken(function(err, xoauth2token) {
  if (err) {
    return console.log(err)
  }
        
  let imap = new Imap(log, {
     xoauth2: xoauth2token,
     host: 'imap.gmail.com',
     port: 993,
     tls: true,
     authTimeout: 10000,
     debug: console.log,
 })
```

and the output I get is

```
[connection] Connected to host
<= '* OK Gimap ready for requests from 108.66.236.53 t4mb119120134obs'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH'
<= 'A0 OK Thats all she wrote! t4mb119120134obs'
=> 'A1 AUTHENTICATE XOAUTH2 {xoauth2token}'
<= '+ eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ=='
=> '\r\n'
<= 'A1 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)'
```

I'm pretty sure the xoauth2token is correct because `Buffer.from(xoauth2token, 'base64').toString()` shows me the string in the format 
`user={myemailaddress}auth=Bearer {sometoken}`

Not sure what I am doing wrong. Any help will be appreciated

**Comment by bijoythomas** [comment]
Maybe it might have something to do with the fact that this account is part of GSuite and perhaps requires a service account config instead of OAUTH2. I'll try it out

**Comment by fhackenb** [comment]
@bijoythomas did you ever figure this out? I'm getting the same error

**Comment by fhackenb** [comment]
For anyone else who may get this error - my problem was a missing scope. Refer to: https://stackoverflow.com/questions/17700114/oauth-2-sasl-string-error
