### ISSUE TITLE
Authentication 2

### ISSUE THREAD

**Issue by jackel27** [mscdex/node-imap#625]
Not really an issue, everything looks great so far. Appreciate the hard work on this. I was just curious on how to manually set up the connection myself. I am currently working with Electron and would like to use this in it, except for the fact that I need to do an oAuth2 verification through Electron's Browser Window. I could take the token and pass into this, but not sure exactly how to go about it within node-imap. Not looking for deep specifics just general direction. Thanks

Also, using Gmail*

**Comment by mscdex** [comment]
If you already have the access token, then you just need the proper format as shown in the 'Initial Client Response' section [here](https://developers.google.com/gmail/imap/xoauth2-protocol#the_sasl_xoauth2_mechanism). If you don't already have an access token, you can use the `xoauth2` module on npm to generate a formatted token on the fly.

After that, pass the formatted token as the `xoauth2` property in the `imap` connection config object.

**Comment by jackel27** [comment]
Exactly what I was looking for! Thanks!

**Comment by jackel27** [comment]
Works like a charm with Electron. No issues on the setup.
