### ISSUE TITLE
Duplicates?

### ISSUE THREAD

**Issue by jackel27** [mscdex/node-imap#626]
Hello again!
Been messing around with this all night. I love the fact it supports Google Extensions! Starred and Followed. On to my issue....

I am not sure if I am handling the stream correctly or if something else is going on. I am returning duplicate messages. I believe this is correct because they have the same ``` 'x-gm-msgid' ``` .  I am not sure what I am doing wrong here. I've read the docs on this, it seems like I am doing things correctly?

``` javascript
export function search (query) {
  imap = new Imap({
    xoauth2: window.btoa(`user=${store.state.User.email}\x01auth=Bearer ${store.state.User.token}\x01\x01`),
    host: 'imap.gmail.com',
    port: 993,
    tls: true
  })
  let attributes = null
  imap.once('ready', () => {
    openInbox((err, box) => {
      if (err) throw err
      imap.seq.search([ ['X-GM-RAW', query] ], (err, results) => {
        let buffer = ''
        let msgobj = {}
        if (err) throw err
        var f = imap.seq.fetch(results, { bodies: '' })
        f.on('message', (msg, seqno) => {
          var prefix = '(#' + seqno + ') '
          msg.on('body', (stream, info) => {
            stream.on('data', (chunk) => {
              buffer += chunk.toString('utf8')
            })
            stream.on('end', () => {
              console.log(prefix + 'Finished')
            })
            stream.once('end', () => {
            })
          })
          msg.on('attributes', (attrs) => {
            attributes = attrs['x-gm-msgid']
            console.log(attributes)
          })
          msg.on('end', () => {
            console.log('message done ')
          })
          msg.once('attributes', (attrs) => {
            // console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8))
          })
          msg.once('end', () => {
            simpleParser(buffer, (err, mail) => {
              if (err) console.log(err)
              msgobj = {
                id: attributes,
                from: mail.from.text,
                date: mail.date,
                subject: mail.subject,
                body: mail.html
              }
              console.log('BODY===>', mail.html) 
              saveMessage(msgobj)
            })
          })
        })
        f.once('error', (err) => {
          console.log('Fetch error: ' + err)
        })
        f.once('end', () => {
          console.log('Done fetching all messages!')
          imap.end()
        })
      })
    })
  })
  imap.once('error', (err) => {
    console.log(err)
  })
  imap.once('end', () => {
    console.log('Connection ended')
  })
  imap.connect()
}
```

**Comment by mscdex** [comment]
I think the main issue is that some variables are not in the proper scope. Specifically the definitions and initializations for `attributes`, `buffer`, and `msgobj` should all be placed right inside the `f.on('message', (msg, seqno) => {` handler.

Also I should point out that while proper email bodies will have non-ASCII characters encoded, email bodies *might* contain multi-byte characters. So doing `buffer += chunk.toString('utf8')` could do the wrong thing if a chunk ends on a split multi-byte character. It'll be safer to just have `buffer` be initialized to an empty array and push the `chunk`s to that. Keep a running total of all `chunk.length` and then pass the `buffer` and length variable to `Buffer.concat()` at the end of the stream and you will have one giant Buffer you can `.toString()`.

**Comment by jackel27** [comment]
Thanks for the quick, and always thorough reply. I will get to this now and share my results. I was beginning to think it was the email-parser.

**Comment by jackel27** [comment]
Oh wow. Yeah. It was a scoping issue for the initialization. I understand the flow of the request better now. doh... 
Thanks for the additional tip on the multi-byte characters! good catch! Excited to get this going with Electron. If I decide to finish this, is there a section to submit projects that use this? Thanks again, that resolved my issue.

**Comment by mscdex** [comment]
Glad to hear you got it working.

> If I decide to finish this, is there a section to submit projects that use this?

I generally don't add such lists to the readme/wiki/etc. for my projects because they're something that has to be maintained and I don't have the time to keep those lists current.

Good luck with your project though!
