### ISSUE TITLE
Cannot connect to Imap in mongoose find callback

### ISSUE THREAD

**Issue by maciejszpyra** [mscdex/node-imap#632]
I'm having problem with connecting to Imap inside a find callback. I'm trying to connect like this:

    mongoose.connect(env.mongo.host, {useMongoClient: true});
    
    User.find((err, users) => {
        if (err) return console.error(err);
        if (users) {
            const connections = [];
            users.forEach((user) => {
                connections.push(
                    imapConnectionFactory(user.username, user.password)
                )
            });
            connections.map((connection) => {
                connection.once('ready', () => console.log('connected'))
                connection.connect();
            })
        }
    });
but I keep getting 

> Authentication failed.

error. When I'm trying to connect outside find callback everything works fine.

    const users = [{username: 'correct_username', password: 'correct_password'}];
    const connections = [];
    users.forEach((user) => {
        connections.push(
            imapConnectionFactory(user.username, user.password)
        )
    });
    connections.map((connection) => {
        connection.once('ready', () => console.log('connected'))
        connection.connect();
    });

What I need is to get users from mongo, connect to thiers boxes and fetch emails. Why this isn't working and how to make this work?

**Comment by mscdex** [comment]
Assuming `user` has the expected properties, you might be better off asking on stackoverflow.com or [nodejs/help](https://github.com/nodejs/help/issues) since I am not very familiar with the mongoose/mongodb API.
