### ISSUE TITLE
GMail blocking signin attemtps

### ISSUE THREAD

**Issue by bijoythomas** [mscdex/node-imap#633]
Hello,

  I was using the node-imap lib without any issues until suddenly I started getting the error `{"type":"no","textCode":"ALERT","source":"authentication"}` and when I looked at my inbox through the browser, I saw an email from GMail asking to "Review blocked sign-in attempt". My Imap connection object looks like
`{
  user: *****,
  password: ******,
  host: 'imap.gmail.com',
  port: 993,
  tls: true
}`

Is there some other security configuration that will allow login attempts?

**Comment by bijoythomas** [comment]
I somehow missed this [post](https://github.com/mscdex/node-imap/issues/623). Will try it out.

**Comment by CodeOtter** [comment]
Does every way to read Gmail (pop3, impa, or the official API) require OAuth? 

How are daemons/cron jobs supposed to read messages in gmail?

**Comment by mscdex** [comment]
@CodeOtter You can programmatically obtain tokens using a module like `xoauth2`, you just have to provide some static values.

I cannot speak for POP3 or the gmail web API.

**Comment by CodeOtter** [comment]
Thanks for the prompt response.  I saw the BountySource on #614 regarding xoauth2, but I did not see a solution.  Are there any valid documents on how to set this up for a Gmail account?

**Comment by mscdex** [comment]
@CodeOtter `xoauth2` pretty much does everything for you, but if you want to look at how to do it manually, there is [Google's oauth2 guide for IMAP](https://developers.google.com/gmail/imap/xoauth2-protocol).

**Comment by CodeOtter** [comment]
Turns out your documentation in the `README.cd` works great.  My problem was I was using `imap-simple`, which doesn't work, which lead me to here, which does work.

Thanks again :D
