### ISSUE TITLE
Seq Fetch order

### ISSUE THREAD

**Issue by johnbaird4085** [mscdex/node-imap#634]
If I fetch for example 100:200 it will process starting with 100. I thought if I changed it too 200:100 it would start with 200. It doesn't it starts with 100. I am trying to avoid any extra computing, as prepend is more expensive than append. Is this a limitation of Imap in general or just the order this library uses?

**Comment by mscdex** [comment]
As far as the range syntax goes, those two example ranges are equivalent:

> seq-range       = seq-number ":" seq-number
                    ; two seq-number values and all values between
                    ; these two regardless of order.
                    ; Example: 2:4 and 4:2 are equivalent and indicate
                    ; values 2, 3, and 4.

**Comment by johnbaird4085** [comment]
Sigh...The Imap protocol continues to disappoint. Sort algorithm it is then. I'll try to not open anymore cases. Node-imap is extremely useful so far. 

Unrelated: I noticed some cases about "user connect but not authenticated" and how its an exchange bug. I can't speak for the exchange part but using hotmail this will happen if too many users are connected at once. Basically instead of disconnecting them it just logs them out so to speak. Just an FYI for ya.

**Comment by mscdex** [comment]
The other option would be to fetch each message individually.... but that might be subject to race conditions if a message gets deleted while fetching the messages. I'm not sure if that would affect using a range too, but at least it may give the server implementation an opportunity to "lock" those messages up front since it knows you're interested in those messages.

**Comment by johnbaird4085** [comment]
Yeah the problem was more my design when I looked at it again. I was adding one message at a time to an array and then sorting that in a reactive property thats used for realtime display. Naturally, if you have multiple connections returning messages at the same time or just a lot of messages already downloaded, resorting on every new message is very expensive and makes the GUI sluggish. I'll just do it right and do bulk inserts and prevent sorting folders that are not currently open in the interface.
