### ISSUE TITLE
Deleting mails 

### ISSUE THREAD

**Issue by c-schwartz** [mscdex/node-imap#635]
function cleanBox() {
        return new Promise(function(resolve, reject) {

            var imap = new Imap({
                user: '********.*******@free.fr',
                password: '*********',
                host: 'imap.free.fr',
                port: 993,
                tls: true
            })

            function openInbox(cb) {
                imap.openBox('INBOX', true, cb);
            }

            imap.once('ready', function() {
                openInbox(function(err, box) {
                    if (err) throw err;
                    var f = imap.seq.fetch('1:2000', {
                        bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
                        struct: true
                    });
                    f.on('message', function(msg, seqno) {
                        imap.addFlags(seqno, 'Deleted', function(err) {
                            if (err) return cb(err);
                        });
                    });
                    f.once('error', function(err) {
                        console.log('Fetch error: ' + err);
                    });
                    f.once('end', function() {
                        console.log('Done fetching all messages!');
                        imap.closeBox(true, function(err) {
                            if (err) return cb(err);
                            imap.end();
                        });
                    });
                });
            });

            imap.once('error', function(err) {
                console.log(err);
                return reject(err)
            });

            imap.once('end', function() {
                console.log('Connection ended')
                return resolve()
            });

            imap.connect();

        })
    }

Hello guys,
I am trying to delete some emails from my box.

I'm not getting any errors with this code but nothing is happening, could you tell me if you see something wrong with the code, or how I could try to debug ?
Thanks

**Comment by mscdex** [comment]
The second argument to `imap.openBox()` is a read-only mode flag. Pass in `false` to open in read-write mode.

**Comment by c-schwartz** [comment]
Thanks
