### ISSUE TITLE
addFlags progress

### ISSUE THREAD

**Issue by ybouhjira** [mscdex/node-imap#637]
Is there a way to get the progress of `addFlags` method? I tried listening on update event but it's shows nothing.

EDIT: It also doesn't delete all messages when dealing with large mailbox (229882 messages), is there a solutions for this?

```js
const Imap = require('imap');

const imap = new Imap({
    user: 'xxxxxxxx@yahoo.com',
    password: 'xxxxxxxxx',
    host: 'imap.mail.yahoo.com',
    port: 993,
    tls: true
});

imap.connect();

imap.on('ready', () => {
    console.log('Client ready');
    imap.openBox('INBOX', false, (err, box) => {
        if (err) error(err);
        console.log(`INBOX open (${box.messages.total})`);
        imap.seq.addFlags('1:*', 'Deleted', err => {
            if (err) error(err);
            console.log('Flags added');
            imap.expunge('1:*', err => {
                if (err) error(err);
                console.log('Expunge done');
                imap.closeBox(false, err => {
                    if (err) error(err);
                    console.log('Box closed');
                    imap.end();
                    console.log('The end');
                });
            })
        });
    });
});

imap.on('update', (seqno, info) => {
    console.log('update ' + seqno);
})

function error(err) {
    console.log('Error: ' + err.message);
    process.exit(1);
}
```

**Comment by mscdex** [comment]
Some things to note:

* `expunge()` only works on UIDs, even if it did have a `seq.expunge()` counterpart, there could be a race condition if new messages arrive between the completion of the `addFlags()` and the `expunge()` request.
* If you're closing the mailbox anyway, why not simply do an implicit expunge by passing `true` instead of `false` to `closeBox()`?
* When deleting messages, you might try listening for the `'expunge'` event instead of `'update'`.

**Comment by ybouhjira** [comment]
How to run expunge on all the messages using UIDS? Is there something like '1:*'?
I didn't use the implicit expunge because it gives me an error

**Comment by mscdex** [comment]
Actually, I forgot to mention the uids parameter is optional and only available when the server supports UIDPLUS. If you just call `expunge()` with just a callback it will expunge all messages marked as deleted.

As far as the implicit expunge via `closeBox()` goes, what error are you receiving?

**Comment by ybouhjira** [comment]
"CLOSE Command is not valid in this state" and sometimes "CLOSE server error"

**Comment by ybouhjira** [comment]
```
Client ready
INBOX open (167515)
Flags added
Error: CLOSE Server error - Please try again later
{ Error: CLOSE Server error - Please try again later
    at Connection._resTagged (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/youssef/Desktop/teeeeest/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7) type: 'no', textCode: 'SERVERBUG', source: 'protocol' }

```

**Comment by mscdex** [comment]
As the `textCode` shows, this is some bug in their implementation. There's not much this module can do about that.

Did the `expunge()` with only a callback work better?

**Comment by ybouhjira** [comment]
It deletes only a portion of the messages not all of them

**Comment by mscdex** [comment]
I don't know then, perhaps more server issues. Do repeated expunges finally clear out all of the deleted messages? Did you check if all messages actually got marked as Deleted (perhaps the server did not mark all of them for some reason and that is why they did not get expunged)?

**Comment by ybouhjira** [comment]
How do I check the deleted tags, using fetch?

**Comment by mscdex** [comment]
You can just do a simple `.search()` for messages with deleted flags set:

```js
imap.search([ 'DELETED' ], (err, results) => {
  if (err) throw err;
  console.log(results.length + ' messages still marked for deletion');
});
```

**Comment by ybouhjira** [comment]
All messages were marked for deletion

**Comment by ybouhjira** [comment]
How can I get the number of remaining messages without closing and reopening the mailbox

**Comment by mscdex** [comment]
If you mean how many messages aren't flagged as Deleted, then you can simply just negate the criteria:

```js
imap.search([ '!DELETED' ], (err, results) => {
  if (err) throw err;
  console.log(results.length + ' messages not marked for deletion');
});
```

**Comment by mscdex** [comment]
So perhaps the server has issues with deleting large amounts of messages at a time.... what about expunging them in chunks of some size (trial and error), does that work?

**Comment by ybouhjira** [comment]
I'll try restarting expunge each time it ends without deleting all messages. 
Is there a way I could get the progress of `addFlags` though ?

**Comment by mscdex** [comment]
The most you will get are `'expunge'` events on the imap connection object. You *should* see one for each message that was expunged.

**Comment by ybouhjira** [comment]
But the expunge event is occurs only after I call expunge. I want to display the progress with it's adding the Deleted flags because it case some time.

**Comment by ybouhjira** [comment]
I want to check if the box is empty but this is too slow
```
imap.search(['ALL'], (err, results) => {
  imap.end();
    if (err || results.length != 0)
           o.onError(new Error(`not empty : total:${results.length}, ${account.email}`)); 
});
```

**Comment by mscdex** [comment]
For flag modifications, currently we enforce a silent option that prevents flag updates from the server.

For checking for a non-empty mailbox, there are a variety of different methods to choose from:

* Check `mailbox.total` (`mailbox` being the object passed to `openBox()` callbacks), it should update as needed, but I'm not sure offhand about after an expunge
* Do `.status()` on an *unopened* mailbox, the callback is given a similar mailbox object as with `openBox()`
* Doing something like `imap.seq.fetch('1')`
* If the server supports the ESEARCH extension, you can do `imap.esearch(['ALL'], ['COUNT'], (err, info) => {})`
* If the server supports the QUOTA extension, you could use `imap.getQuotaRoot()` and then `imap.getQuota()` to get usage information for a mailbox

**Comment by ybouhjira** [comment]
It appears that problem is from Yahoo. I ended up making the script restart each time in finishes without deleting all the messages. Thanks a lot for your help.
