### ISSUE TITLE
 Server does not support that threading algorithm

### ISSUE THREAD

**Issue by mohamedmohsin** [mscdex/node-imap#644]
hi @mscdex    i want use threading extension , but it shows error while using both 'references', 'orderedsubject' ,  if these algorithms not support ,then how to get algorithm supported by my server

 imap.thread('orderedsubject',[['SUBJECT','1234']],function(err,uids){
		   if(err)
			   console.log(err);
		   else
			   console.log(uids);
	   });

**Comment by mscdex** [comment]
Not all servers support all extensions. You can check for any extension support by calling `imap.serverSupports(name)` where `name` is an uppercase string containing an extension name (e.g. `imap.serverSupports('THREAD=ORDEREDSUBJECT')`).

**Comment by mohamedmohsin** [comment]
Thanks @mscdex
