### ISSUE TITLE
Get mail uid on deleted mails

### ISSUE THREAD

**Issue by PertapaCode** [mscdex/node-imap#649]
Hi,

It's possible to get the mail uid when a mail is expunged externally?
Maybe using a search on the expunge event?

I was trying something like:

`.on('expunge', (seqno) => {
  imap.search([['DELETED', seqno]], function(err, results) {
    console.log(err, results);
  });
})`

but since the mail has been already deleted I receive a empty array in the results.

The reason I ask this, is to keep a database in sync with imap, if is not possible to get the uid when a mail is deleted the solution is to keep track of the seqno and compare local sequence numbers with imap, or there is better solution to implement this?

**Comment by mscdex** [comment]
It's not possible without QRESYNC support, which this module currently does not have yet.

**Comment by PertapaCode** [comment]
I understand now. TK
