### ISSUE TITLE
how do i parse date of an email with current user's timezone?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#651]
Hi developers,

when i use yahoo account to reply to me. Seem that content of an emails are shown as yahoo's timezone. It is not my timezone. How do i parse the email with  Bern Timezone (5:58 am). 

```
<div dir="ltr"><font size="2" face="Arial"> On 10:53 Firday, 13rd Oct 2017, Albert Enstein &lt;vinhtest1@123flo.com&gt; wrote:<br></font></div>  <br><br> <div class="y_msg_container"><div id="yiv8594862566"><div>Test replied bern timezone.</div>
```

Thanks.

**Comment by mscdex** [comment]
Parsing (especially semantically) the content of emails is outside the scope of this project. IMAP provides direct access to email timestamp(s), so if you can, use those instead.

**Comment by quangvinh1305** [comment]
@mscdex Thanks.
