### ISSUE TITLE
IMAP state is authenticated unless it stopped receiving email

### ISSUE THREAD

**Issue by pavelsc** [mscdex/node-imap#652]
I use the following options to connect to server (office365 if this is significant)

    self.imap = new Imap({
        user: self.parent.cfg['email']['imap_user'],
        password: self.parent.cfg['email']['imap_password'],
        host: self.parent.cfg['email']['imap_host'],
        port: self.parent.cfg['email']['imap_port'],
        tls: true,
        keepalive: {
            interval: 10000,
            idleInterval: 300000,
            forceNoop: true
        }
    });`

IMAP stops receiving emails and when I check self.imap.state via websockets it returns _authenticated_ value. Latest email was received about 30 minutes ago until I noticed that receiving failed. No error or end events weren't fired, it just silently stopped. This occurs every single day. 
Any simple workaround would be appreciated

**Comment by mscdex** [comment]
You can set `debug: console.log` to see what's going on behind the scenes to verify that NOOPs are being sent and responded to.

**Comment by pavelsc** [comment]
It looks like a bunch of noop commands, with no reaction to incoming emails.

    => 'NOOP NOOP'
    <= 'NOOP OK NOOP completed.'
    => 'NOOP NOOP'
    <= 'NOOP OK NOOP completed.'
    => 'NOOP NOOP'
    <= 'NOOP OK NOOP completed.'

**Comment by mscdex** [comment]
You could try disabling `forceNoop`, but it seems the server isn't sending the mail notifications if all you see are the NOOP requests and responses when you know email has been received.

If you have other email clients connected at the same time, try disconnecting the others and try again. The IMAP spec itself is designed to handle concurrent clients, but it could be the server implementation that is buggy.
