### ISSUE TITLE
Update draft mail while composing an email?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#654]
Hello developers,

I have an issue when i compose a new email. I want to auto save the email i am composing. 
I used an interval to save the email include(body, subject, cc, bcc).
how can i just update the content(body, subject, cc, bcc, to) of that email in draft folder every 30 seconds.

Thanks you,
Vinh

**Comment by jeffreyroshan** [comment]
- Connect to the drafts mailbox and use the **append** method to save the email to drafts.

- For updating a draft, you can simply create a new draft and delete the old draft by marking the message as "Deleted" (**addFlags**) and use the **expunge** method to delete it.
