### ISSUE TITLE
Timeout on connect

### ISSUE THREAD

**Issue by francisco4challenge** [mscdex/node-imap#655]
Hey! I was trying to promisify the connection, to make everything look cleaner, but i get many times a Error: Timed out while authenticating with server.
This even happens without the promises... Am i doing something wrong?
Node V: 8.6.0
imap V: 0.8.19

```js
const emailOptions: any = getConfigs('test.env').email;
    const imap = new Imap({
        user: emailOptions.auth.user,
        password: emailOptions.auth.pass,
        host: emailOptions.imapHost, /*'imap-mail.outlook.com',*/
        port: emailOptions.imapPort,
        tls: true,
        authTimeout: 10000
    });
    imap.connect();
    imap.once('error', function (err: any) {
        console.log('Err: ' + err);
    });
    imap.once('ready', function () {
        if (imap.state != 'authenticated') {
            console.log('not auth');
            imap.connect();
        } else {
            console.log('connected!');
            imap.end();
        }
    });
    imap.once('end', () => {
        console.log('ending');
    });
```

Thanks in advance

**Comment by mscdex** [comment]
What hostname and port are you using?

**Comment by francisco4challenge** [comment]
host: imap-mail.outlook.com
port: 993

**Comment by mscdex** [comment]
Can you set `debug: console.log` and post the output, after censoring the username and password in the output?

**Comment by francisco4challenge** [comment]
[connection] Connected to host
<= '* OK The Microsoft Exchange IMAP4 service is ready. [SABFADEAUABSADAANQAwADEAQwBBADAAMAAwADcALgBlAHUAcgBwAHIAZAAwADUALgBwAHIAbwBkAC4AbwB1AHQAbABvAG8AawAuAGMAbwBtAA==]'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
=> 'A1 LOGIN "email" "pass"'
Err: Error: Timed out while authenticating with server
[connection] Closed

**Comment by mscdex** [comment]
Try setting `authTimeout` to some value larger than the default (currently `5000` milliseconds), like `20000` for 20 seconds. It might be that the server is just slow to respond.

**Comment by francisco4challenge** [comment]
Tried with 30000 and seems to have fixed it, (seems like 10s wasn't enough xD) thx!
