### ISSUE TITLE
how to get it to work with gmail?

### ISSUE THREAD

**Issue by elimau** [mscdex/node-imap#658]
I've tried 4 different ways.
The error message for each way is the comments part.
Thanks.

```
  // Error: 140735690208192:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:../deps/openssl/openssl/ssl/s3_pkt.c:365:
  host: 'smtp.gmail.com',
  port: 587,
  tls: true,
  tlsOptions: { rejectUnauthorized: false, secureProtocol: 'TLSv1_method' },

  // Error: SSLv3 methods disabled
  host: 'smtp.gmail.com',
  port: 587,
  tls: true,
  tlsOptions: {
    rejectUnauthorized: false, secureProtocol: 'SSLv3_method', ciphers: 'AES128-SHA:AES256-SHA:RC4-MD5:RC4-SHA',
    authTimeout:10000,
  },

  // { Error: Timed out while authenticating with server
  // at Timer.listOnTimeout (timers.js:283:5) source: 'timeout-auth' }
  host: 'smtp.gmail.com',
  port: 465,

// { Error: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
  host: 'imap.gmail.com',
  port: 993,
```

**Comment by mscdex** [comment]
You want to use the last configuration. Have you tried the suggestions at the URL given? If you have tried *all* of those suggestions, have you also tried using oauth2 authentication instead of plain passwords?

**Comment by elimau** [comment]
Thank you. The last way ended up working. I went to that website link in the error message and it presented me to accept some terms and conditions to grant some permissions and after that it worked.

Does that mean only imap works and smtp does not work?

**Comment by mscdex** [comment]
I can't comment about smtp, only imap.

**Comment by elimau** [comment]
good point. This is a imap package! Thanks for your help.
