### ISSUE TITLE
How do I hold a connection?

### ISSUE THREAD

**Issue by xenbyte** [mscdex/node-imap#662]
I have a problem.
I establish the connection and set the settings for the keepalive:
```
keepalive: {
  interval: 9000,
  idleInterval: 200000,
  forceNoop: true
  }
```

After some time, the connection is closed. And I get this message:
```
[connection] Ended
[connection] Closed
```
How can I hold the connection without breaking?
Or how to reconnect automatically if the connection is broken?

**Comment by mscdex** [comment]
The server is probably forcefully logging you off despite NOOPs after some maximum time.

To reconnect you can just call `imap.connect()` again or just create a new `Imap` instance and connect.

**Comment by xenbyte** [comment]
Now I get an error:
```
[connection] Error: Error: read ECONNRESET
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:618:25)
```

**Comment by mscdex** [comment]
The server is rejecting the connection for some unknown reason, there isn't anything this module can do about that.

**Comment by xenbyte** [comment]
add reconnect
