### ISSUE TITLE
Error: Nothing to fetch

### ISSUE THREAD

**Issue by HazemElAgaty** [mscdex/node-imap#663]
When i search for mails inside my outlook sent box i always get no results, although i am sure that this mail has sent me an email.

```js
if (req.service == "Outlook") {
    folder = "Sent";
  } else {
    folder = "[Gmail]/Sent Mail";
  }
  var messages = req.messages;
  imap.once("ready", function() {
    imap.openBox(folder, true, function(err, box) {
      imap.search(["ALL", ["TO", req.body.client]], function(err, results) {
        if (err) {
          res.status(400).json({
            msg: "Bad Request",
            errors: [
              {
                msg: "Something went wrong while fetching mail."
              }
            ]
          });
        }
        console.log("RESULTS:", results);
        console.log(folder);
        if (results.length == 0) {
          res.status(400).json({
            msg: "Bad Request",
            errors: [
              {
                msg: "No messages found."
              }
            ]
          });
        }
        var f = imap.fetch(results, {
          bodies: [""],
          struct: true
        });
```

this is a snippet from my code. It works fine with Gmail tho.

**Comment by mscdex** [comment]
Have you checked the value(s) for `req.body.client`? Is it a valid email address?

**Comment by HazemElAgaty** [comment]
yes, i even hard coded req.body.client to the email i want and nothing was fetched either. The thing is that it works perfectly with my gmail account.

**Comment by HazemElAgaty** [comment]
Also thank you so much for the quick reply :). I hope i can solve this soon.

**Comment by mscdex** [comment]
Wait, you said you are sure *they* have sent you email. In that case, wouldn't the email be in another mailbox (e.g. Inbox) and not *your* Sent mail (in which case you would be searching for 'FROM' instead of 'TO')?

**Comment by HazemElAgaty** [comment]
I am sorry, I meant I am sure I have sent an email to that person. For testing I fetched all the mail in my Sent box and logged the messages with the TO Header and the Mail I am searching for is logged. However, when I use the query "TO" with any e-mail, I get no results. It works fine when I search for emails in my inbox using "FOR" queries. And again I tried the same code with Gmail and it works fine.

**Comment by mscdex** [comment]
Are you able to see *any* emails in the Sent mailbox on Outlook's server?

Are you sure the sent emails are not being stored in some other mailbox on Outlook's server?

**Comment by HazemElAgaty** [comment]
Yes I am able to fetch all the messages from my Sent box by just removing the TO Query. It successfully fetches all the mails in my Sent box. And I compared the results count to the number of mails in my Sent box and it is the same. However, when I search for any e-mail with the TO Query, It always fails. I really spent the whole day testing this and I am clueless to what is going wrong.

**Comment by mscdex** [comment]
It wouldn't surprise me if the server is trying to match the criteria in some unexpected way (I have seen gmail do that kind of thing).

Have you tried using the `'HEADER'` criteria instead, like `['HEADER', 'TO', 'foo@example.org']`?

**Comment by HazemElAgaty** [comment]
Well for some reason the 'HEADER' criteria worked. I have no clue why tho. Thank you for the help :) .
