### ISSUE TITLE
Retrieve no part of "bodies"

### ISSUE THREAD

**Issue by popey456963** [mscdex/node-imap#668]
Is there a way to retrieve no parts of the body?  For instance, my use case is trying to grab _only_ the envelope and nothing else:
```
   { bodies: undefined, envelope: true }
```
Errors out.

**Comment by mscdex** [comment]
That should work just fine. You don't even need to explicitly set it in the object.

**Comment by popey456963** [comment]
@mscdex Absolutely my bad, I'm sorry, it was the mail parser I'm using freaking out at an "undefined" content value.  Made the mistake of assuming since my code was working for one input, it would work for another.

Thanks for maintaining such a stable library, by the way.  I'm not sure why I'd even have considered there to be a bug in it.
