### ISSUE TITLE
When "bodies" parameter is not defined, give useful error message

### ISSUE THREAD

**Issue by popey456963** [mscdex/node-imap#669]
At the moment when bodies is an invalid or non-existant parameter, it gives the rather cryptic message of:

```
(node:15824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11493): TypeError: Cannot read property 'pipe' of undefined
```

**Comment by mscdex** [comment]
Did you check the stack trace? Where is the error actually coming from?

**Comment by popey456963** [comment]
My bad, not related to imap, see #668.
