### ISSUE TITLE
Can't search emails with special characters " ' "?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#672]
Hello developers, 
I use req.imap.search with the mail body queries with the search string is "I'm a little girl". I can't receive the email return from imap server even though in imap folder have the email with the body.
Seem that node-imap can't query for special character "\'". 
I checked the contents of the email it is like this "Hi i\&#39;m a little girl.".
Please give me an i deal if you see the same issue.

```
req.imap.search([ 'Body', 'Hi I\'m a little girl' ], (err, uids){
   //the result is [] 
})
```

Many Thanks,
Vinh

**Comment by mscdex** [comment]
The server may not be doing a case-insensitive search. You mention the email has a lowercase 'i' in "i'm" but you're searching with an uppercase 'I'. Did you try making the string match exactly?

**Comment by quangvinh1305** [comment]
Hi @mscdex 
i see this in my email body Hi I&#39;m a little girl.
I think that is reason why.

Thanks.

**Comment by quangvinh1305** [comment]
Hi @mscdex
i see this in my email body Hi I\&#39;m a little girl.
I think that is reason why. How can i handle for this case.

Thanks.

**Comment by mscdex** [comment]
If the body contains html entities, then you'd have to search using them as well (using `&#39;` instead of `'`), it has to be an exact match (not sure about the case-sensitivity).

**Comment by quangvinh1305** [comment]
It's great my issue is resolved.
Thanks @mscdex.
