### ISSUE TITLE
Does the package imap work together with socket.io ?

### ISSUE THREAD

**Issue by thE-iNviNciblE** [mscdex/node-imap#674]
I get in the same folder one error and one not.

Error: Cannot find module 'imap'

------ works -----
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var Imap = require('imap'),
    inspect = require('util').inspect;

----- works not ---- 
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var Imap = require('imap'),
    inspect = require('util').inspect;

var SocketIOFileUpload = require('socketio-file-upload'),
    socketio = require('socket.io'),
    express = require('express'),
	http = require('http'),
	binaryServer = require('binaryjs').BinaryServer,
	wav = require('wav'),
	mysql = require('mysql');

**Comment by mscdex** [comment]
There is no problem using this module server-side with any other module.

**Comment by thE-iNviNciblE** [comment]
thx for fast information and really nice and hard work for this nodejs module :-)

i had installed both ways npm install imap and npm install -g imap.

Your imap nodejs module has a other folder structure with the /libs/ folder...

i don't know where the error is... :-|
./app.js not working - with all modules
./app2.js working - without all modules like socket.io
./node_modules/imap - the module is still there

**Comment by thE-iNviNciblE** [comment]
strange, i've the solution i'm working with pm2 and i had to rename the file app.js in app-imap.js then it is working without module not found... :-)

**Comment by mscdex** [comment]
I'd take that up with pm2 then if that's where the problem lies.
