### ISSUE TITLE
STARTTLS not working

### ISSUE THREAD

**Issue by AndiSHFR** [mscdex/node-imap#675]
I tried to connect to an imap server using STARTTLS option but it did not work.
Even after setting <code>tls: false, autotls: 'required'</code> options it still did not work.

While crawling thru the source code i came to the following code lines in file lib/Connection.js#1647:

```js
   if (self.serverSupports('STARTTLS')
          && (self._config.autotls === 'always'
              || (self._config.autotls === 'required'
                  && self.serverSupports('LOGINDISABLED')))) {
          self._starttls();
          return;
}
```
Shouldn't the if-clause read:

```js
   if (self.serverSupports('STARTTLS')
          && (self._config.autotls === 'always'
              || (self._config.autotls === 'required'
                  && !self.serverSupports('LOGINDISABLED')))) {
```
Mind the ! (not) in front of <code>self.serverSupports('LOGINDISABLED')</code>.

After changing this i got it working.

**Comment by mscdex** [comment]
No, a server implementation must advertise the LOGINDISABLED capability if a login should not be attempted (typically due to a required STARTTLS). If a server is advertising the STARTTLS capability on a plaintext connection and NOT the LOGINDISABLED capability, then the server is not behaving according to RFC 3501, the IMAP specification.

**Comment by AndiSHFR** [comment]
So the following snippet from the servers log would mean that the server is not behaving according to RFC3501 because it is advertising STARTTLS but is missing the LOGINDISABLED flag?

```log
"IMAPD"	10212	2915	"2018-01-12 13:42:19.353"	"172.20.1.2"	"RECEIVED: A0 CAPABILITY"
"IMAPD"	10212	2915	"2018-01-12 13:42:19.357"	"172.20.1.2"	"SENT: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL STARTTLS NAMESPACE RIGHTS=texk[nl]A0 OK CAPABILITY completed"
"IMAPD"	10208	2915	"2018-01-12 13:42:19.364"	"172.20.1.2"	"RECEIVED: A1 STARTTLS"
```

**Comment by alexte** [comment]
autotls: 'required'
means: start tls only if THE SERVER "requires" it. (LOGINDISABLED)
I filed an issue for a feature request to add a different setting
#589
