### ISSUE TITLE
How can I get server curent time?

### ISSUE THREAD

**Issue by wangxiaoming2** [mscdex/node-imap#676]
I am triggering new mail, I need current time at mail server to determine whether a new mail received, is there any way to get it?

**Comment by mscdex** [comment]
There is no way to get the current server time. However, that shouldn't be necessary anyway to check for new mail. There are multiple ways to more appropriately go about that. If you're doing an explicit search, just look for messages without the `'Seen'` flag set (there is an example of this in the readme). Also, you might want to listen for the `'mail'` event on the connection object, which will be emitted whenever new mail arrives while you are connected.

**Comment by wangxiaoming2** [comment]
Thanks for that, I found a stupid way is that I send a mail to my self and get the internalDate ...

**Comment by wangxiaoming2** [comment]
Sorry, one more question
Will there be different time format for internalDate when I connect to different server?
For example, outlook mail and zimbra

**Comment by mscdex** [comment]
The time zone may be different of course, but the format for the INTERNALDATE field is well defined in RFC 3501, so the *format* *should not* change from server to server.
