### ISSUE TITLE
Unable to mark emails as \Seen

### ISSUE THREAD

**Issue by dbaile7** [mscdex/node-imap#678]
I am trying to set flags for a single email using its uid and I am getting no errors from the setFlags function, but the email is not being updated on the server. My code is as follows:

```
imap.once('ready', function() {
    imap.openBox(folder, true, function(err, box) {
        imap.setFlags(uid, flagArray, function(err) {
            ....
```
folder is 'Inbox' in my test, uid is "64" but I have also tried converting it to the number 64 and I tried wrapping it in an array: [ uid ]
for flagArray I have tried ['Seen'], ['\\Seen'] and ['\\\\Seen'] <- the last one caused an error

Is there something I'm doing wrong?

**Comment by mscdex** [comment]
Are you sure `uid` is in fact a uid and not a sequence number?

**Comment by dbaile7** [comment]
Yes, the setFlag call is done from a separate imap session and the uid is retrieved from a previous session from email.attributes.uid

**Comment by dbaile7** [comment]
Ok I found the problem.

The openBox function I had before was:
`imap.openBox(folder, true, ...`

This opened the box in read-only mode. Changing that to false has fixed the problem.

I recommend that node-imap checks read-only state and returns an error if you try to perform an operation like this in read-only model.
