### ISSUE TITLE
How to fetch the body of the email

### ISSUE THREAD

**Issue by lesterjanpearson** [mscdex/node-imap#679]
I cant see the body of the message for example it was just "mybody"
```
var Imap = require('imap'),
    inspect = require('util').inspect;

var imap = new Imap({
  user: 'lxxx',
  password: 'xxx',
  host: 'imap.gmail.com',
  port: 993,
  tls: true
});

function openInbox(cb) {
  imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
  openInbox(function(err, box) {
  if (err) throw err;
  var f = imap.seq.fetch(box.messages.total + ':*', { bodies: ['HEADER.FIELDS (FROM)',''] });
  f.on('message', function(msg, seqno) {
    console.log('Message #%d', seqno);
    var prefix = '(#' + seqno + ') ';
    msg.on('body', function(stream, info) {
      if (info.which === 'TEXT')
        console.log(prefix + 'Body [%s] found, %d total bytes', inspect(info.which), info.size);

      var buffer = '', count = 0;
      stream.on('data', function(chunk) {
        count += chunk.length;
        buffer += chunk.toString('utf8');
        if (info.which === 'TEXT')
          console.log(prefix + 'Body [%s] (%d/%d)', inspect(info.which), count, info.size);
      });
      stream.once('end', function() {
        if (info.which !== 'TEXT')
          console.log(prefix + 'Parsed header: %s', inspect(Imap.parseHeader(buffer)));
        else
          console.log(prefix + 'Body [%s] Finished', inspect(info.which));
      });
    });
    msg.once('attributes', function(attrs) {
      console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
    });
    msg.once('end', function() {
      console.log(prefix + 'Finished');
    });
  });
  f.once('error', function(err) {
    console.log('Fetch error: ' + err);
  });
  f.once('end', function() {
    console.log('Done fetching all messages!');
    imap.end();
  });
});
});

imap.once('error', function(err) {
  console.log(err);
});

imap.once('end', function() {
  console.log('Connection ended');
});



imap.connect();



```

**Comment by mscdex** [comment]
Most likely because you're doing `info.which === 'TEXT'`, but you're not fetching the `'TEXT'` body. You should instead check for `info.which === ''`.

**Comment by lesterjanpearson** [comment]
one stream.on('data', function(chunk) { ?

**Comment by mscdex** [comment]
You need to replace *every* instance of `'TEXT'` with `''`.

**Comment by lesterjanpearson** [comment]
This is what I am getting when I replace all.

![image](https://user-images.githubusercontent.com/1978109/35137594-25f6ff50-fd25-11e7-82c3-cff9f049b9f6.png)

**Comment by mscdex** [comment]
Looks fine to me. You're seeing the entire contents of the email, headers and all, which is what `''` will retrieve.

**Comment by lesterjanpearson** [comment]
Do I need to convert that to be able to see the html body?

**Comment by lesterjanpearson** [comment]
is it possible to get the html or text content on the email boday?

**Comment by lesterjanpearson** [comment]
```
var Imap = require('imap'),
    inspect = require('util').inspect;

var imap = new Imap({
  user: 'xxxxx',
  password: 'xxxx',
  host: 'imap.gmail.com',
  port: 993,
  tls: true
});

function openInbox(cb) {
  imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
openInbox(function(err, box) {
    if (err) throw err;
    var f = imap.seq.fetch(box.messages.total + ':*', {
      bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
      struct: true
    });
    f.on('message', function(msg, seqno) {
      console.log('Message #%d', seqno);
      var prefix = '(#' + seqno + ') ';
      msg.on('body', function(stream, info) {
        var buffer = '';
        stream.on('data', function(chunk) {
          buffer += chunk.toString('utf8');
        });
        stream.once('end', function() {
          console.log(prefix + 'Parsed header: %s', inspect(Imap.parseHeader(buffer)));
        });
      });
      msg.once('attributes', function(attrs) {
        console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
      });
      msg.once('end', function() {
        console.log(prefix + 'Finished');
      });
    });
    f.once('error', function(err) {
      console.log('Fetch error: ' + err);
    });
    f.once('end', function() {
      console.log('Done fetching all messages!');
      imap.end();
    });
  });
});

imap.once('error', function(err) {
  console.log(err);
});

imap.once('end', function() {
  console.log('Connection ended');
});

imap.connect();

```
looks like I can pull the from to subject. but I still cant get the email body/content. any idea?

**Comment by hallettj** [comment]
@lesterjanpearson What I do is fetch the message attributes (obtained from the `'attributes'` event of each message) which provide a list of message parts, and then I fetch the parts individually. I traverse the tree in the `struct` property of the message attributes and select the `partID` of each content part to get a list of IDs for content parts.

A fetch for a message part looks like this:

```js
imap.seq.fetch([messageSequenceNumber], { bodies: partID })
```

Then do just what you have been trying: listen for `'body'` events on each message and assemble the result from `'data'` chunks. When the selection includes that `bodies: partID` bit then you get the actual message part content.

**Comment by phpmydev** [comment]
Please pardon me for posting this but,  would @halletj mind posting your code for traversing/parsing the bodies:partID? Or if someone has a compelling reason not to write my own IMAP webmail in node?  Or maybe a detailed tutorial of how to install RoundCube on a Raspberry Pi?  Or how to ask a question on Github?!!  But, I've been busting my head open on this.  What I'd really like to do is have a webmail client written in nodejs.  Did I already say that?   Thanks in advance!

**Comment by mscdex** [comment]
@phpmydev If you fetch the message's `struct`, you will get back an object describing the message's structure/layout. From that you can get the `partID` of a particular part of the message that you can use to pass to `fetch()`.

**Comment by phpmydev** [comment]
Thanks for your response! but, I'm getting this:
`e = imap.seq.fetch([messageSequenceNumber], { bodies: attrs.struct })
			console.log(e);
output of e:
EventEmitter {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
`
Any idea n this?

**Comment by phpmydev** [comment]
@mscdex - do you have any thoughts on this?  
Thanks!

**Comment by mscdex** [comment]
@phpmydev  `bodies: attrs.struct` is not valid, refer to the readme for descriptions on what `attrs.struct` looks like and what `bodies` expects.

**Comment by phpmydev** [comment]
Ok, Great!  Can you tell me how to get the body of the email out of the following?  I'm not clear on how to do this from the Readme.   
```
(#25) Parsed header: { subject: [ 'Re: Fwd: Re: test for file creation' ],
  to: [ 'Richard Whitney <richard@email.com>' ],
  from: [ 'Ric Whitney <ric@email.com>' ],
  date: [ 'Wed, 21 Nov 2018 08:50:22 -0700' ] }
(#25) Attributes: { struct: 
   [ { type: 'alternative',
       params: { boundary: '------------4F55820E549333602A8BFFE6' },
       disposition: null,
       language: [ 'en-US' ],
       location: null },
     [ { partID: '1',
         type: 'text',
         subtype: 'plain',
         params: { charset: 'utf-8', format: 'flowed' },
         id: null,
         description: null,
         encoding: '7bit',
         size: 1933,
         lines: 45,
         md5: null,
         disposition: null,
         language: null,
         location: null } ],
     [ { partID: '2',
         type: 'text',
         subtype: 'html',
         params: { charset: 'utf-8' },
         id: null,
         description: null,
         encoding: '7bit',
         size: 4235,
         lines: 95,
         md5: null,
         disposition: null,
         language: null,
         location: null } ] ],
  date: 2018-11-21T15:50:26.000Z,
  flags: [ 'NonJunk' ],
  uid: 27,
  modseq: '85' }
(#25) Finished

```

**Comment by phpmydev** [comment]
I'm trying this: 
var b = imap.seq.fetch([seqno], { bodies: '1' });
		console.log('BODY?: ',b);
renders: ```		BODY?:  EventEmitter {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
Message #1
```

**Comment by mscdex** [comment]
Like most things in node, it's asynchronous. See the second example in the readme.

**Comment by phpmydev** [comment]
Thanks @mscdex - I have now gotten to a point where I am getting the body of the email.  How do I listen for messages to come in?  I'm in the console.log and I have to rerun the app to see the latest message.

**Comment by phpmydev** [comment]
It appears that once I have the front-end going, I can manipulate the back-end from there.

**Comment by Vital-Ij** [comment]
@phpmydev Do you mind sharing the code how you got the body part?
