### ISSUE TITLE
add a special flags to headers of an emails and search?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#681]
Hi developers,

I would like to store a special flags '\\Special 'to headers of an emails and then search it?

Thanks you,
Vinh

**Comment by jeffreyroshan** [comment]
You can only add flags that are supported by your email provider. If you want to organise your existing emails, then you can create a new mailbox "Special" and move emails to the new box. You can then fetch emails from that box. Or if you want to add a custom header to new emails created, you can do so by adding a custom header and then search using the Search by HEADER.
