### ISSUE TITLE
Exchange Public Folders?

### ISSUE THREAD

**Issue by u382514** [mscdex/node-imap#690]
Is there a way to open up a public folder? I'm not finding the right combo to do so here.

**Comment by mscdex** [comment]
You might also check other mailbox namespaces by passing in other namespace prefixes to `imap.getBoxes()`. The available namespaces are in `imap.namespaces`.

**Comment by u382514** [comment]
Thank you for the quick response! Definitely was not in the boxes response so let me check out the namespaces and go from there.
