### ISSUE TITLE
Adding custom flags

### ISSUE THREAD

**Issue by kerimdragolj** [mscdex/node-imap#692]
Hello guys, I've been trying to add custom flags to emails. Something like 'Starred' or 'Important' but not sure if its even possible. I've read in the docs something about permFlags but not sure if those flags has to be provided by email provider or we can add our custom ones?

**Comment by mscdex** [comment]
If the mailbox object has `.newKeywords === true`, then you can define your own (permanent) keywords via the `*Keywords()` functions. Otherwise, if `.newKeywords === false`, then either the server will ignore the change or it will save the keywords for the current connection/session only.

**Comment by kerimdragolj** [comment]
Sry, wasnt expecting such quick answer.. Aaa so I should be adding keywords instead of flags, and if the newKeywords === false nothing can be done? Thanks for the help, issue can be closed... Btw. I've been getting struggling with 'Self signed certificate in certificate chain' error for a while now, when I'm trying to use gmail or hotmail emails, more precisely when I try to access each email by its seqno (get, delete, patch). Are you by any chance familiar with that error and what might've been causing it?

**Comment by mscdex** [comment]
You should not be getting TLS errors when connecting to public servers like gmail.

Are you using the latest version of `imap`? If so, what does your connection config look like (omitting username and passwords)?

Setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"` is dangerous as it makes you susceptible to MITM attacks.

**Comment by kerimdragolj** [comment]
Hmm not sure what it is about then... I'm using imap 0.8.19 .. if this is what u asking i'm pretty much just getting his password and email from request, together with imap server and port, smtp server and port.

var imap = new Imap({
        user: this.emailUsername,
        password: this.emailPassword,
        host: this.host,
        port: this.port,
        tls: this.tls,
        //debug: console.log,
        tlsOptions: {
          rejectUnauthorized: false
        }
});

**Comment by mscdex** [comment]
So if `host` is set to `'imap.gmail.com'`, `port` is set to `993`, `tls` is set to `true`, and `tlsOptions` is omitted completely, you get a self-signed certificate error?

If so, perhaps you're being MITM'ed then. What does `openssl s_client -connect imap.gmail.com:993` output from the same machine the `imap` module is being used?

**Comment by kerimdragolj** [comment]
Here is the whole output: http://prntscr.com/jbaa9v http://prntscr.com/jbaaid

**Comment by kerimdragolj** [comment]
I think this solved it: tlsOptions: {          rejectUnauthorized: false        }

**Comment by mscdex** [comment]
Yeah it looks like you're being MITM'ed by Avast. If you're ok with this, a better option might be to set `tlsOptions.ca` to that server certificate you see in the console. This should prevent the self-signed error, but obviously you should only need to do that on that affected machine (most people would not/should not be MITM'ed).

**Comment by mscdex** [comment]
You'd just copy the part starting with the line containing 'BEGIN CERTIFICATE' and ending with the line containing 'END CERTIFICATE', preserving the newlines, and set that string as the `ca` value.

Another alternative to this of course is to simply disable (at least) the 'Mail Shield' component of Avast.

**Comment by kerimdragolj** [comment]
Ok. thanks a lot! sry for bothering u.
