### ISSUE TITLE
what is the reason of ECONNRESET error?

### ISSUE THREAD

**Issue by NetHans** [mscdex/node-imap#695]
Hi,
I get this error after close the imap connection.
```
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  source: 'socket' }
```
What ist the reason for this error?

This is my code
```
var Imap = require('imap'),
    inspect = require('util').inspect;
	
var imap = new Imap({
	user: '----',
	password: '----',
	host: '----',
	port: 993,
	tls: true,
	autotls: "always",
	tlsOptions: { rejectUnauthorized: false, secureProtocol: 'TLSv1_method' }
});

function openInbox(cb) {
  imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
	imap.getBoxes(function(err, boxes){
		console.log(typeof(boxes));
		console.log(boxes);
		imap.end();
	});	
});

imap.once('error', function(err) {
  console.log(err);
});

imap.once('end', function() {
  console.log('Connection ended');
});

imap.connect();
```

**Comment by mscdex** [comment]
It just means the server abruptly ended the connection.

**Comment by NetHans** [comment]
When I remove the "imap.end()" command, I don't get the errormessage. 
So I think that the Server doesn't close the connection abruptly.
Is it possible that I close the imap connection to early? But when I close the connection to early, when is the right time and where is the right code place to close the connection to prevent the error?

**Comment by mscdex** [comment]
That is what is happening, I've seen others run into the same issue before. `.end()` sends a logout request and the server terminates the connection after that. Sometimes it's done gracefully, other times it's reset forcefully. You'll just have to add an `'error'` event handler and ignore any errors that occur after you've logged out.

**Comment by saurabhraitruworth** [comment]
t
