### ISSUE TITLE
find UID of the email sent by Gmail in sent folder? 

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#697]
Hi developers,

I would like to ask for the case when i send an email by gmail the email is auto save to sent folder of gmail.

How can i know uid of that email?

Thanks,

**Comment by mscdex** [comment]
You have to search for it using some criteria.

**Comment by quangvinh1305** [comment]
@mscdex but i afraid that if i use messageId or newest message to search but gmail is still not store in sent folder. so the result query is empty. Do you have any ideal?

`
					createMessage(req, (err, msg) => {
						if (err) return next(err);
						
						var mailComposer = mailcomposer(msg);
						msg.messageId = mailComposer.messageId() + "@" + config.FLOW_HOST;
						transporter.sendMail(msg, (err, sendMailInfo) => {
							if (err) return futil.json(req, res, {
								error: err
							});
							if (!req.user.gmailXoauth2){
								msg.messageId = sendMailInfo.messageId;
								// build the rfc 822 message
								mailComposer.build((err, raw) => {
									if (err) return next(err);
									req.imap.append(raw, {
										mailbox: path,
										flags: ['\\Seen'],
										date: req.msg.date ? new Date(req.msg.date) : new Date()
									}, (err, uid) => {
										if (err) return futil.json(req, res, {
											error: err
										});
										console.log(sendMailInfo);
										msg.uid = uid;
										msg.path = path;
										msg.messageId = sendMailInfo.messageId;
										if (msg.from && !_.isArray(msg.from)) {
											msg.from = [{ address: msg.from }];
										}

									});
								});
							} else {
                                                           #search by creteria messageId or newest proposal by Brian
                                                           # afraid that gmail is still not store that email and i search it.

							}
						});
					});
`

**Comment by mscdex** [comment]
Did you check the value of `path`? Are you sure the `append()` was successful? How exactly are you trying to search, as that is not included in your code snippet?

**Comment by quangvinh1305** [comment]
Hey Brian,
when i send an email with gmail. i fetched nextUID it is ok.
Thanks.
