### ISSUE TITLE
Connection error: Error: self signed certificate

### ISSUE THREAD

**Issue by EJNB** [mscdex/node-imap#705]
I am trying to connect to an email address via IMAP, it is a local mail server in our company and I get the following error:
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }

my configurations are the following:

var Imap = require('imap'),
    inspect = require('util').inspect;

var imap = new Imap({
    user: 'contratos@cubanacan.tur.cu',
    password: 'Cubanacan123',
    host: 'correo.cubanacan.tur.cu',
    port: 993,
    tls: true
});

function openInbox(cb) {
    imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
    openInbox(function(err, box) {
        if (err) throw err;
        var f = imap.seq.fetch('1:3', {
            bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
            struct: true
        });
        f.on('message', function(msg, seqno) {
            console.log('Message #%d', seqno);
            var prefix = '(#' + seqno + ') ';
            msg.on('body', function(stream, info) {
                var buffer = '';
                stream.on('data', function(chunk) {
                    buffer += chunk.toString('utf8');
                });
                stream.once('end', function() {
                    console.log(prefix + 'Parsed header: %s', inspect(Imap.parseHeader(buffer)));
                });
            });
            msg.once('attributes', function(attrs) {
                console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
            });
            msg.once('end', function() {
                console.log(prefix + 'Finished');
            });
        });
        f.once('error', function(err) {
            console.log('Fetch error: ' + err);
        });
        f.once('end', function() {
            console.log('Done fetching all messages!');
            imap.end();
        });
    });
});

imap.once('error', function(err) {
    console.log(err);
});

imap.once('end', function() {
    console.log('Connection ended');
});

imap.connect();

**Comment by mscdex** [comment]
For legitimate self-signed certificates (and you are not being MITM'ed), you will need need to set `tlsOptions` to include your self-signed `ca` so that the your self-signed CA can be trusted.

**Comment by mscdex** [comment]
You need to have a copy of the self-signed CA certificate locally, that is what you set as `ca` in your `tlsOptions`. You can get the raw certificate using the openssl command line utility with: `openssl s_client -showcerts -connect hostname:port </dev/null`

**Comment by EJNB** [comment]
and copy the certificate to the root directory. "correo.cer"
I guess the configuration is like that
var imap = new Imap({
    user: 'contratos@cubanacan.tur.cu',
    password: '*************',
    host: '172.104.55.88',
    port: 993,
    tls: true,
    tlsOptions : {
        ca : ''......"
    }
});
now how do I use the commands these openssl s_client -showcerts -connect hostname: port
What if I give the certificate path? tlsOptions : { ca : path_file_certificade}

**Comment by mscdex** [comment]
`ca` has to contain the raw certificate string (not a file path). So whether you load that from disk or you put inline, it doesn't matter.

**Comment by EJNB** [comment]
I was watching googling and I happened to find an issue with something configured from tlsOptions, to be exec this was what I found tlsOptions: {
         rejectUnauthorized: false
     }
I put it in my project and it works like a charm. Thanks bro

**Comment by mscdex** [comment]
FWIW that's not a real solution and leaves you open to MITM attacks. By explicitly setting the `ca` appropriately you can be sure you are talking to who you think you are.

**Comment by EJNB** [comment]
Excuse me, you could give me an example of how to use option 'ca' with tlsOptions {ca: .....}.
The problem is that you do not put in value of 'ca' of the object tlsOptions

**Comment by mscdex** [comment]
As I previously said, `ca` has to be set to the actual server (PEM) certificate string.

**Comment by C7ement** [comment]
Hi,
I don't understand how to configure the tlsOptions
Would it be possible to have an exemple please ?

**Comment by victorlclopes** [comment]
It's supposed to be something like this:

```
const imaps = require('imap-simple')
const fs = require('fs')
 
let config = {
    imap: {
        user: 'your_username',
        password: 'your_password',
        host: 'mail.yourserver.com',
        port: 993,
        tls: true,
        tlsOptions : {
            ca: [ fs.readFileSync("./path/to/your_ca_certificate.pem") ]
        }
    }
}

imaps.connect(config).then(...
```

You must have the certificate file and then load its content like above. Note that the `ca` option expects an array. If you have the file in .cer, .crt or .der formats you can use openssl to convert it to PEM.
You need this for certificates both self-signed or signed by a private CA.

I've tested and it works (against a Microsoft Exchange server).

Either that or use `rejectUnauthorized: false` which is much less secure.

As per:
[https://nodejs.org/api/tls.html#tls_tls_connect_options_callback](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback)

**Comment by mscdex** [comment]
Honestly `rejectUnauthorized: true` should never be a solution to this problem in node. Nowadays you can:

* Pass the CA certs explicitly
* Use the OpenSSL certificate store (if your self-signed certificates are available there) instead of node's built-in certificate list via the `--use-openssl-ca`
* Add CA certificates in addition to node's built-in list by setting the `NODE_EXTRA_CA_CERTS` environment variable to a path to a file that contains one or more certificates

**Comment by ile** [comment]
FYI, this may work:

```coffee
			imap = new Imap({
				host: host
				tls: true
				tlsOptions: { servername: host }
			})

```

Setting `servername` in `tlsOptions`.

**Comment by ile** [comment]
FYI, this may work:

```coffeescript
imap = new Imap({
	host: host
	tls: true
	tlsOptions: { servername: host }
})

```

Setting `servername` in `tlsOptions`.

**Comment by marktorrance** [comment]
Confirming this last option works for me to workaround the problem in node 12 or 13 that was absent in node 11.  You can also work around the problem by running node with --tls-max-v1.2 option, but that's annoying.

**Comment by ebarila** [comment]
How do you get the certificate string from a gmail account?

**Comment by atorresbernal** [comment]
> I was watching googling and I happened to find an issue with something configured from tlsOptions, to be exec this was what I found tlsOptions: {
>          rejectUnauthorized: false
>      }
> I put it in my project and it works like a charm. Thanks bro

Thank you so much, this was the answer for me.

**Comment by martian17** [comment]
> > I was watching googling and I happened to find an issue with something configured from tlsOptions, to be exec this was what I found tlsOptions: {
> >          rejectUnauthorized: false
> >      }
> > I put it in my project and it works like a charm. Thanks bro
> 
> Thank you so much, this was the answer for me.

I think that solution is a bad idea. It just turns off the security instead of fixing the underlying issue with SNI. 
That means whoever has access to your network could steal your access token or password by posing as your email server.
Instead, I strongly recommend that you use the solution provided by @ile, which fixes the underlying problem, and still retains the security afaik.
