### ISSUE TITLE
Can't move messages to another box?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#706]
I moved a message from inbox to trash by use imap.move. Even i closed the box but the messages is still in the folder INBOX folder how can i move it.
`req.imap.on('ready', () => {
	req.imap.openBox(path, err => {
		if (err) return next(err);

		req.imap.move(uids, des, (err, info) => {

			console.log(err, info)
			if(!_.isEmpty(err)){
			        return futil.json(req, res, {
			                  error: err
					})
				}
		         req.imap.closeBox((err) => {
				req.imap.openBox(des, (err, info) => {
					if (err) return next(err);
					// console.log("===========>", info, err)
					// if (err) return next(err);

					// let queries = ['OR'];
					// if(messageIds.length >= 2){
					// 	messageIds.forEach(function(messageId){
					// 		queries.push(['HEADER', 'MESSAGE-ID', messageId])
					// 	})
					// } else {
					// 	queries = ['HEADER', 'MESSAGE-ID', messageIds[0]]
					// }
					// var partialDone = () => {
					// 	futil.json(req, res, {
					// 		error: 'new uid not found',
					// 		status: 'partial done'
					// 	});
					// };
					// req.imap.search([queries], (err, uids) => {
					var uidsMoved = []
					for(var i = 0; i < uids.length; i++){
						uidsMoved.push(info.uidnext - (i + 1))
					}

					fetchHeaders({uids: uidsMoved, path: des}, req, res, next);
					// });
				})
			})
		})
       });
});`

**Comment by mscdex** [comment]
What does your `console.log(err, info)` display?

**Comment by mscdex** [comment]
Also, you really should use the `info` from your `imap.move()` call if it's available, as it's not subject to race conditions like your current solution is (assuming the uids are directly offset from `.uidnext`).

**Comment by quangvinh1305** [comment]
This is the log i got the messages is moved to trash folder but they are not deleted in INBOX floder.

[log_imap_cant_move.txt](https://github.com/mscdex/node-imap/files/2046527/log_imap_cant_move.txt)

>>>Also, you really should use the info from your imap.move() callback if it's available, as that is not subject to race conditions like your current solution is (which assumes the new uids of the moved messages are directly offset from .uidnext).
The info is empty and the race condition here is the challenge for me. Currently i don't have any ideal.

**Comment by quangvinh1305** [comment]
I rechecked it is ok with current implement.
