### ISSUE TITLE
Can't get all mails by node-imap@0.8.19

### ISSUE THREAD

**Issue by liangmark** [mscdex/node-imap#712]
i use node-imap to get mail from server. but it's only return recent mails（the count is incorrect）

	    function openInbox(cb) {
	        imap.openBox('INBOX', false, cb);
	    }

	    imap.once('ready', function () {
	        openInbox(function (err, box) {
	            if (err){
	                console.log('failed to open the mail.');
	            } else {
	                console.log('the total of message:');
	                console.log(box);
	                //['SINCE', 'May 30, 2018']
	                //['UNSEEN', ['SUBJECT', 'HY']]
	                imap.search(['ALL'], function (err, results) {
	                    if (err){
	                        console.log('failed to search the mail.');
	                    } else {
	                        if (!results || !results.length){
	                            console.log('no mails!!!');
	                            imap.end();
	                        } else {
	                            console.log('the length of results:'+results.length);
	                            //var f = imap.fetch(results, {bodies:'',markSeen: true});
	                            var f = imap.fetch(results, {bodies:''});
	                            f.on('message', function (msg, seqno) {
	                                msg.on('body', function (stream, info) {
	                                    simpleParser(stream, function (err, mail) {
	                                        console.log(mail.from.value[0].name);
	                                        console.log('==================');
	                                        console.log(mail.subject);
	                                        console.log('==================');
	                                        console.log(mail.date);
	                                    })
	                                });
	                                msg.once('end', function() {
	                                    console.log(seqno + ' finished.');
	                                });
	                            });
	                            f.once('error', function(err) {
	                                console.log('failed to fetch: ' + err);
	                            });
	                            f.once('end', function() {
	                                console.log('succeed in getting all mails!');
	                                imap.end();
	                            });
	                        }
	                    }
	                })
	            }
	        });
	    });

	    imap.once('error', function(err) {
	        console.log(err);
	    });

	    imap.once('end', function() {
	        console.log('finished!');
	    });

	    imap.connect();

the result of console:

		the total of message:
		{ name: 'INBOX',
		  flags: [ '\\Answered', '\\Seen', '\\Deleted', '\\Draft', '\\Flagged' ],
		  readOnly: false,
		  uidvalidity: 1,
		  uidnext: 0,
		  permFlags: [ '\\Answered', '\\Seen', '\\Deleted', '\\Draft', '\\Flagged' ],
		  keywords: [],
		  newKeywords: false,
		  persistentUIDs: true,
		  nomodseq: false,
		  messages: { total: 40, new: 29 } }
		the length of results:40
		1 finished.
		lixueqi
		==================
		【兼职面试安排】杭州/Hubin Intime/3.23
		==================
		Fri Mar 23 2018 17:39:32 GMT+0800 (CST)
		2 finished.
		...

the other mail client for the same account:
![snip20180710_6](https://user-images.githubusercontent.com/12019458/42496297-1f0376d2-8458-11e8-8548-dfdcf8c01b2c.png)

**Comment by mscdex** [comment]
Is it possible that the mailbox shown in the screenshot(s) are not of the inbox, but a different mailbox on the account? You might verify this by calling `imap.getBoxes()` and seeing if the mail provider has the mailbox you're looking for under a different name.

Also on a semi-related note, if you're fetching all mail, you don't need to `imap.search()` first, you should be able to just do `imap.seq.fetch(`1:${box.messages.total}`, ....)`, which is much more efficient if you have a lot of messages in the mailbox, since no giant array of message uids/sequence numbers has to be created first.

**Comment by liangmark** [comment]
i use 'getBoxes()' to verify the mailbox on the account	    

        imap.once('ready', function () {
	        imap.getBoxes(function (err, boxes) {
	            console.log(boxes);
	        });
	    });

the result:

		{ INBOX: { attribs: [], delimiter: '/', children: null, parent: null },
		  '草稿箱': 
		   { attribs: [ '\\Drafts' ],
		     delimiter: '/',
		     children: null,
		     parent: null,
		     special_use_attrib: '\\Drafts' },
		  '已发送': 
		   { attribs: [ '\\Sent' ],
		     delimiter: '/',
		     children: null,
		     parent: null,
		     special_use_attrib: '\\Sent' },
		  '已删除': 
		   { attribs: [ '\\Trash' ],
		     delimiter: '/',
		     children: null,
		     parent: null,
		     special_use_attrib: '\\Trash' },
		  '垃圾邮件': 
		   { attribs: [ '\\Junk' ],
		     delimiter: '/',
		     children: null,
		     parent: null,
		     special_use_attrib: '\\Junk' } }
 i have opened each mailbox, only 'INBOX' and '已发送' has mails，and the mails in '已发送' are not my want.

**Comment by liangmark** [comment]
I find the reason, when the mail was received by email client, it's deleted on email server.  I am sorry for my poor english， thank you very much!
