### ISSUE TITLE
Actual limit 25mb size of gmail?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#713]
Hi Developer,
I built an email with attachments 25mb and plain text but gmail don't allow me send it because error email size limitation.
I researched 25mb + email headers + email body greater than >= 25mb ~= 34mb greater than limit size of gmail.
Please let me know Actual limit size 25mb of gmail.
Thanks

**Comment by mscdex** [comment]
I'm not sure what your question is. If you're asking about something that is provider-specific, your best bet is to ask on the appropriate forums or look on their website for more information. I have no experience with gmail attachments and their sizes.

**Comment by quangvinh1305** [comment]
Thanks
