### ISSUE TITLE
[ HELP WANTED ]  Implementing IMAP in react project.

### ISSUE THREAD

**Issue by rajat-np** [mscdex/node-imap#714]
I am trying to use imap library in my react project. but there is some resolve error in the imap library. See the error for more info.

```
ERROR in ./node_modules/imap/lib/Connection.js
Module not found: Error: Can't resolve 'net' in '/home/blizzard/drc/react-redux-registration-login-example/node_modules/imap/lib'
@ ./node_modules/imap/lib/Connection.js 2:13-27
@ ./src/imap-services/get_folder.js
@ ./src/EmailLogin/EmailLogin.jsx
@ ./src/EmailLogin/index.js
@ ./src/App/App.jsx
@ ./src/App/index.js
@ ./src/index.jsx
@ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx

ERROR in ./node_modules/imap/lib/Connection.js
Module not found: Error: Can't resolve 'tls' in '/home/blizzard/drc/react-redux-registration-login-example/node_modules/imap/lib'
@ ./node_modules/imap/lib/Connection.js 1:10-24
@ ./src/imap-services/get_folder.js
@ ./src/EmailLogin/EmailLogin.jsx
@ ./src/EmailLogin/index.js
@ ./src/App/App.jsx
@ ./src/App/index.js
@ ./src/index.jsx
@ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.jsx
```

**Comment by mscdex** [comment]
As this is a node module, it requires certain built-in node core modules. Most of these will not be possible to do from the browser, but if you're targeting some other platform you will need to find a way to provide these modules for compatibility. I can't really help you with that as I don't have any experience in that area.

**Comment by jchook** [comment]
@rajat-np want to point out [https://emailjs.org/](https://emailjs.org/), which has many low-level IMAP, etc tools for webmail in ES2015.

I also would love to have an IMAP client available from any web browser. Why doesn't this exist?!
