### ISSUE TITLE
Use [de-facto standard] `debug` module

### ISSUE THREAD

**Issue by broofa** [mscdex/node-imap#716]
https://www.npmjs.com/package/debug is a de-facto standard for turning on verbose debug logging.  IMHO, this is a better solution than the `debug` attribute on the options object.

Edit: On a related note, including password strings in log output is a security issue that should be avoided.
```
[parsing incoming] saw tagged response
==> A2 LOGIN "user@example.com" "password_in_clear_text_here"
```

**Comment by mscdex** [comment]
I'm not really interested in using the `debug` module at this point.

> On a related note, including password strings in log output is a security issue that should be avoided.

That's debatable, I've seen many cases where users have noticed typos in passwords after viewing the debug output.
