### ISSUE TITLE
Unable to move-to-Trash or delete messages in GMail

### ISSUE THREAD

**Issue by broofa** [mscdex/node-imap#717]
Sorry,  I know this isn't exactly a help forum, but I've run out of ideas.

I'm trying to get rid of messages in my Gmail inbox.  I'd be happy with either moving them to Trash or deleting them.  However, nothing I do seems to have any effect on my actual inbox state in GMail.

Here's the `imap` debug output: https://gist.github.com/broofa/a76d50ca2a4cfcbc16bcc08f1811970a .  It seems to indicate all the commands are succeeding.

At a bit of a loss.  Any thoughts?

**Comment by mscdex** [comment]
The messages don't show up as moved/deleted after you logout even?

**Comment by broofa** [comment]
You mean logout of my imap client (script), or out of GMail in the browser?  If I do a hard-refresh of the GMail webpage (even), the "deleted" messages are still there.

I've put together a SSCCE for this, here: https://gist.github.com/broofa/a37f08f3693644160ee1fe0b6dbccd7e/edit

When I run the above script using `EMAIL=<my email> PASSWORD=<my password> node gmaul_sscce.js`, I get the following: https://gist.github.com/broofa/cab964d85a73254555bcf812425c4383

I.e. everything _appears_ to work as expected there.  But when I go to GMail and reload the page, all of the messages the script says are being deleted  (see "Trashing ..." log lines) are still in my Inbox.  :-/

**Comment by mscdex** [comment]
I don't have any suggestions other than maybe try deleting a smaller number in a single go? I haven't seen this particular issue with gmail before.

**Comment by broofa** [comment]
Ah, figured it out.   I needed to use `attributes.uid` instead of the `seqNo`.  Sorry for the bother.

And for anyone else coming along, here's the working form of my script: https://gist.github.com/broofa/7da109334c70c5234995c1be89a9ceff
