### ISSUE TITLE
working with message uids only instead of seqno

### ISSUE THREAD

**Issue by s4ms3pi0l** [mscdex/node-imap#719]
hey, 

first of all, thank you for developing this great module, it´s working like a charm.
but i want to work only with the message uids instead of the seqno. please have a look at the following code:
```javascript
 			var msgUid;
                        var f = imap.fetch(results, {bodies: ''});
                        f.on('message', function (msg, seqno) {

                            msg.once('attributes', function (attrs) {
                                msgUid = attrs.uid;
                                console.log('attributes msgUid=' + msgUid);
                            });

                            msg.on('body', function (stream, info) {

                                var parser = new MailParser();
                                parser.once("end", function (msg) {
                                    console.log('parser.once(end) msgUid=' + msgUid);
                                    //parse header and mail body
                                    //save header and mail body to db
                                });

                                stream.on("data", function (chunk) {
                                    parser.write(chunk.toString("utf8"));
                                });
                            });
```

the console.log function gives the follwing output:

attributes msgUid=24409
attributes msgUid=24410
parser.once(end) msgUid=24410
attributes msgUid=24412
attributes msgUid=24448
parser.once(end) msgUid=24448
parser.once(end) msgUid=24448
parser.once(end) msgUid=24448
attributes msgUid=24455
parser.once(end) msgUid=24455

as you can see, the message uids from the two events are mixed together and out of sync.
what do i have to do that the uids are always identical in the two events and so that the console output maybe looks like this:

attributes msgUid=24409
parser.once(end) msgUid=24409
attributes msgUid=24410
parser.once(end) msgUid=24410
attributes msgUid=24411
parser.once(end) msgUid=24411
...

thanks for your help!

**Comment by mscdex** [comment]
Move your `msgUid` definition to the inner scope (the `'message'` event handler).
