### ISSUE TITLE
No supported authentication method(s) available error.

### ISSUE THREAD

**Issue by awcchungster** [mscdex/node-imap#726]
I set up 2FA on my Gmail account, and app specific password for my test script.

I'm getting the following error:

`No supported authentication method(s) available. Unable to login.`

The error is still there even if I turn off 2FA and use my real password. Anyone know if this is a bug?

Imap Version: 0.8.19
Node Version: v8.11.3

**Comment by mscdex** [comment]
Perhaps OAuth2 is required for your account? You can try this via the `xoauth2` config option.

**Comment by awcchungster** [comment]
I enabled debug mode, and I don't think I'm limited to xoauth2

```
<= '* OK Gimap ready for requests from 71.198.162.89 i9-v6mb3261845ocr'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH'
```

**Comment by mscdex** [comment]
What does the rest of the log show when the authentication fails?

**Comment by awcchungster** [comment]
```
<= 'A0 OK Thats all she wrote! i9-v6mb3261845ocr'
{ Error: No supported authentication method(s) available. Unable to login.

```

**Comment by mscdex** [comment]
And you have `user` and `password` set in your connection config object to non-empty strings?

**Comment by awcchungster** [comment]
The password is an app specific password, but yes.

My code is basically right off the documentation:

```
var imap = new Imap({
	user:  process.env.GOOGLE_USER,
	pass: process.env.GOOGLE_PASS,
	host: 'imap.gmail.com',
	port: 993,
	tls: true,
	debug: (debug) => {
		console.log(debug)
	}
});

```

**Comment by mscdex** [comment]
It should be `password` and not `pass`.

**Comment by awcchungster** [comment]
Oh wow, that was trivial. I'm now getting the following error. I have 2FA on, so it doesn't let me open access to less secure devices, but since I'm using an app password, it shouldn't matter. Any thoughts?

`<= 'A1 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)'
`

Thanks!

**Comment by mscdex** [comment]
I believe the only way to use plaintext passwords with gmail is if the "less secure" setting is enabled on the account. Otherwise you have to use something like OAuth2 as I indicated earlier.

**Comment by Arbaz-20** [comment]
npm install https://github.com/mscdex/node-imap/tarball/master same error here and i have configured everything properly plz help

**Comment by Arbaz-20** [comment]
No supported authentication method(s) available. Unable to login. 

this is the error

**Comment by rcffc** [comment]
> It should be `password` and not `pass`.

I had a different error but this comment saved me, thanks 🎉

**Comment by Vastradamus** [comment]
> 

Have you ever managed to solve this issue?

**Comment by im-kent** [comment]
Just checking in here from 2024. Changing "pass" to "password" actually fixed the same error message ("No supported authentication method(s) available"). I wonder why the documentation suggests using "pass"...maybe it works for other applications?

```
var imap = new Imap({
	user:  process.env.GOOGLE_USER,
	//pass: process.env.GOOGLE_PASS, //This doesn't work
	password: process.env.GOOGLE_PASS, //This works
	host: 'imap.gmail.com',
	port: 993,
	tls: true,
	debug: (debug) => {
		console.log(debug)
	}
});
```
