### ISSUE TITLE
How can i save Email Attachments to Filesystem?

### ISSUE THREAD

**Issue by PortScanner** [mscdex/node-imap#727]
Please help!

**Comment by mscdex** [comment]
One option is to download the entire raw email message and parse it locally (this could be wasteful if there are other parts to the email -- e.g. attachments -- that are large and you do not wish to keep).

You could also fetch the message structure *first* (which describes each part of the email) and then fetch just the parts you want. The message structure object is detailed in the readme. There is also an example [here](https://github.com/mscdex/node-imap/issues/398#issuecomment-47406538) that shows navigating this structure to find the first text/plain or text/html part and retrieving that. You could try adapting that to your needs.
