### ISSUE TITLE
How to search emails to myself and unseen?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#730]
Hi Developers,
I wanna search emails to myself and unseen. The param i attached in the picture.
Please help

![image](https://user-images.githubusercontent.com/6763141/47552981-2360bc80-d930-11e8-9259-eca8a5b6820b.png)

Thanks,
Vinh

**Comment by mscdex** [comment]
I'm not sure what the question is here, it seems you already have a solution?

Although it seems like you probably just want `[ ["TO", "...."], "UNSEEN" ]` if you have a single address.
