### ISSUE TITLE
Timed out while authenticating with server

### ISSUE THREAD

**Issue by chandnisoni** [mscdex/node-imap#736]
Timed out while authenticating with server:
`Error: Timed out while authenticating with server`
`at Object._onTimeout (/app/node_modules/imap/lib/Connection.js:137:17)`
`at Timer.list.ontimeout (timers.js:101:19)`

For context I am trying to connect to icloud:
`var imap = new Imap({
    user: 'xxxxx',
    password: 'xxxxx',
    host: 'imap.mail.me.com',
    port: 993,
    ssl: true,
    authTimeout: 30000
  });`

**Comment by mscdex** [comment]
It's `tls: true`, not `ssl: true`.

**Comment by chandnisoni** [comment]
@mscdex Thanks.
My actual problem is this seems: https://stackoverflow.com/questions/53344470/node-imap-lib-is-throwing-authentication-failed-error
Can you direct me in right direction. I am pretty new to imap. Thanks
