### ISSUE TITLE
'A5 BAD Could not parse command' when i try to fetch gmail certain folders

### ISSUE THREAD

**Issue by HazemElAgaty** [mscdex/node-imap#739]
I am using node-imap for a while to fetch messages from my gmail inbox and sent mail box. Today I tried to add a new folder (gmail label) to gmail, when i listed all the boxes the newly created folder name was returned sucessfully. However, when I tried to fetch messages from that folder i got this error 'A5 BAD Could not parse command'.

<img width="916" alt="screen shot 2018-11-28 at 3 22 21 pm" src="https://user-images.githubusercontent.com/17452220/49154626-8d022b00-f321-11e8-88ee-9dd551304d52.png">

The folder name is called Test as shown in the debug. Also I am using the same function I used to fetch the inbox and the sent mail. 
`imap.once("ready", function() {
  imap.openBox("Test", true, function(err, box) {
    ...
  })  
});`

Would you please tell me what I am missing.

**Comment by mscdex** [comment]
Sequence numbers have to be non-zero. My guess is that's why the server is rejecting the fetch request.

**Comment by HazemElAgaty** [comment]
Thank you it worked. I was paginating on my other two boxes and never tried the 0 seq number their, so maybe that's why.
