### ISSUE TITLE
Error: Timed out while connecting to server

### ISSUE THREAD

**Issue by s4ms3pi0l** [mscdex/node-imap#742]
I am fetching mails from multiple accounts.

The imap error event sometimes says "Error: Timed out while connecting to server" and sometimes he can sucessfully log in to the accounts and fetch mails. The timeout takes longer (about 10 secs) as stated in my config.

I have checked this accounts in Mozilla Thunderbird and he can always login to the accounts successfully. My internet connection also works properly.

So what means the error "Error: Timed out while connecting to server" (is this a special error message from node-imap) and how can I avoid it?

My config for the accounts:
```
 var imap = new Imap({
            user: mail,
            password: pw,
            host: host,
            port: 993,
            tls: true,
            authTimeout: 5000,
        });
```

**Comment by mscdex** [comment]
You can increase the default `connTimeout` of 10 seconds to whatever you want/need. Specify the value in milliseconds like `authTimeout`.

**Comment by s4ms3pi0l** [comment]
I have increased the connTimeout to 20 seconds and tried again. Still the same. But sometimes login/fetching works and sometimes not, so i think the problem is with the accounts/mail providers. 
Thank you for your help, issue can be closed.
