### ISSUE TITLE
(Solved) Unable to decode a string after using IMAP with Uri.EscapeDataString(String) Method

### ISSUE THREAD

**Issue by bennymeade** [mscdex/node-imap#743]
Hello, our developers are encoding a URL containing an email and code using **.Net Uri.EscapeDataString(String) Method** https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring?view=netcore-2.1

When I then inspect element in chrome html, the email and code are displayed in a usable format as:

`href="https://testwebsite.net/verify?email=tester%40test.com&code=CfDJ8MP2ppy%2FllhPmLj8nDAuJCJZmVdoCPzUfiyxvSYJDUtzWQiwe6yfiQk%2FMVA3FOrAXcelByDaEOv1nwDxWNrsCSQGK2VVf0%2BeL9sPjqE0xZ4hBk4lqgtLU8dezmWY%2FVScDX9Xrt%2B8Iw3OzRYPLHgUy%2Bgxql4VThJOl1ZlzBliDKKEPOW8GFaOoR5dfDCFeK2Ve6E1VTCnIT%2BzSECzZzPJVhQ7ZvlJQCPVyGiIDoCdz7UEolH8Rk18RL4cKiOGXXQ%3D%3D"`

I then run my IMAP code:

```
var Imap = require('imap'),
    inspect = require('util').inspect;

var imap = new Imap({
  user: 'xxx@gmail.com',
  password: 'xxx',
  host: 'imap.gmail.com',
  port: 993,
  tls: true
});

function openInbox(cb) {
  imap.openBox('INBOX', true, cb);
}

function getLatestMessage(cb) {
  imap.once('ready', function() {
    openInbox(function(err, box) {
        if (err) throw err;
        var f = imap.seq.fetch(box.messages.total + ':*', { bodies: ['TEXT'] });
        f.on('message', function(msg, seqno) {
          console.log('Message #%d', seqno);
          var prefix = '(#' + seqno + ') ';
          msg.on('body', function(stream, info) {
            var buffer = '', count = 0;
            stream.on('data', function(chunk) {
              count += chunk.length;
              buffer += chunk.toString('utf8');
            });
            stream.once('end', function() {
              if (info.which !== 'TEXT')
                console.log(prefix + 'Parsed header: %s', inspect(Imap.parseHeader(buffer)));
              else
                console.log(prefix + 'Body [%s] Finished', inspect(info.which));

              cb(buffer);
            });
          });
        });
        f.once('error', function(err) {
          console.log('Fetch error: ' + err);
        });
        f.once('end', function() {
          console.log('Done fetching latest Gmail!');
          imap.end();
        });
      });
  });

  imap.once('error', function(err) {
    console.log(err);
  });

  imap.once('end', function() {
    console.log('Connection ended');
  });

  imap.connect();
}

module.exports = { getLatestMessage: getLatestMessage };
```

And this returns the email and code in an unusual encoded format:

```
href=3D"https://testwebsite.net/verify=
?email=3Dtester%40mailinator.com&code=3DCfDJ8Bsg1G7jyZ1Nk6vdvKE6Ohap=
hnx0RlE21t1zaPwSS4bLtueZT7aNOQLHDqmYONTs8gRXj0kdFcXI6lKkY2NvUlJ8b%2BQU=
yeHKoZdDb97zswy5Rq7gB5YMxgaKauREypO2e7NKyxEhgqUbYFogKdi8hu8ReuluYu7DR%2FqqW=
TKIiOGTc4RsD7FuGS8EUtyA1AOCkxpy6TlyYmtk6tlvSC2g6BUjyH0Ykixp86O0kFLuvMhkVBzV=
TQiYlcxobCxug%3D%3D"
```

I then try to decode with **decodeURIComponent** but it cannot decode the IMAP response, it just spits out the same string as IMAP with those unusual 3D's listed at the beginning of the email and code strings and is in unknown encoded type to me! 

Can you help me understand if I can in-fact decode this after IMAP has been run or is this a restriction of some sort within the current IMAP version?

**Comment by mscdex** [comment]
The "unusual 3D's" are there because that part's content-type is most likely [quoted-printable](https://en.wikipedia.org/wiki/Quoted-printable). You can probably verify this by checking the part's structure (by setting `struct: true` in the `fetch()` and checking the `.struct` value inside an `'attributes'` event handler on the message object).

**Comment by bennymeade** [comment]
You are correct. Setting `struct: true` returns **Content-Transfer-Encoding: quoted-printable** in the response. I then used [Node quoted-printable](https://www.npmjs.com/package/quoted-printable) to successfully decode my URL string. A massive thank you.
