### ISSUE TITLE
Search email in children folder

### ISSUE THREAD

**Issue by Adibla** [mscdex/node-imap#744]
Hi, I didn't find any information about how retrieve email inside a children folder in my inbox using node-imap library. This is my inbox structure:

```
INBOX
 CHILDREN
   CHILDREN2
```
I must retrieve all email in Children2. 
Thanks for your attention. I’m looking forward to your reply..

**Comment by mscdex** [comment]
`getBoxes()` will return an object describing the mailbox hierarchy, including the delimiters used for each level (typically `'/'`). So if the typical delimiter is used, you would pass something like `'INBOX/CHILDREN/CHILDREN2'` to `openBox()`.

**Comment by Adibla** [comment]
> `getBoxes()` will return an object describing the mailbox hierarchy, including the delimiters used for each level (typically `'/'`). So if the typical delimiter is used, you would pass something like `'INBOX/CHILDREN/CHILDREN2'` to `openBox()`.

I already tried this approach, this is my response from getBoxes --> 

```
{ INBOX:
   { attribs: [ '\\HasChildren' ],
     delimiter: '.',
     children: { '2018': [Object], '2019': [Object] },
     parent: null } }
```

Then "openBox("INBOX.2019") return  "Error: Mailbox doesn't exist: INBOX.2019"

**Comment by mscdex** [comment]
If you inspect the `2019` object, what does it show?

**Comment by Adibla** [comment]
Sorry for the delay, I found the problem, my folder structure is more complicated than i thought:
```
{ INBOX:
   { attribs: [ '\\HasChildren' ],
     delimiter: '.',
     children: { 
         '2018':  { 
              attribs: [ '\\HasChildren' ],
              delimiter: '.',
              children: { '01': [Object], '02': [Object], ecc... },
          },
         '2019':  { 
              attribs: [ '\\HasChildren' ],
              delimiter: '.',
              children: { '01': [Object], '02': [Object], ecc... },
          }
     parent: null } }
```

Maybe the error that I've received is not completely correct "Mailbox doesn't exist", because Mailbox exist, but it has children.
Thank you for your reply.

**Comment by mscdex** [comment]
Yes, that is very likely.
