### ISSUE TITLE
unable to connect to gmail IMAP

### ISSUE THREAD

**Issue by AdarshKumarGM** [mscdex/node-imap#750]
I am unable to connect to the INBOX of my gmail account. When I try to print the state of IMAP, it always displays as "disconnected".

var Imap = require('imap');
var imapConnection = new Imap({
    username: '<gmail username>',
password: '<gmail password>',
host: "imap.gmail.com",
port: 993,
debug: console.log
});
function testemail(){
    imapConnection.connect();
    if(imapConnection.state == 'authenticated'){
        console.log('yay authenticated')
    }
    else{
        console.log('No success:'+imapConnection.state)
    }
}

Output display:

No success:disconnected
․[connection] Connected to host

I am confused as why it says that it connected to host when I print the state, it says as "Disconnected" ?

**Comment by mscdex** [comment]
I/O in node.js is generally handled asynchronously. Because of this, the underlying socket for the IMAP connection is not connected immediately after calling `connect()` like you might expect in platforms with synchronous network I/O.

**Comment by AdarshKumarGM** [comment]
Okay. Can you please provide me some example for this? I am trying to figure out this from few days.

**Comment by mscdex** [comment]
There are examples in the readme. Most importantly, you're missing `tls: true` in your connection config because port 993 is a TLS-based IMAP connection.

**Comment by AdarshKumarGM** [comment]
Okay. This is the new thing I tried and I still get the error "ErrorError: Not authenticated". Can

```
var Imap = require('imap'),
    inspect = require('util').inspect;
 
var imap = new Imap({
  user: '',
  password: '',
  host: 'imap.gmail.com',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false }
});
 
function openInbox(cb) {
  imap.openBox('INBOX', true, cb);
}
imap.once('ready', function() {
  openInbox(function(err, box) {
    if (err) throw err;
    imap.search([ 'ALL' ,['SUBJECT','Test-Test']], function(err, results) {
      var messages = [];
     
      if (err) throw err;
      var imapFetch = imap.fetch(results, {
        id: 1,
        bodies: [ 'HEADER.FIELDS (FROM TO SUBJECT)', '1','2'],
        struct: true
      });
     
      imapFetch.on('message', function(msg, seqno) {
        //console.log('Message #%d', seqno);
        var body = ''
          , header = ''
          , parsedMsg = {}
         
        var prefix = '(#' + seqno + ') ';
       
        msg.on('body', function(stream, info) {
          //console.log(prefix + 'Body');
          var buffer = '', count = 0;
         
         if (info.which === 'TEXT' || info.which === '1.TEXT' ) {
            stream.on('data', function(chunk) { body += chunk.toString('utf8') })
            stream.once('end', function() { parsedMsg.body = body })
          } else {
            stream.on('data', function(chunk) { header += chunk.toString('utf8') })
            stream.once('end', function() { parsedMsg.header = Imap.parseHeader(header) })
          }
         
        });
       
        msg.once('attributes', function(attrs) {
          //console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
          parsedMsg.attrs = attrs;
        });
       
        msg.once('end', function() {
          console.log(prefix + 'Finished');
          messages.push( parsedMsg );
        });
      });
      imapFetch.once('error', function(err) {
        console.log('Fetch error: ' + err);
      });
      imapFetch.once('end', function() {
        console.log('Done fetching all messages!');
        for( i in messages ) {
          console.log( i + ': ' + inspect( messages[i], false, 4 ) );
        }
        imap.end();
      });
    });
  });
});
 
imap.once('error', function(err) {
  console.log(err);
});
 
imap.once('end', function() {
  console.log('Connection ended');
});
 
imap.connect();

```

**Comment by mscdex** [comment]
You should not use `tlsOptions: { rejectUnauthorized: false }` as it opens you up to possible MITM attacks.

Also,  you need to fill in the appropriate username and password. Other than that, it should work fine.
