### ISSUE TITLE
How to send a message in draft folder?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#751]
Hi developers,
I have a message with the size 80mb in draft folder(My mail server config allow send email with larger size).
How do i send an imap command to mail server to ask mail server send it and then move it to inbox folder.

Thanks you,
Vinh

**Comment by mscdex** [comment]
You have to use SMTP to send messages as IMAP does not handle message sending. You would need to download the draft email via IMAP and send it via SMTP.
