### ISSUE TITLE
search from not behaving as expected

### ISSUE THREAD

**Issue by umasudhan** [mscdex/node-imap#752]
server: Exchange 2007
This does not work:
```
imap.search(['ALL',['FROM','someemail@somemail.com']],function(err,uids){
    console.log(uids);
});
```
The following works partially in that I get results for the from field. However it also searches the CC field for 'someemail@somemail.com' which I don't expect. 
```
imap.search(['ALL',['HEADER', 'FROM','someemail@somemail.com']],function(err,uids){
    console.log(uids);
});
```
Could you please help me out?

**Comment by mscdex** [comment]
Both should work. Are you sure you're in the right mailbox on the right account?

If so, it's most likely an issue with the server implementation if it can be verified via other means that one or more emails with that 'From' address exists in the opened mailbox on that account.

**Comment by umasudhan** [comment]
this was a server issue- have worked around it.
