### ISSUE TITLE
File with small size (453 bytes) is getting saved with no Data

### ISSUE THREAD

**Issue by schundawat5** [mscdex/node-imap#754]
I am trying to download an attachment using this module. 
I am able to download all other files properly, but there is one file which is of size around 453 bytes and has some data in it , is getting downloaded with no data in it.
When I open that file I see no data and size is also 0 Kb.
Please help...

**Comment by schundawat5** [comment]
Anyone has any idea or comments?

**Comment by mscdex** [comment]
You're using the wrong function on line 40 of your script.

**Comment by schundawat5** [comment]
Here is the part of my script which downloads attachment from mail
--------------------


function buildAttMessageFunction(attachment) {
	var filename = attachment.params.name;
	var encoding = attachment.encoding;

	return function(msg, seqno) {
		var prefix = '(#' + seqno + ') ';
		msg.on('body', function(stream, info) {
			//Create a write stream so that we can stream the attachment to file;
            console.log(prefix + 'Streaming this attachment to file', 'FileLocation', info);
			var writeStream = fs.createWriteStream('FileLocation');
			writeStream.on('finish', function() {
				console.log(prefix + 'Done writing to file %s', 'FileLocation');
                saveFile('FileLocation');
			});

			//stream.pipe(writeStream); this would write base64 data to the file.
			//so we decode during streaming using
			if (encoding === 'BASE64') {
				//the stream is base64 encoded, so here the stream is decode on the fly and piped to the write stream (file)
				stream.pipe(base64.decode()).pipe(writeStream);
			} else {
				//here we have none or some other decoding streamed directly to the file which renders it useless probably
				stream.pipe(writeStream);
			}
		});
		msg.once('end', function() {
			console.log(prefix + 'Finished attachment %s', '/var/sftp/symantec/dlp/' + filename);
		});
	};
}

function saveFile(filename) {
	console.log('Starting saveFile...');
	var base64Data = fs.readFileSync(filename, 'utf-8');
	fileBase64.decode(base64Data, filename, function(err, output) {
        if (err) console.log(err);
	});
}

function openInbox(cb) {
	imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
	openInbox(function(err, box) {
		if (err) throw err;
		imap.search(
			[
				[ 'SINCE', 'Some date'],
				[ 'SUBJECT', 'Some subject']
			],
			function(err, results) {
				var f = imap.fetch(results, {
					bodies: [ 'HEADER.FIELDS (FROM TO SUBJECT DATE)' ],
					struct: true
                });
                
                console.log("Results ==> " + results);

				f.on('message', function(msg, seqno) {
					console.log('Message #%d', seqno);
					var prefix = '(#' + seqno + ') ';
					msg.on('body', function(stream, info) {
						var buffer = '';
						stream.on('data', function(chunk) {
							buffer += chunk.toString('utf8');
						});
						stream.once('end', function() {
							console.log(prefix + 'Parsed header: %s', Imap.parseHeader(buffer));
						});
					});
					msg.once('attributes', function(attrs) {
						var attachments = findAttachmentParts(attrs.struct);
						console.log(prefix + 'Has attachments: %d', attachments.length);
						for (var i = 0, len = attachments.length; i < len; ++i) {
							var attachment = attachments[i];
							console.log(prefix + 'Fetching attachment %s', attachment.params.name);
							var f = imap.fetch(attrs.uid, {
								bodies: [ attachment.partID ],
								struct: true
							});
							//build function to process attachment message
							f.on('message', buildAttMessageFunction(attachment));
						}
					});
					msg.once('end', function() {
						console.log(prefix + 'Finished email');
					});
				});
				f.once('error', function(err) {
					console.log('Fetch error: ' + err);
				});
				f.once('end', function() {
					console.log('Done fetching all messages!');
					imap.end();
				});
			}
		);
	});
});

imap.once('error', function(err) {
	console.log(err);
});

imap.once('end', function() {
	console.log('Connection ended');
});

imap.connect();

**Comment by mscdex** [comment]
One issue is you're overwriting the value of `f` within the event handler, which could be causing problems. Try using a different name either in the parent scope or inside your loop.

Also, have you tried just writing the base64 data to the file to check if the base64 decoder is to blame?

**Comment by schundawat5** [comment]
Thanks for pointing out "One issue is you're overwriting the value of f within the event handler".
Just renamed it and now all good
