### ISSUE TITLE
Click on link in email using message parts

### ISSUE THREAD

**Issue by AdarshKumarGM** [mscdex/node-imap#756]
Hello,

I am trying to click on a HTML link displayed in my email body. I am able to retrieve the message parts such as this:

> Done fetching all messages!
0: { header:
   { from: xxxx@xxxxx.com,
     to: yyyyy@yyyy.com,
     subject: Test},
  attrs:
   { struct:
      [ { type: 'alternative',
          params:
           { boundary: '--==_mimepart_5c889b3fd36c_46d2a1de845225',
             charset: 'UTF-8' },
          disposition: null,
          language: null },
        [ { partID: '1',
            type: 'text',
            subtype: 'plain',
            params: [Object],
            id: null,
            description: null,
            encoding: '7BIT',
            size: 672,
            lines: 14,
            md5: null,
            disposition: null,
            language: null } ],
        [ { partID: '2',
            type: 'text',
            subtype: 'html',
            params: [Object],
            id: null,
            description: null,
            encoding: '7BIT',
            size: 1504,
            lines: 31,
            md5: null,
            disposition: null,
            language: null } ] ],
     date: 2019-03-13T05:55:11.000Z,
     flags: [],
     uid: 102408,
     modseq: '6535141',
     'x-gm-labels': [ '\\Important' ],
     'x-gm-msgid': '1627868638473910311',
     'x-gm-thrid': '1627868222319883033' } }

I have part 2 here displaying as HTML for "subtype". How do I parse it/verify the link name and click on it based on my preference?

Can you please help

**Comment by mscdex** [comment]
I'm not sure what you're asking exactly, but I'm guessing the "link" you're looking for is in that part's body, so you will need to fetch that specific part for that message.

**Comment by AdarshKumarGM** [comment]
Hi Mscdex,

Yeah, I am looking at clicking on a link inside the parts body. How do I fetch it. I am very new to this and require your help.

Can you please help in providing a solution to fetch the "subtype:html".

**Comment by mscdex** [comment]
Just use the part ID as the value in the `bodies` property passed to `fetch()`. You can optionally use the different values shown in the documentation for `fetch()` as suffixes to only fetch particular portions of that part (e.g. header only, body only, header + body, etc.), for example: `'2.TEXT'`.

**Comment by AdarshKumarGM** [comment]
Okay, thank you very much mscdex. Just one last question, does "window.open()" also work in here, when I parse the part ID for HTML and after retrieving it, can it be passed into the function and open the URL?

**Comment by mscdex** [comment]
I can't really answer that, whatever you want to do with the content of the email is up to you.

**Comment by AdarshKumarGM** [comment]
Okay, Thank you.
