### ISSUE TITLE
how to run fetch function in synchronous

### ISSUE THREAD

**Issue by vigneshtharani** [mscdex/node-imap#757]
How to run the fetch.on message and end function in synchronously, while it runs on asynchronous process, so in end function I am get data empty before message function runs, how to fix this!

**Comment by mscdex** [comment]
You can't. Node in general has asynchronous I/O. About the closest you could get is if you created a wrapper that used `async`/`await` and Promises to make asynchronous operations appear synchronous. That would be up to you to implement however.

**Comment by vigneshtharani** [comment]
f.on("message", function(msg, seqno){
			     		var buffer;
				    	var parser = new MailParser();
				    	msg.on("body", function(stream) {
				        	stream.on("data", function(chunk) {
				            	parser.write(chunk.toString("utf8"));
				            	buffer += chunk.toString('utf8'); 
				        	});
				    	});
				    	msg.once("end", function() {
				     		parser.on('data', data => {
					        	if (data.type === 'text') {
					            	var msg = data.text;
						            var parseBuffer = Imap.parseHeader(buffer);
						            var from  = parseBuffer.from[0];
						            var to = parseBuffer.to[0];
						            var subject = parseBuffer.subject[0];
						            var date = parseBuffer.date[0];
						            var description = subject + '\n\n' + msg;
						            var splitEmail = from.split('<')[1].replace(/>/g, '');
						            console.log(splitEmail, 'splitEmail');			            
					        	}
					     	});					       
					     	parser.end();
				    	});
			     	});

			    	f.once('error', function(err) {
			      		console.log('Fetch error: ' + err);
			    	});

			    	f.on("end", function() {
			      		console.log(emailIds, 'emailIds end function'); 
			      		console.log('Done fetching all messages!');
			      		imap.end();
			    	});

Here "end" function fires soon, so not able to get all values in array, did I miss anything here?
