### ISSUE TITLE
Attributes based search 

### ISSUE THREAD

**Issue by ahmedisam99** [mscdex/node-imap#765]
@mscdex 
How do I search through emails based on something that only exists in the attributes (e.g. x-gm-thrid)?

**Comment by mscdex** [comment]
For gmail specifically, just use the [documented](https://github.com/mscdex/node-imap#extensions-supported) `'X-GM-THRID'` search criteria when using `.search()`. If you're wanting to search headers in general, you can use `'HEADER'`.
