### ISSUE TITLE
imap.fetch() VS imap.seq.fetch()

### ISSUE THREAD

**Issue by ahmedisam99** [mscdex/node-imap#766]
What's the difference between `imap.seq.fetch()` and `imap.fetch()` ??

**Comment by mscdex** [comment]
From the readme:

```
All functions below have sequence number-based counterparts that can be accessed by using the 'seq' namespace of the imap connection's instance (e.g. conn.seq.search() returns sequence number(s) instead of UIDs, conn.seq.fetch() fetches by sequence number(s) instead of UIDs, etc):
```

**Comment by ahmedisam99** [comment]
@mscdex   
Actually I knew that in advance but I had a problem fetching emails and I suspected the fetch method i was using so I decided to ask here in case there are somethings else.
