### ISSUE TITLE
read only calendar events - exchange server

### ISSUE THREAD

**Issue by shashi004** [mscdex/node-imap#772]
Hi,

Am able to connect and pull emails from microsoft exchange server and gmail imap server using nodejs imap library.

But

    1. how can i read/pull only calendar events (not required normal emails).
    2. how can i read/parse the complete event data such as From address, To address (participants), event location, from datetime and end datetime etc., as microsoft exchange server calendar event is different than gmail calander event

Please share the sample script, if possible :)

Thanks in advance.

**Comment by shashi004** [comment]
requirement is to read only calendar events from email server and show it in our web application under user dashboard.

reading all emails, finding content type as "application/calendar" in headers (to filter calendar events) is a bit lengthy process waste of time to process all the records.

**Comment by mscdex** [comment]
That's outside of the scope of this issue tracker. You might ask on StackOverflow or on the [nodejs/help issue tracker](https://github.com/nodejs/help/issues) instead.

**Comment by shashi004** [comment]
Thanks for the reply. :)
