### ISSUE TITLE
Retrieve UID from SEQNO

### ISSUE THREAD

**Issue by gustavohstrassburger** [mscdex/node-imap#776]
Hey there,

I'm facing an issue that I do not know how to solve at this point.
I need to sync the flags (mostly if the email was seen) between my application and the email server.
To do so, I'm listening to the update event, however, I do not keep track of the SEQNO, only the UID, but this event doesn't seem to give me such information.

Do you have any suggestions on how to proceed?

Thanks in advance.

**Comment by mscdex** [comment]
You would need to `fetch()` by sequence number with just the basics (no bodies for example) to get the new flags and the UID.

**Comment by gustavohstrassburger** [comment]
I see, and is it possible to filter a specific SEQNO like I do it with the UID on the search method?

E.g:
``['UID', `${uidvalidity}:*`]``

Thanks so much.

**Comment by mscdex** [comment]
Since you already have the sequence number from the `'update'` event, you can just pass that to `imap.seq.fetch()`.

**Comment by gustavohstrassburger** [comment]
Thanks, It worked.
