### ISSUE TITLE
Get all conversations  between two mail

### ISSUE THREAD

**Issue by johnDivek** [mscdex/node-imap#777]
example:
- abc@gmail.com -> xyz@gmail.com
   Data : Hi how are you
       - xyz@gmail.com -> abc@gmail.com
           Data : Hi I am fine
               - abc@gmail.com -> xyz@gmail.com
                  Data : having a cool day ?
                           - xyz@gmail.com -> abc@gmail.com
                               Data : Man it's hot here lol

**Comment by johnDivek** [comment]
> If the server supports the `THREAD=REFERENCES` capability, you can use `imap.thread()` as described in the readme. If the server is gmail (supports the `X-GM-EXT-1` capability), then you will automatically get thread IDs when fetching messages and you can search by thread id (this is also described in the readme).

**Comment by venky0195** [comment]
Can you please post an example of how to use imap.thread()?
