### ISSUE TITLE
Server does not support that threading algorithm

### ISSUE THREAD

**Issue by tecnodev** [mscdex/node-imap#781]
I have tried to test server capability  `imap.serverSupports('THREAD=ORDEREDSUBJECT')` but it returns `undefined ` 

if the server does not support threading means, how can I handle this, suggest me any possible solutions

**Comment by mscdex** [comment]
`serverSupports()` should only be used once the `'ready'` event has been fired and the connection is still valid.

If the server doesn't support threading natively, then you will have to develop your own algorithm on email message metadata to determine the threading appropriately. The descriptions of the algorithms used by the IMAP threading extensions can be viewed in [the relevant RFC](https://tools.ietf.org/html/rfc5256).
