### ISSUE TITLE
forbidden by email server

### ISSUE THREAD

**Issue by Ben07** [mscdex/node-imap#782]
I use `imap` to access outlook or Yandex mail ,but some days later.they not allow me to access. how to avoid it?

> Access to your account has been temporarily restricted as Yandex suspects it may have been hacked. 
This may have happened because you have entered your password on a fraudulent website or because your computer is infected with a virus.

**Comment by mscdex** [comment]
That's outside the scope of this module. You will have to send a support request to the specific email provider.
