### ISSUE TITLE
imap.fetch('*') only returning 1 message.

### ISSUE THREAD

**Issue by Aurailus** [mscdex/node-imap#784]
Hi, I'm having a really frustrating issue. I'm using the following code to `fetch` all of the messages from the inbox of an account:

```
imap.openBox('INBOX', false, (err: any, box: any) => {
    let f = imap.fetch('*');
    f.on('message', (msg: any, uid: number) => {
        console.log(uid);
    });
    f.once('end', () => console.log('all done'));
})
```

And it's only logging one uid. And then triggering the end event. 
The Inbox has 3 messages in it, so there should be 3 log events, right?

I do want UIDs, not sequence numbers, just fyi. Using imap.seq.fetch isn't an answer.

**Comment by hallettj** [comment]
Try changing `imap.fetch('*')` to `imap.fetch('1:*')`. In a fetch I think `*` is interpreted as the highest UID, not as a range by itself. `1` is the lowest possible UID.

I find it helpful to refer to [RFC 4549 - Synchronization Operations for Disconnected IMAP4 Clients](https://tools.ietf.org/html/rfc4549) for advice on writing fetch commands, and UID ranges are specified in [INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1](
https://tools.ietf.org/html/rfc4549):


> seq-range       = seq-number ":" seq-number
                    ; two seq-number values and all values between
                    ; these two regardless of order.
                    ; Example: 2:4 and 4:2 are equivalent and indicate
                    ; values 2, 3, and 4.
                    ; Example: a unique identifier sequence range of
                    ; 3291:* includes the UID of the last message in
                    ; the mailbox, even if that value is less than 3291.

**Comment by mwalden2004** [comment]
This is not solving the problem for me.

**Comment by Aurailus** [comment]
That's working for me, thank you!
