### ISSUE TITLE
how to decode a mime base64 string

### ISSUE THREAD

**Issue by suedar** [mscdex/node-imap#785]
I am crawling my personal email by using Imap.And I get the massage body above this.
```
This is a multi-part message in MIME format.

------=_NextPart_5DC4DDFF_109DD668_3F61445F
Content-Type: text/plain;
    charset="ISO-8859-1"
Content-Transfer-Encoding: base64

ZGRk

------=_NextPart_5DC4DDFF_109DD668_3F61445F
Content-Type: text/html;
    charset="ISO-8859-1"
Content-Transfer-Encoding: base64

PGRpdj5kZGQ8L2Rpdj4=

------=_NextPart_5DC4DDFF_109DD668_3F61445F--
```
I wonder if there is a way to decode this buffer.Thanks for your help

**Comment by mscdex** [comment]
That's outside the scope of this module, however node has built-in support for base64 decoding for example (e.g. `Buffer.from(..., 'base64')`).
