### ISSUE TITLE
cannot get encoding windows-1251

### ISSUE THREAD

**Issue by XIIIcool** [mscdex/node-imap#786]
I get a letter where either the encoding is not specified or it windows-1251
And do not see the cyrillic
��������� �����
`MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1573322701287230"
X-Mailer: MIME::Lite 3.028 (F2.72; T1.34; A2.08; B3.01; Q3.01)
Date: Sat, 9 Nov 2019 22:05:01 +0400
From: 
To: 
Subject: =?windows-1251?B?UmU6IFJFOiBSRTogW0JUSyMxMTA3XS8v0tLKKNLSIDEzNTU5OTAgx8DPwMQpIElEIE1vc2Nvdy9UVMogRnJhbmtmdXJ0L0dUUCA2NFMx?=
Cc:  

This is a multi-part message in MIME format.

--_----------=_1573322701287230
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=windows-1251`

**Comment by jose123455587** [comment]
Are you using this ? https://github.com/nodemailer/mailparser
I think you must use it to decrypt email

**Comment by XIIIcool** [comment]
yes, I use it, but there are such letters from one client that are poorly recognized

**Comment by XIIIcool** [comment]
it turned out, it’s not done right yet, but it works
in the mailparser plugin comment out the decoding lines
`                    let charset = node.charset || 'utf-8';
                    //charset = charset || 'windows-1257';

                    if (!['ascii', 'usascii', 'utf8'].includes(charset.toLowerCase().replace(/[^a-z0-9]+/g, ''))) {
                        // try {
                        //     let decodeStream = this.decoder.decodeStream(charset);
                        //     node.contentStream.on('error', err => {
                        //         decodeStream.emit('error', err);
                        //     });
                        //     node.contentStream.pipe(decodeStream);
                        //     node.contentStream = decodeStream;
                        // } catch (E) {
                        //     // do not decode charset
                        // }
                    }`
and then we code in utf-8
`                    stream.on('data', (chunk) => {
                        let buf = new Buffer(chunk, 'windows-1251');
                        let conv = new Iconv('windows-1251', 'utf-8');
                        buffer += conv.convert(buf).toString('utf-8');
                    });`
how can you avoid editing mailparser?

**Comment by XIIIcool** [comment]
if you save the letter in eml and open it without node-imap, then everything is fine!
`                        const util = require('util');
                        const fs = require('fs');


                        let input = fs.createReadStream('mail.eml');

                        simpleParser(input, options = {Iconv}).then((parsedBody) => {

                            message.body = parsedBody;
                            resolve(message);

                        });`

**Comment by Rabinzon** [comment]
@nendic did you found solution ?

**Comment by nendic** [comment]
my problem was that I did not read the streaming data of the body of the letter correctly

`                messageSource.on('body', (stream) => {

                    let buffer = Buffer.from('');

                    stream.on('data', (chunk) => {
                        buffer = Buffer.concat([buffer, chunk]);
                    });

                    stream.on('end', () => {
                        message.body = buffer;
                    });

                });`
