### ISSUE TITLE
Question: Xoauth2 for Gmail (session continuance after access token expiry)

### ISSUE THREAD

**Issue by jaykumarthaker** [mscdex/node-imap#789]
Thank you so much @mscdex for this amazing library, everything is working great for me. I am using suggested library `XOauth2` and just have one question. As per the [documentation](https://developers.google.com/identity/protocols/OAuth2#4.-refresh-the-access-token,-if-necessary.), Auth2 "access token" expire after 3600 sec. (i.e. 1hr) and as per my knowledge XOauth2 doesn't seems to do anything special to handle this case (auto refresh of access tokens). Well I can say this because:
```
xoauth2gen.on("token", function(token){
    console.log("User: ", token.user); // e-mail address
    console.log("New access token: ", token.accessToken); // the access token
    console.log("New access token timeout: ", token.timeout); // TTL in seconds
});
```
is only called once.

Despite all these, connection still remains live for me even after 2hr. So, what's the magic here?

**Comment by mscdex** [comment]
I can't speak for the `xoauth2` module or really oauth2 in general, but I would assume the connection would not be severed after the token expires. AFAIK the token expiry is there to say how long you have until you can no longer log in with it.

**Comment by jaykumarthaker** [comment]
Agreed, my initial guess was the same. Appreciate for your prompt response.
