### ISSUE TITLE
gmail

### ISSUE THREAD

**Issue by melitus** [mscdex/node-imap#795]
I was able to connect and download an email attachment from the localhost. But could not connect when tried the same process when hosted on Heroku. I kept getting the response below
```
Trace: { Error: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```
This is my imap setting below
```
const imap = new Imap {
        user: imapServerSettings.username  as string,
        password: imapServerSettings.password  as string,
        host: imapServerSettings.host  as string,
        port: imapServerSettings.port as number,
        tls: imapServerSettings.tls as boolean,
}
```

**Comment by melitus** [comment]
I was able to connect and download an email attachment from the localhost. But could not connect when tried the same process when hosted on Heroku. I kept getting the response below
```
Trace: { Error: Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```

**Comment by mscdex** [comment]
Did you try the suggested troubleshooting steps at the URL? This seems like a gmail account-specific issue, not an issue with this module.

**Comment by melitus** [comment]
@mscdex Thanks for your reply.  I am not trying to infer that it is a problem with this module, This module has been so amazing. I tested downloading from Gmail on the localhost and it worked perfectly, but when I hosted on Heroku, it could not connect to the Gmail IMAP again. I would appreciate if anyone who have experimented with this on Gmail on live server could help me with a guide, Thanks

**Comment by mscdex** [comment]
My guess is that Google sees you logging in from a different IP that it doesn't recognize so it blocks access.

However I think your question might be more suitable for (and would have more eyes on it at) a place like stackoverflow or perhaps Heroku support/forums.

**Comment by melitus** [comment]
Thanks

**Comment by kaceman** [comment]
@melitus I am having the same issue here, it's working on my local machin, but when I host it on linode (ubuntu machine) I have the same error you had, is there any solution for that?
