### ISSUE TITLE
Code fails on Node 12.x ... Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by tarach** [mscdex/node-imap#797]
After switching to newer version of Node code below started giving me following error messages: 

Connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed and I get Connection error: Error: Timed out while authenticating with server

```javascript
const Imap = require('imap');
const inspect = require('util').inspect;
const fs = require('fs');

const config = require('./config');
const imap = new Imap(config);

function openInbox(cb) {
    imap.openBox('INBOX', true, cb);
}

imap.once('ready', function() {
    openInbox(function(err, box) {
        if (err) throw err;
        imap.search([ 'UNSEEN', ['SINCE', 'June 15, 2018'] ], function(err, results) {
            if (err) throw err;
            var f = imap.fetch(results, { bodies: '' });
            f.on('message', function(msg, seqno) {
                console.log('Message #%d', seqno);
                var prefix = '(#' + seqno + ') ';
                msg.on('body', function(stream, info) {
                    console.log(prefix + 'Body');
                    stream.pipe(fs.createWriteStream('msg-' + seqno + '-body.txt'));
                });
                msg.once('attributes', function(attrs) {
                    console.log(prefix + 'Attributes: %s', inspect(attrs, false, 8));
                });
                msg.once('end', function() {
                    console.log(prefix + 'Finished');
                });
            });
            f.once('error', function(err) {
                console.log('Fetch error: ' + err);
            });
            f.once('end', function() {
                console.log('Done fetching all messages!');
                imap.end();});
        });
    });
});
imap.once('error', function(err) {
    console.log(err);
});
imap.once('end', function() {
    console.log('Connection ended');
});
imap.connect();
```

> C:\Users\sebastian\AppData\Local\Microsoft\WindowsApps\debian.exe run "export PATH=/home/sebastian/.nvm/versions/node/v12.0.0/bin:$PATH && /home/sebastian/.nvm/versions/node/v12.0.0/bin/node /f/projects/sms-to-email/index.js"
> Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
>     at doWrite (_stream_writable.js:413:19)
>     at clearBuffer (_stream_writable.js:543:7)
>     at Socket.Writable.uncork (_stream_writable.js:321:7)
>     at JSStreamSocket.doWrite (internal/js_stream_socket.js:162:17)
>     at JSStream.onwrite (internal/js_stream_socket.js:20:57)
>     at Socket.ondata (internal/js_stream_socket.js:64:22)
>     at Socket.emit (events.js:196:13)
>     at addChunk (_stream_readable.js:290:12)
>     at readableAddChunk (_stream_readable.js:271:11)
>     at Socket.Readable.push (_stream_readable.js:226:10) {
>   source: 'socket'
> }
> events.js:173
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: self signed certificate
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1260:34)
>     at TLSSocket.emit (events.js:196:13)
>     at TLSSocket._finishInit (_tls_wrap.js:737:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:569:12)
>     at Socket.ondata (internal/js_stream_socket.js:64:22)
>     at Socket.emit (events.js:196:13)
>     at addChunk (_stream_readable.js:290:12)
>     at readableAddChunk (_stream_readable.js:271:11)
>     at Socket.Readable.push (_stream_readable.js:226:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
> Emitted 'error' event at:
>     at TLSSocket._onError (/f/projects/sms-to-email/node_modules/imap/lib/Connection.js:151:10)
>     at TLSSocket.emit (events.js:196:13)
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at processTicksAndRejections (internal/process/task_queues.js:83:17)
> 
> Process finished with exit code 1
> 

Error occurs only when I'm on version 12 of Node.js

**Comment by tarach** [comment]
Solved.
Added NODE_TLS_REJECT_UNAUTHORIZED=0 as node environment variable and it worked.

C:\Users\sebastian\AppData\Local\Microsoft\WindowsApps\debian.exe run "export PATH=/home/sebastian/.nvm/versions/node/v12.16.1/bin:$PATH && /home/sebastian/.nvm/versions/node/v12.16.1/bin/node /f/projects/sms-to-email/index.js"
(node:7956) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

**Comment by mscdex** [comment]
As the warning says, you shouldn't do this. You should instead set the appropriate `ca` or at the very least `cert` in options passed under `tlsOptions` when connecting. By doing so you're at least verifying that you trust that particular CA or certificate instead of anything at all (including possible attackers trying to MITM your connection).
