### ISSUE TITLE
Is there any way to retrieve and use  gmail body content in other java script class, only output

### ISSUE THREAD

**Issue by NilukaSripalim** [mscdex/node-imap#801]
Is there any way to retrieve and use  gmail body content in other java script class, only output

**Comment by mscdex** [comment]
I don't understand your question. There are examples of fetching emails in the readme though.

**Comment by NilukaSripalim** [comment]
Thanks for kind response, 
That issue was currently i am doing some test, and i want to email content/body as input for some other test.
By writing file I solve this just now, Thanks

Stay safe.
