### ISSUE TITLE
actively maintained (project status)

### ISSUE THREAD

**Issue by j3g** [mscdex/node-imap#816]
Hello. At first I thought this project was stale. Then in the Issues tracker and the PRs I see that mscdex is *VERY* active, which is AWESOME! The last modification to the code was Dec 2016. Is the code really that good that nothing needed updating since that time? I see a lot of closes PRs. I'm trying to understand the status of this project.
Thanks!
PS. I need to use this module in my electron app so i'll be taking it for a spin.

**Comment by mscdex** [comment]
It's still on the back burner. Unfortunately I don't have the free time I used to have to contribute code changes like I used to, but I am happy to answer questions/help with issues the best I can.

**Comment by j3g** [comment]
totally understand. take care.
