### ISSUE TITLE
Regarding errror [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Dsiddhesh** [mscdex/node-imap#817]
Hi Team,
We are using IMAP NPM for our application and while  batch testing we came across this error inside 'error' event. We checked on the net and concluded that this error is thrown when a server tries to send more than one response to a client. 
In our case we are unable to find out for which exact scenario we are getting this error. We are executing mix flows which has functionality like  get Email using filter, list folder, update email message etc,  We wanted to know if there is any way if we can get more insights about this error in 'error' event of IMAP or is there any way to handle it.

**Comment by mscdex** [comment]
`imap` has nothing to do with http. The error is coming from somewhere else in your code.

**Comment by Dsiddhesh** [comment]
Thanks for confirmation @mscdex , I will cross check my code.

**Comment by Dsiddhesh** [comment]
@mscdex  Could you please let me know what should be done if IMAP error is thrown on parent event when the execution of child event ( like on('message') etc) is in progress.

**Comment by mscdex** [comment]
Continued in #819.
