### ISSUE TITLE
Is it possible to create two connections to gmail and outlook at once?

### ISSUE THREAD

**Issue by ravisojitra** [mscdex/node-imap#829]
Hello, 
I have a requirement where i want to create app that let you read your all mails from different providers such as gmail,outlook, yahoo at once place.
So in this case, is it possible to fetch all mails from different providers?
If it's not possible, is it possible with design like slack where you can select one mail at one time and fetch all mails from it and store in local DB, and then in all mails workspace, i show all mails from there? So are dynamic connections possible?

**Comment by mscdex** [comment]
This is a higher-level question that is beyond the scope of this project. `imap` does not limit you to how many connections you create.

**Comment by ravisojitra** [comment]
Well, if imap doesn't limit on how many connections i create, Then it seems possible. Thanks for the answer.
