### ISSUE TITLE
Not being able to stablish connection inside AWS Lambda function

### ISSUE THREAD

**Issue by brunostc** [mscdex/node-imap#833]
Well, the title is pretty much self-explanatory, I have to use this package for scanning through a list of emails when the lambda function is invoked, but I cant even connect. 
I've tried with lambda outside VPC and inside a VPC. It doesnt work.
At my localhost I am able to perform all the actions needed, I scan unread emails, download their attachments and put the objects at the S3. Everything working great!! But when I invoke my lambda function I cant seem to connect to the imap server. The code I used is this one below (its simple because I'm stuck at the first part - connecting to gmail's imap). 
Any help is appreciated.

```js
const Imap = require('imap');

exports.handler = async(event) => {
	const payloadObj = event;

	const imap = new Imap({
		user: payloadObj.email,
		password: payloadObj.pwd,
		host: payloadObj.provider,
		port: 993,
		tls: true
	});
	
	imap.once('ready', function() {
		console.log('Connection stablished'); // never triggered
		imap.end();
	});
	
	imap.once('end', function() {
		console.log('Connection ended'); // never triggered
	});

	imap.connect();
};
```

**Comment by mscdex** [comment]
You've verified `exports.handler` is being called and that `payloadObj.provider` is the correct value? If so, I don't have any suggestions as there is nothing wrong with your code.

**Comment by brunostc** [comment]
Yes, I've set up several console.logs at the code and the `exports.handler` being called, I have also hard coded the parameters and it also doesnt work (altought the parameters and being passed correctly through `event`).

**Comment by mscdex** [comment]
Perhaps Amazon is abruptly halting the process for some reason? Briefly looking at the node.js Lambda docs, you need to return a `Promise` from your function when using the `async` keyword. Otherwise if you're just exporting a plain function handler (no `async` keyword) you have to execute the `callback` passed that is to the handler function (when you're done).

**Comment by brunostc** [comment]
If i remove the async keyword i get the following error:
```js
{
    "errorType": "Error",
    "errorMessage": "Cannot call write after a stream was destroyed",
    "code": "ERR_STREAM_DESTROYED",
    "source": "socket",
    "stack": [
        "Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed",
        "    at doWrite (_stream_writable.js:399:19)",
        "    at clearBuffer (_stream_writable.js:542:7)",
        "    at Socket.Writable.uncork (_stream_writable.js:338:7)",
        "    at JSStreamSocket.doWrite (internal/js_stream_socket.js:176:17)",
        "    at JSStream.onwrite (internal/js_stream_socket.js:33:57)",
        "    at Socket.ondata (internal/js_stream_socket.js:77:22)",
        "    at Socket.emit (events.js:314:20)",
        "    at addChunk (_stream_readable.js:297:12)",
        "    at readableAddChunk (_stream_readable.js:272:9)",
        "    at Socket.Readable.push (_stream_readable.js:213:10)"
    ]
}
```

**Comment by brunostc** [comment]
I was able to solve the issue by returning a promise and the connect function inside this promise
