### ISSUE TITLE
Get updated state of currently opened mailbox

### ISSUE THREAD

**Issue by miroslavskela** [mscdex/node-imap#843]
Hello,

one question, is it possible to get updated state of currently opened mailbox without closing that box and opening it again. Now I open one box, let's say INBOX, and I'm listening for onmail event, when that event triggers, is it possible to get info about box, at that moment. On opening box my uidnext was 100, and uidValidity was 1, and when new mail comes, i need updated uidNext value.

Thank you very much.

**Comment by mscdex** [comment]
The server does not provide updated UIDNEXT values while the box is open.
