### ISSUE TITLE
Microsoft disabling basic authentication methods

### ISSUE THREAD

**Issue by petah-sama** [mscdex/node-imap#862]
So Microsoft will disable all Basic Auth protocols, except for SMTP Auth, for Office 365 and Exchange. Is there anyway to still use this package without Basic Auth?

**Comment by mscdex** [comment]
Yes, you'd use `xoauth2` in the connection config to authenticate. However you are responsible for generating the base64-encoded xoauth2 string. There are modules on npm to help you with this or you can do it yourself manually.

**Comment by giacomobartoli** [comment]
@mscdex is there any code sample using MSAL?
https://www.npmjs.com/package/@azure/msal-node

Thanks for help

**Comment by mscdex** [comment]
@giacomobartoli  Not that I'm aware of

**Comment by giacomobartoli** [comment]
@mscdex any suggestion about how to generate the xouath2 string?
I've read: https://github.com/mscdex/node-imap/issues/881

This method is not working for me, I am afraid it only works with gmail and not suitable for azure/microsoft.

**Comment by mscdex** [comment]
@giacomobartoli The issue you linked to shows how to generate it. [Microsoft's site](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth) shows you the same thing. Perhaps you're missing some kind of configuration on the server.

**Comment by giacomobartoli** [comment]
@mscdex I managed to obtain a jwt token from Azure using ROPC auth.
Now, I manually insert the token using the following snippet of code:

```
const oauth2 = Buffer
.from([`user=${user}`, `auth=Bearer ${token}`, '', '']
.join('\x01'), 'utf-8')
.toString('base64');
```

And then:

```
const notifier = require('mail-notifier');

const mailListener = {
    xoauth2: oauth2,
    host: "outlook.office365.com",
    port: 993,
    tls: true,
    debug: console.log,
    authTimeout: 8000,
    connTimeout: 30000,
    tlsOptions: { 
      rejectUnauthorized: false,
      servername: 'outlook.office365.com'
    },
    markSeen: true
  }

 
 const n = notifier(mailListener);
 n.on('end', () => n.start()) // session closed
    .on('mail', mail => console.log(mail.from[0].address, mail.subject))
    .start();

```

The authentication fails with the following log:

<= '* OK The Microsoft Exchange IMAP4 service is ready. 
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
=> 'A1 AUTHENTICATE XOAUTH2 {{oauth2 string}}
<= 'A1 NO AUTHENTICATE failed.'

Does the server does not support XOAUTH2?
It is a migrated Azure mail address..

**Comment by mscdex** [comment]
I can't really help you then as I have no experience with Microsoft's IMAP service. Like I mentioned, I'd suggest double checking the scopes/permissions for your token. Otherwise you'll need to contact Microsoft.

**Comment by luixal** [comment]
Hi,

As I end up in this issue a couple days ago, I'm pasting here the code that worked for me, in case anyone else comes here.

You need to install the azure msal package for node:

```
npm i @azure/msal-node
```

and this is the code:

```js
const Imap = require('imap');
const msal = require("@azure/msal-node");

var imap;

// this function does the login using the client credentials flow:
async function login() {
  const msalConfig = {
    auth: {
      clientId: '<your-client-id>',
      authority: '<your-authority-id>',
      clientSecret: '<your-client-secret',
      // knownAuthorities: [config.imap.authority] not sure about this option, I didn't need to include it
    }
  };

  const tokenRequest = {
    scopes: ["https://outlook.office365.com/.default"] // this was my main point of failure, I was first using the graph url
  };

  // this function encodes the token into the XOAuth2 format needed by imap:
  const _build_XOAuth2_token = (user = '', access_token = '') => Buffer
    .from([`user=${user}`, `auth=Bearer ${access_token}`, '', '']
      .join('\x01'), 'utf-8')
    .toString('base64');

  try {
    // here you log in and get the token for the outlook scope:
    const cca = new msal.ConfidentialClientApplication(msalConfig);
    const authResponse = await cca.acquireTokenByClientCredential(tokenRequest);
    token = authResponse.accessToken;
    // here you build the imap object using the token formatted by the function above:
    imap = new Imap({
      xoauth2: _build_XOAuth2_token('<email-address-here>', token),
      host: 'outlook.office365.com',
      port: 993,
      tls: true,
      tlsOptions: {
        rejectUnauthorized: false,
        servername: config.imap.host
      }
    });
  } catch (err) {
    console.log('AUTH ERROR');
    console.log(err);
  }
}

// this function does not really "process" imap, but hooks the actions you want to perform once logged in:
function processImap() {
  imap.once('ready', function () {
    logger.info('Connected');
    imap.openBox('INBOX', !markAsRead, function (err, box) {

      if (err) throw err;
      imap.search(
        ['UNSEEN'],
        function (err, results) {
          if (err) throw err;

          if (!results.length) {
            // if now unread messages, log and end connection:
            logger.info('No new emails found');
            imap.end();

          } else {
            logger.info(`Found ${results.length} unread emails`)
            // if unread messages, fetch and process:
            var f = imap.fetch(results, {
              bodies: ['HEADER.FIELDS (FROM TO SUBJECT DATE)'],
              struct: true
            });

            f.on('message', function (msg, seqno) {
              // code to run for every message
            }

            f.once('error', function (err) {
              // code for error on message
            });
          }
        }
      );
    });
  });

  imap.once('error', function (err) {
    // error handling
    imap.end();
  });

  imap.once('end', function () {
    // do something nice when ending
    console.log('Connection ended);
  });
}

async function main() {
  await login();
  processImap();
  imap.connect();
}

main();
```

Cheers!

PS: @mscdex I think it would be a good idea to add something similar to this to the docs, just as an example, as this may be used by several people around. If you want and point me where to place it, I can make a PR with this doc.
