### ISSUE TITLE
Unable to connect to Gmail

### ISSUE THREAD

**Issue by dzg** [mscdex/node-imap#866]
Upon `imap.connect()` I get:
```
Uncaught Error: self signed certificate
...
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  source: 'socket',
  domainEmitter: Connection {
    _events: [Object: null prototype] { ready: [Function], end: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _config: {
      localAddress: undefined,
      socket: undefined,
      socketTimeout: 0,
      host: 'imap.gmail.com',
      port: 993,
      tls: true,
      tlsOptions: undefined,
      autotls: undefined,
      user: <my gmail id>,
      password: <my google app password>,
      xoauth: undefined,
      xoauth2: <my access token>,
      connTimeout: 10000,
      authTimeout: 5000,
      keepalive: true
    },
...
```

My IMAP is enabled; I have 2FA; I tried an App Password only (didn't work); I tried adding the `xoauth2` token.

Anyone can help? Thanks!

**Comment by dzg** [comment]
If set `tls: false` I get `Error: Timed out while authenticating with server`

**Comment by mscdex** [comment]
If you're getting a self-signed certificate error while connecting to a public server like gmail then that means someone is attempting to [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) your (secure) connection.

**Comment by mscdex** [comment]
You can usually find out who/what is trying to MITM your connection by connecting with OpenSSL:

```
openssl s_client -connect imap.gmail.com:993
```

It will show the supposed certificate of the server you're connecting to. Depending on the source of the MITM, it might be security software running locally on your PC, some content filtering running upstream on your network, or perhaps a malicious actor.

**Comment by dzg** [comment]
You're talking about stuff way above my paygrade :)

```

openssl s_client -connect imap.gmail.com:993
CONNECTED(00000006)
depth=3 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
verify return:1
depth=0 CN = imap.gmail.com
verify return:1
---
Certificate chain
 0 s:/CN=imap.gmail.com
   i:/C=US/O=Google Trust Services LLC/CN=GTS CA 1C3
 1 s:/C=US/O=Google Trust Services LLC/CN=GTS CA 1C3
   i:/C=US/O=Google Trust Services LLC/CN=GTS Root R1
 2 s:/C=US/O=Google Trust Services LLC/CN=GTS Root R1
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFUTCCBDmgAwIBAgIQLNwCsPXjvXkKAAAAAS+SVDANBgkqhkiG9w0BAQsFADBG
...
wEk+7iDYyeiGa91TnhwsI5wqq1MJ/tECj1LErb9AlRwPTcdGP/Rcw/oKxA+4it8n
fnDv6CcZPu8G8BZy9KkzhB2O1Mrb
-----END CERTIFICATE-----
subject=/CN=imap.gmail.com
issuer=/C=US/O=Google Trust Services LLC/CN=GTS CA 1C3
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 4859 bytes and written 281 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
...
```

Does that look wrong?

I use NextDNS, could that be interfering? You're scaring me.

**Comment by dzg** [comment]
Also I am able to connect over IMAP to Google via Mac Mail for example ... so shouldn't this work?

**Comment by dzg** [comment]
Also I am able to connect over IMAP to Google via Mac Mail for example ... so shouldn't this work?

**Comment by dzg** [comment]
This solved the issue for me: [https://stackoverflow.com/a/60126034/1166371](https://stackoverflow.com/a/60126034/1166371)

Add `tlsOptions: { rejectUnauthorized: false }`

**Comment by mscdex** [comment]
`tlsOptions: { rejectUnauthorized: false }` is not a secure solution. It's more of a "ignore any security errors" setting.

Out of curiosity, does https://github.com/mscdex/node-imap/pull/725 fix things for you?

**Comment by dzg** [comment]
> Out of curiosity, does #725 fix things for you?

Yes it does! Thanks!

**Comment by TechStudent10** [comment]
For everyone who still gets this error, you need to add `tlsOptions: {servername: "<imap server/host parameter>"}` to the `Imap()` object.
