### ISSUE TITLE
Google stops "less secure" apps access on May 22nd

### ISSUE THREAD

**Issue by Rigel772** [mscdex/node-imap#872]
Starting May 30, 2022, ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password...
Will node-imap still be  working with Gmail?

**Comment by mscdex** [comment]
Sure, use oauth2 for authentication instead. See the documentation for the `xoauth2` option in the readme.

**Comment by Rigel772** [comment]
From xoauth2 issues: 
"This library has been unmaintained for the last 7 years. Both Google and Microsoft have their own OAuth authentication libraries now, so there is no need for the xoauth2 library..." - I understand it does not work with Gmail.
Maybe the Readme should be updated?

**Comment by lacell75** [comment]
@Rigel772 I need to implement xoauth for gmail also. Do you find a solution?

**Comment by Rigel772** [comment]
sorry, did not
