### ISSUE TITLE
Maximum number of IMAP connections exceeded

### ISSUE THREAD

**Issue by blakegonzales** [mscdex/node-imap#882]
I've successfully been using imap-backup for a couple years now.  Thank you!

Today I ran across this issue in the log after traversing about 75% of my imap folders on the server.

> S: RUBY0001 NO [UNAVAILABLE] Maximum number of connections from user+IP exceeded (mail_max_userip_connections=30)

Is there a way to limit the number of connections imap-backup creates as it runs?

Thanks,
Blake

**Comment by mscdex** [comment]
I think you left this issue on the wrong repo?

**Comment by blakegonzales** [comment]
That I did!!  Sorry about that
