### ISSUE TITLE
Purpose of subscribebox

### ISSUE THREAD

**Issue by anshul-kai** [mscdex/node-imap#883]
What is the purpose of subscribebox if one can't really get events for mail on more than one box. In other words, openBox opens one box which you can add hooks to. Why use subscribebox?

**Comment by mscdex** [comment]
`subscribeBox()`/`unsubscribeBox()` are there for completeness and represent a part of IMAP that is more of a historical peculiarity. It has nothing to do with synchronization, notifications, or events. Originally the people who developed the IMAP specification envisioned users having usenet/newsgroup-like subscriptions. I've never seen this used/implemented anywhere, so you can basically ignore it.
