### ISSUE TITLE
Microsoft Outlook 2019 ERROR MESSAGE 503 BAD SEQUESCE OF COMMANDS

### ISSUE THREAD

**Issue by ALMedina0820** [mscdex/node-imap#916]
Hi Guys! One of our users reported about the email issue that she encountered. The user sent an email to one of their vendors, however the user received this message. "The following recipient(s) cannot be reached:  503 Bad sequence of commands (Please see the attached image).  And after several attempts, the email went through.

Btw, we are using a mail server "IONOS". 

Please give me an instruction on how to get rid of this. 

Thank you

![Jenna's issue](https://github.com/mscdex/node-imap/assets/163047075/c2ac9d10-967d-47dd-bad0-7941c82e8925)

**Comment by mscdex** [comment]
This has nothing to do with IMAP or `imap` the module.
